# 快速入門

本指南展示此軟體套件的基本用法範例，涵蓋了套件提供的最有用函數，可用來生成我[農曆網站](https://ytliu0.github.io/ChineseCalendar/index_chinese.html)的日曆資料。

## 安裝

用以下`pip`措令安裝及更新軟體套件。

In [1]:
#取消註解字串#來執行措令
#pip install --upgrade ChineseCalendar_py

## 載入軟體套件

In [2]:
import ChineseCalendar_py.calendar_conversion as ccal
from IPython.display import HTML
import pandas as pd

用以下指令建立中曆物件實例。輸入參數`'ChiT'`表示函數的輸出的語言是傳統中文，其他兩個可用的參數是`'Eng'`(英文)及`'ChiS'`(簡體中文)。

In [3]:
cal = ccal.calendar_conversion('ChiT')

## 公曆轉中曆

本軟體提供以下三個函數可用來轉公曆為中曆：

- `.western_to_chinese_date(y, m, d, ...)`: 公曆日期(y=年，m=月，d=日)轉中曆日期。

- `.western_to_chinese_year(y, m=None, ...)`: 公曆 y 年 m 月 中所有日期轉為中曆日期。如果 m 是 None，則將公曆年 y 中所有日期轉為中曆日期。

- `.western_to_chinese_year_html(y, m=None, ...)`: 與函數`.western_to_chinese_year(y, m=None, ...)`的功能一樣，但會輸出 HTML 格式的文字。

以上`...`表示函數還有其他可選的參數，但本指南不會討論，略去這些參數，函數執行時會取默認值。這些函數參數的用法在`tutorial/traditional_Chinese/tutorial.iynb`的深入指引中介紹。

以下指令將公曆2025年1月26日轉為中曆日期。

In [4]:
cal.western_to_chinese_date(2025, 1, 26)

{'Western ymd': [2025, 1, 26],
 'Western calendar': '格里曆',
 'JDN': 2460702,
 'Chinese ymd': [2024, 12, 27],
 'cyear': 2024,
 'cdate': '十二月廿七',
 'sexagenary year': ['甲辰', '龍', 41],
 'jian': ['建丁丑', 14],
 'Nday_cmonth': 29,
 'sexagenary date': ['乙未', 32],
 'Week': ['星期日', 0],
 'period': '現代 (1912 - )',
 'Chinese calendar': '紫金曆 (GB/T 33661-2017)'}

函數的輸出顯示公曆2025年1月26日是農曆2024年(甲辰年)十二月廿七日。

此函數的輸出是 python dictionary，有下列的字典鍵(keys):

`'Western ymd'`: python list 包含公曆的年月日。

`'Western calendar'`: 公曆版本 (格里曆、儒略曆或逆推儒略曆)。

`'JDN'`: 正午儒略日數。

`'Chinese ymd'`: 包含中曆的年月日，閏月的月份用負數表示。 

`'cyear'`: 與中曆年日期重疊最多的公曆年份，也是`'Chinese ymd'` list 中第一個數字。此例的甲辰年就是2024年，因為甲辰年始於2024年2月10日，終於2025年1月28日，甲辰年與公曆2024年有326日重疊，是重疊日數最多的公曆年，因此甲辰年的`'cyear'`取2024。

`'cdate'`: 中曆日期。

`'sexagenary year'`: python list 顯示年干支，年地支對應的生肖，及干支數 (1=甲子，2＝乙丑，3＝丙寅等，六十干支的干支數可參閱[干支網頁](https://ytliu0.github.io/ChineseCalendar/sexagenary_chinese.html)的表二) 。

`'jian'`: 中曆月的月建干支，月干支的詳情可參閱[干支網頁](https://ytliu0.github.io/ChineseCalendar/sexagenary_chinese.html)。

`'Nday_cmonth'`: 中曆月的日數，一般是29日或30日。

`'sexagenary date'`: 日干支及其干支數，日干支的詳情參閱[干支網頁](https://ytliu0.github.io/ChineseCalendar/sexagenary_chinese.html)。

`'Week'`: 星期及星期數，星期數用 0、1、2、3、4、5、6 表示星期日、一、二、三、四、五、六。 

`'period'`: 中國歷史的時代。

`'Chinese calendar'`: 中曆的版本。

與我的[農曆網站](https://ytliu0.github.io/ChineseCalendar/index_chinese.html)一樣，公曆年 y 的年限是 -721 至 2200。當中國處於分裂時代時常有多個曆法同時使用，這裡用的指令只提供其中一個版本，其他版本的日期也可以獲取，但要用上述`...`中的參數，本指南不會說明，如想知其用法，可參閱`tutorial/traditional_Chinese/tutorial.ipynb`的進階指引。

以下指令`cal.western_to_chinese_year(2025, 1)`輸出公曆2025年1月所有日期的中曆資料。指令 `cal.western_to_chinese_year(2025)`則顯示2025年全年的中曆日期資料。

In [5]:
cal.western_to_chinese_year(2025, 1)

[{'Western ymd': [2025, 1, 1],
  'Western calendar': '格里曆',
  'JDN': 2460677,
  'Chinese ymd': [2024, 12, 2],
  'cyear': 2024,
  'cdate': '十二月初二',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['庚午', 7],
  'Week': ['星期三', 3],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 2],
  'Western calendar': '格里曆',
  'JDN': 2460678,
  'Chinese ymd': [2024, 12, 3],
  'cyear': 2024,
  'cdate': '十二月初三',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['辛未', 8],
  'Week': ['星期四', 4],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 3],
  'Western calendar': '格里曆',
  'JDN': 2460679,
  'Chinese ymd': [2024, 12, 4],
  'cyear': 2024,
  'cdate': '十二月初四',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['壬申', 9],
  'Week': ['星期五', 5],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 4],
  'Western calendar': '格里曆',
  'JDN': 2460680,
  'Chinese ymd': [2024, 12, 5],
  'cyear': 2024,
  'cdate': '十二月初五',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['癸酉', 10],
  'Week': ['星期六', 6],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 5],
  'Western calendar': '格里曆',
  'JDN': 2460681,
  'Chinese ymd': [2024, 12, 6],
  'cyear': 2024,
  'cdate': '十二月初六',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['甲戌', 11],
  'Week': ['星期日', 0],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 6],
  'Western calendar': '格里曆',
  'JDN': 2460682,
  'Chinese ymd': [2024, 12, 7],
  'cyear': 2024,
  'cdate': '十二月初七',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['乙亥', 12],
  'Week': ['星期一', 1],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 7],
  'Western calendar': '格里曆',
  'JDN': 2460683,
  'Chinese ymd': [2024, 12, 8],
  'cyear': 2024,
  'cdate': '十二月初八',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['丙子', 13],
  'Week': ['星期二', 2],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 8],
  'Western calendar': '格里曆',
  'JDN': 2460684,
  'Chinese ymd': [2024, 12, 9],
  'cyear': 2024,
  'cdate': '十二月初九',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['丁丑', 14],
  'Week': ['星期三', 3],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 9],
  'Western calendar': '格里曆',
  'JDN': 2460685,
  'Chinese ymd': [2024, 12, 10],
  'cyear': 2024,
  'cdate': '十二月初十',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['戊寅', 15],
  'Week': ['星期四', 4],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 10],
  'Western calendar': '格里曆',
  'JDN': 2460686,
  'Chinese ymd': [2024, 12, 11],
  'cyear': 2024,
  'cdate': '十二月十一',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['己卯', 16],
  'Week': ['星期五', 5],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 11],
  'Western calendar': '格里曆',
  'JDN': 2460687,
  'Chinese ymd': [2024, 12, 12],
  'cyear': 2024,
  'cdate': '十二月十二',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['庚辰', 17],
  'Week': ['星期六', 6],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 12],
  'Western calendar': '格里曆',
  'JDN': 2460688,
  'Chinese ymd': [2024, 12, 13],
  'cyear': 2024,
  'cdate': '十二月十三',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['辛巳', 18],
  'Week': ['星期日', 0],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 13],
  'Western calendar': '格里曆',
  'JDN': 2460689,
  'Chinese ymd': [2024, 12, 14],
  'cyear': 2024,
  'cdate': '十二月十四',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['壬午', 19],
  'Week': ['星期一', 1],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 14],
  'Western calendar': '格里曆',
  'JDN': 2460690,
  'Chinese ymd': [2024, 12, 15],
  'cyear': 2024,
  'cdate': '十二月十五',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['癸未', 20],
  'Week': ['星期二', 2],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 15],
  'Western calendar': '格里曆',
  'JDN': 2460691,
  'Chinese ymd': [2024, 12, 16],
  'cyear': 2024,
  'cdate': '十二月十六',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['甲申', 21],
  'Week': ['星期三', 3],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 16],
  'Western calendar': '格里曆',
  'JDN': 2460692,
  'Chinese ymd': [2024, 12, 17],
  'cyear': 2024,
  'cdate': '十二月十七',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['乙酉', 22],
  'Week': ['星期四', 4],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 17],
  'Western calendar': '格里曆',
  'JDN': 2460693,
  'Chinese ymd': [2024, 12, 18],
  'cyear': 2024,
  'cdate': '十二月十八',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['丙戌', 23],
  'Week': ['星期五', 5],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 18],
  'Western calendar': '格里曆',
  'JDN': 2460694,
  'Chinese ymd': [2024, 12, 19],
  'cyear': 2024,
  'cdate': '十二月十九',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['丁亥', 24],
  'Week': ['星期六', 6],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 19],
  'Western calendar': '格里曆',
  'JDN': 2460695,
  'Chinese ymd': [2024, 12, 20],
  'cyear': 2024,
  'cdate': '十二月二十',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['戊子', 25],
  'Week': ['星期日', 0],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 20],
  'Western calendar': '格里曆',
  'JDN': 2460696,
  'Chinese ymd': [2024, 12, 21],
  'cyear': 2024,
  'cdate': '十二月廿一',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['己丑', 26],
  'Week': ['星期一', 1],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 21],
  'Western calendar': '格里曆',
  'JDN': 2460697,
  'Chinese ymd': [2024, 12, 22],
  'cyear': 2024,
  'cdate': '十二月廿二',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['庚寅', 27],
  'Week': ['星期二', 2],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 22],
  'Western calendar': '格里曆',
  'JDN': 2460698,
  'Chinese ymd': [2024, 12, 23],
  'cyear': 2024,
  'cdate': '十二月廿三',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['辛卯', 28],
  'Week': ['星期三', 3],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 23],
  'Western calendar': '格里曆',
  'JDN': 2460699,
  'Chinese ymd': [2024, 12, 24],
  'cyear': 2024,
  'cdate': '十二月廿四',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['壬辰', 29],
  'Week': ['星期四', 4],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 24],
  'Western calendar': '格里曆',
  'JDN': 2460700,
  'Chinese ymd': [2024, 12, 25],
  'cyear': 2024,
  'cdate': '十二月廿五',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['癸巳', 30],
  'Week': ['星期五', 5],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 25],
  'Western calendar': '格里曆',
  'JDN': 2460701,
  'Chinese ymd': [2024, 12, 26],
  'cyear': 2024,
  'cdate': '十二月廿六',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['甲午', 31],
  'Week': ['星期六', 6],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 26],
  'Western calendar': '格里曆',
  'JDN': 2460702,
  'Chinese ymd': [2024, 12, 27],
  'cyear': 2024,
  'cdate': '十二月廿七',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['乙未', 32],
  'Week': ['星期日', 0],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 27],
  'Western calendar': '格里曆',
  'JDN': 2460703,
  'Chinese ymd': [2024, 12, 28],
  'cyear': 2024,
  'cdate': '十二月廿八',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['丙申', 33],
  'Week': ['星期一', 1],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 28],
  'Western calendar': '格里曆',
  'JDN': 2460704,
  'Chinese ymd': [2024, 12, 29],
  'cyear': 2024,
  'cdate': '十二月廿九',
  'sexagenary year': ['甲辰', '龍', 41],
  'jian': ['建丁丑', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['丁酉', 34],
  'Week': ['星期二', 2],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 29],
  'Western calendar': '格里曆',
  'JDN': 2460705,
  'Chinese ymd': [2025, 1, 1],
  'cyear': 2025,
  'cdate': '正月初一',
  'sexagenary year': ['乙巳', '蛇', 42],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊戌', 35],
  'Week': ['星期三', 3],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 30],
  'Western calendar': '格里曆',
  'JDN': 2460706,
  'Chinese ymd': [2025, 1, 2],
  'cyear': 2025,
  'cdate': '正月初二',
  'sexagenary year': ['乙巳', '蛇', 42],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['己亥', 36],
  'Week': ['星期四', 4],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 31],
  'Western calendar': '格里曆',
  'JDN': 2460707,
  'Chinese ymd': [2025, 1, 3],
  'cyear': 2025,
  'cdate': '正月初三',
  'sexagenary year': ['乙巳', '蛇', 42],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚子', 37],
  'Week': ['星期五', 5],
  'period': '現代 (1912 - )',
  'Chinese calendar': '紫金曆 (GB/T 33661-2017)'}]

以上的輸出如果用於其後的日曆計算或許有用，但對於瀏覽來說並不是很方便，函數`.western_to_chinese_year_html()`輸出的 HTML 文字用`IPython.display.HTML()`的函數處理後，就會得到如[這農曆網頁](https://ytliu0.github.io/ChineseCalendar/index_chinese.html)的表列顯示，比較方便瀏覽。

In [6]:
# 2025年11月的月曆表 
HTML(cal.western_to_chinese_year_html(2025, 11))

In [7]:
# 1979年的年曆表
HTML(cal.western_to_chinese_year_html(1979))

In [8]:
# 公曆 690 年的年曆表 
HTML(cal.western_to_chinese_year_html(690))

上面列出的月相和二十四節氣如[農曆網站](https://ytliu0.github.io/ChineseCalendar/index_chinese.html)的一樣是指用現代方法以噴射推進實驗室的 DE441 曆表算出，而曆書節氣指按當時中國曆法算出的節氣日期。

中國科學院紫金山天文臺從 2014年起用 DE421 曆表編算天文年曆，直至2025年還沒有更新曆表，不過 DE421 算出的月相和節氣時刻在現代相差甚微。所有用現代曆表算出的月相和節氣時刻都用東八區時間 UT+8 (UT 在1972年前指 UT1， 1972年到今年指 UTC，未來年份則是預推的 UTC)。

## 中曆轉公曆

本軟體提供以下四個函數可用來轉中曆為公曆：

`.chinese_to_western_date(y, m, d, ...)`: 轉中曆年月日 y, m, d 為公曆日期，閏月的 m 值為負數。

`.chinese_year_info(y, ...)`: 此函數輸出中曆年 y 的所有中曆月初一的公曆日期，曆書節氣，及用現代曆表 DE441 算出的節氣。

`.chinese_year_html(y, ...)`: 與上述函數的功能一致，但輸出 HTML 文字。

`.chinese_to_western_year(y, m=None, ...)`: 列出中曆年 y 中曆月 m 所有日期的公曆日期。如果 m 是 None，則列出中曆年全年的公曆日期。

`chinese_to_western_year_html(y, m=None, ...)`: 與上述函數的功能一致，但輸出 HTML 文字。

同上， `...`表示其他可選的參數，但本指南不會討論。

In [9]:
# 轉 2025年農曆七月初七為公曆
cal.chinese_to_western_date(2025, 7, 7)

{'Chinese ymd': [2025, 7, 7],
 'Western ymd': [2025, 8, 29],
 'Western calendar': '格里曆',
 'JDN': 2460917,
 'cyear': 2025,
 'cdate': '七月初七',
 'sexagenary year': ['乙巳', '蛇', 42],
 'jian': ['建甲申', 21],
 'Nday_cmonth': 30,
 'sexagenary date': ['庚午', 7],
 'Week': ['星期五', 5],
 'period': '現代 (1912 - )',
 'Chinese calendar': '紫金曆 (GB/T 33661-2017)'}

由於曆法變更，歷史上有少數情況某中曆日期對應兩個公曆日期。例如武周聖曆三年/久視元年(700年)的十一月(當時稱為正月)和十二月。以下指令顯示700年十一月廿三日對應公曆日期是699年12月19日及701年1月6日。

In [10]:
cal.chinese_to_western_date(700, 11, 23)

[{'Chinese ymd': [700, 11, 23],
  'Western ymd': [699, 12, 19],
  'Western calendar': '儒略曆',
  'JDN': 1976720,
  'cyear': 700,
  'cdate': '正月廿三',
  'sexagenary year': ['庚子', '鼠', 37],
  'jian': ['建丙子', 13],
  'Nday_cmonth': 30,
  'sexagenary date': ['癸酉', 10],
  'Week': ['星期五', 5],
  'period': '唐 (618 - 907)',
  'reign/era': '武周聖曆三年/久視元年',
  'Chinese calendar': '麟德曆'},
 {'Chinese ymd': [700, 11, 23],
  'Western ymd': [701, 1, 6],
  'Western calendar': '儒略曆',
  'JDN': 1977104,
  'cyear': 700,
  'cdate': '十一月廿三',
  'sexagenary year': ['庚子', '鼠', 37],
  'jian': ['建戊子', 25],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁酉', 34],
  'Week': ['星期四', 4],
  'period': '唐 (618 - 907)',
  'reign/era': '武周聖曆三年/久視元年',
  'Chinese calendar': '麟德曆'}]

以下指令輸出中曆700年的曆日資料。

In [11]:
cal.chinese_year_info(700)

{'cm': [{'cm': 11, 'JDN': 1976698, 'jian': '13', 'n': 30},
  {'cm': 12, 'JDN': 1976728, 'jian': '14', 'n': 30},
  {'cm': 1, 'JDN': 1976758, 'jian': '15', 'n': 30},
  {'cm': 2, 'JDN': 1976788, 'jian': '16', 'n': 29},
  {'cm': 3, 'JDN': 1976817, 'jian': '17', 'n': 30},
  {'cm': 4, 'JDN': 1976847, 'jian': '18', 'n': 29},
  {'cm': 5, 'JDN': 1976876, 'jian': '19', 'n': 29},
  {'cm': 6, 'JDN': 1976905, 'jian': '20', 'n': 30},
  {'cm': 7, 'JDN': 1976935, 'jian': '21', 'n': 29},
  {'cm': -7, 'JDN': 1976964, 'jian': 'NA', 'n': 29},
  {'cm': 8, 'JDN': 1976993, 'jian': '22', 'n': 30},
  {'cm': 9, 'JDN': 1977023, 'jian': '23', 'n': 29},
  {'cm': 10, 'JDN': 1977052, 'jian': '24', 'n': 30},
  {'cm': 11, 'JDN': 1977082, 'jian': '25', 'n': 30},
  {'cm': 12, 'JDN': 1977112, 'jian': '26', 'n': 30}],
 'calendar': '麟德曆',
 'reign/era': '武周聖曆三年/久視元年',
 'calst': [('J11', 1976704),
  ('Z11', 1976719),
  ('J12', 1976735),
  ('Z12', 1976750),
  ('J1', 1976765),
  ('Z1', 1976780),
  ('J2', 1976796),
  ('Z2', 1976811),
  ('J3', 1976826),
  ('Z3', 1976841),
  ('J4', 1976856),
  ('Z4', 1976872),
  ('J5', 1976887),
  ('Z5', 1976902),
  ('J6', 1976917),
  ('Z6', 1976933),
  ('J7', 1976948),
  ('Z7', 1976963),
  ('J8', 1976978),
  ('Z8', 1976993),
  ('J9', 1977009),
  ('Z9', 1977024),
  ('J10', 1977039),
  ('Z10', 1977054),
  ('J11', 1977070),
  ('Z11', 1977085),
  ('J12', 1977100),
  ('Z12', 1977115),
  ('J1', 1977130)],
 'datongST': [],
 'sterm': [['J11',
   {'event': '大雪',
    'year': 699,
    'month': 12,
    'date': 4,
    'hour': 6,
    'minute': 7,
    'dateString': '12月4日',
    'timeString': '06:07',
    'jd0_ut': 1976366.5,
    'jd1_ut': 337.9215101693816}],
  ['Z11',
   {'event': '冬至',
    'year': 699,
    'month': 12,
    'date': 18,
    'hour': 23,
    'minute': 4,
    'dateString': '12月18日',
    'timeString': '23:04',
    'jd0_ut': 1976366.5,
    'jd1_ut': 352.62778805956}],
  ['J12',
   {'event': '小寒',
    'year': 700,
    'month': 1,
    'date': 2,
    'hour': 16,
    'minute': 21,
    'dateString': '1月2日',
    'timeString': '16:21',
    'jd0_ut': 1976731.5,
    'jd1_ut': 2.3481674345704246}],
  ['Z12',
   {'event': '大寒',
    'year': 700,
    'month': 1,
    'date': 17,
    'hour': 11,
    'minute': 6,
    'dateString': '1月17日',
    'timeString': '11:06',
    'jd0_ut': 1976731.5,
    'jd1_ut': 17.12891498304114}],
  ['J1',
   {'event': '立春',
    'year': 700,
    'month': 2,
    'date': 1,
    'hour': 7,
    'minute': 40,
    'dateString': '2月1日',
    'timeString': '07:40',
    'jd0_ut': 1976731.5,
    'jd1_ut': 31.98584674592126}],
  ['Z1',
   {'event': '雨水',
    'year': 700,
    'month': 2,
    'date': 16,
    'hour': 6,
    'minute': 58,
    'dateString': '2月16日',
    'timeString': '06:58',
    'jd0_ut': 1976731.5,
    'jd1_ut': 46.95714066913762}],
  ['J2',
   {'event': '驚蟄',
    'year': 700,
    'month': 3,
    'date': 2,
    'hour': 9,
    'minute': 7,
    'dateString': '3月2日',
    'timeString': '09:07',
    'jd0_ut': 1976731.5,
    'jd1_ut': 62.04677931037536}],
  ['Z2',
   {'event': '春分',
    'year': 700,
    'month': 3,
    'date': 17,
    'hour': 14,
    'minute': 41,
    'dateString': '3月17日',
    'timeString': '14:41',
    'jd0_ut': 1976731.5,
    'jd1_ut': 77.27854363767912}],
  ['J3',
   {'event': '清明',
    'year': 700,
    'month': 4,
    'date': 1,
    'hour': 23,
    'minute': 20,
    'dateString': '4月1日',
    'timeString': '23:20',
    'jd0_ut': 1976731.5,
    'jd1_ut': 92.63889503223206}],
  ['Z3',
   {'event': '穀雨',
    'year': 700,
    'month': 4,
    'date': 17,
    'hour': 11,
    'minute': 12,
    'dateString': '4月17日',
    'timeString': '11:12',
    'jd0_ut': 1976731.5,
    'jd1_ut': 108.13359658092664}],
  ['J4',
   {'event': '立夏',
    'year': 700,
    'month': 5,
    'date': 3,
    'hour': 1,
    'minute': 32,
    'dateString': '5月3日',
    'timeString': '01:32',
    'jd0_ut': 1976731.5,
    'jd1_ut': 123.73032607134814}],
  ['Z4',
   {'event': '小滿',
    'year': 700,
    'month': 5,
    'date': 18,
    'hour': 18,
    'minute': 0,
    'dateString': '5月18日',
    'timeString': '18:00',
    'jd0_ut': 1976731.5,
    'jd1_ut': 139.41690309829764}],
  ['J5',
   {'event': '芒種',
    'year': 700,
    'month': 6,
    'date': 3,
    'hour': 11,
    'minute': 33,
    'dateString': '6月3日',
    'timeString': '11:33',
    'jd0_ut': 1976731.5,
    'jd1_ut': 155.14802213267387}],
  ['Z5',
   {'event': '夏至',
    'year': 700,
    'month': 6,
    'date': 19,
    'hour': 5,
    'minute': 34,
    'dateString': '6月19日',
    'timeString': '05:34',
    'jd0_ut': 1976731.5,
    'jd1_ut': 170.89835912068702}],
  ['J6',
   {'event': '小暑',
    'year': 700,
    'month': 7,
    'date': 4,
    'hour': 22,
    'minute': 55,
    'dateString': '7月4日',
    'timeString': '22:55',
    'jd0_ut': 1976731.5,
    'jd1_ut': 186.62150729515815}],
  ['Z6',
   {'event': '大暑',
    'year': 700,
    'month': 7,
    'date': 20,
    'hour': 14,
    'minute': 55,
    'dateString': '7月20日',
    'timeString': '14:55',
    'jd0_ut': 1976731.5,
    'jd1_ut': 202.2881220833286}],
  ['J7',
   {'event': '立秋',
    'year': 700,
    'month': 8,
    'date': 5,
    'hour': 4,
    'minute': 44,
    'dateString': '8月5日',
    'timeString': '04:44',
    'jd0_ut': 1976731.5,
    'jd1_ut': 217.86380357633357}],
  ['Z7',
   {'event': '處暑',
    'year': 700,
    'month': 8,
    'date': 20,
    'hour': 15,
    'minute': 48,
    'dateString': '8月20日',
    'timeString': '15:48',
    'jd0_ut': 1976731.5,
    'jd1_ut': 233.32488180149394}],
  ['J8',
   {'event': '白露',
    'year': 700,
    'month': 9,
    'date': 4,
    'hour': 23,
    'minute': 47,
    'dateString': '9月4日',
    'timeString': '23:47',
    'jd0_ut': 1976731.5,
    'jd1_ut': 248.65748931951256}],
  ['Z8',
   {'event': '秋分',
    'year': 700,
    'month': 9,
    'date': 20,
    'hour': 4,
    'minute': 26,
    'dateString': '9月20日',
    'timeString': '04:26',
    'jd0_ut': 1976731.5,
    'jd1_ut': 263.8511791635494}],
  ['J9',
   {'event': '寒露',
    'year': 700,
    'month': 10,
    'date': 5,
    'hour': 5,
    'minute': 57,
    'dateString': '10月5日',
    'timeString': '05:57',
    'jd0_ut': 1976731.5,
    'jd1_ut': 278.9142605761686}],
  ['Z9',
   {'event': '霜降',
    'year': 700,
    'month': 10,
    'date': 20,
    'hour': 4,
    'minute': 27,
    'dateString': '10月20日',
    'timeString': '04:27',
    'jd0_ut': 1976731.5,
    'jd1_ut': 293.85207611782624}],
  ['J10',
   {'event': '立冬',
    'year': 700,
    'month': 11,
    'date': 4,
    'hour': 0,
    'minute': 35,
    'dateString': '11月4日',
    'timeString': '00:35',
    'jd0_ut': 1976731.5,
    'jd1_ut': 308.69123727544155}],
  ['Z10',
   {'event': '小雪',
    'year': 700,
    'month': 11,
    'date': 18,
    'hour': 18,
    'minute': 48,
    'dateString': '11月18日',
    'timeString': '18:48',
    'jd0_ut': 1976731.5,
    'jd1_ut': 323.4502977908783}],
  ['J11',
   {'event': '大雪',
    'year': 700,
    'month': 12,
    'date': 3,
    'hour': 12,
    'minute': 0,
    'dateString': '12月3日',
    'timeString': '12:00',
    'jd0_ut': 1976731.5,
    'jd1_ut': 338.1670075413189}],
  ['Z11',
   {'event': '冬至',
    'year': 700,
    'month': 12,
    'date': 18,
    'hour': 4,
    'minute': 49,
    'dateString': '12月18日',
    'timeString': '04:49',
    'jd0_ut': 1976731.5,
    'jd1_ut': 352.86744622431104}],
  ['J12',
   {'event': '小寒',
    'year': 701,
    'month': 1,
    'date': 1,
    'hour': 22,
    'minute': 13,
    'dateString': '1月1日',
    'timeString': '22:13',
    'jd0_ut': 1977097.5,
    'jd1_ut': 1.5922736895132177}],
  ['Z12',
   {'event': '大寒',
    'year': 701,
    'month': 1,
    'date': 16,
    'hour': 16,
    'minute': 49,
    'dateString': '1月16日',
    'timeString': '16:49',
    'jd0_ut': 1977097.5,
    'jd1_ut': 16.367678836813926}],
  ['J1',
   {'event': '立春',
    'year': 701,
    'month': 1,
    'date': 31,
    'hour': 13,
    'minute': 30,
    'dateString': '1月31日',
    'timeString': '13:30',
    'jd0_ut': 1977097.5,
    'jd1_ut': 31.229459936626977}]],
 'mphase': [['Q0',
   {'event': '朔',
    'year': 699,
    'month': 11,
    'date': 27,
    'hour': 18,
    'minute': 27,
    'dateString': '11月27日',
    'timeString': '18:27',
    'jd0_ut': 1976366.5,
    'jd1_ut': 331.4357120734951,
    'eclipse': '日環食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=601&ind=248&DE=441&ref=python'}],
  ['Q1',
   {'event': '上弦',
    'year': 699,
    'month': 12,
    'date': 5,
    'hour': 23,
    'minute': 43,
    'dateString': '12月5日',
    'timeString': '23:43',
    'jd0_ut': 1976366.5,
    'jd1_ut': 339.6547673874774}],
  ['Q2',
   {'event': '望',
    'year': 699,
    'month': 12,
    'date': 12,
    'hour': 22,
    'minute': 53,
    'dateString': '12月12日',
    'timeString': '22:53',
    'jd0_ut': 1976366.5,
    'jd1_ut': 346.6200537443031,
    'eclipse': '半影月食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=601&ind=254&DE=441&shrule=revised_Danjon&ref=python'}],
  ['Q3',
   {'event': '下弦',
    'year': 699,
    'month': 12,
    'date': 19,
    'hour': 14,
    'minute': 30,
    'dateString': '12月19日',
    'timeString': '14:30',
    'jd0_ut': 1976366.5,
    'jd1_ut': 353.2708277570382}],
  ['Q0',
   {'event': '朔',
    'year': 699,
    'month': 12,
    'date': 27,
    'hour': 14,
    'minute': 8,
    'dateString': '12月27日',
    'timeString': '14:08',
    'jd0_ut': 1976366.5,
    'jd1_ut': 361.2553242897828}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 1,
    'date': 4,
    'hour': 15,
    'minute': 55,
    'dateString': '1月4日',
    'timeString': '15:55',
    'jd0_ut': 1976731.5,
    'jd1_ut': 4.329952425347095}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 1,
    'date': 11,
    'hour': 9,
    'minute': 43,
    'dateString': '1月11日',
    'timeString': '09:43',
    'jd0_ut': 1976731.5,
    'jd1_ut': 11.071642169442}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 1,
    'date': 18,
    'hour': 4,
    'minute': 57,
    'dateString': '1月18日',
    'timeString': '04:57',
    'jd0_ut': 1976731.5,
    'jd1_ut': 17.873138425217537}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 1,
    'date': 26,
    'hour': 9,
    'minute': 29,
    'dateString': '1月26日',
    'timeString': '09:29',
    'jd0_ut': 1976731.5,
    'jd1_ut': 26.061944848194486}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 2,
    'date': 3,
    'hour': 4,
    'minute': 38,
    'dateString': '2月3日',
    'timeString': '04:38',
    'jd0_ut': 1976731.5,
    'jd1_ut': 33.859527520457966}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 2,
    'date': 9,
    'hour': 19,
    'minute': 52,
    'dateString': '2月9日',
    'timeString': '19:52',
    'jd0_ut': 1976731.5,
    'jd1_ut': 40.494611271081574}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 2,
    'date': 16,
    'hour': 22,
    'minute': 3,
    'dateString': '2月16日',
    'timeString': '22:03',
    'jd0_ut': 1976731.5,
    'jd1_ut': 47.58567921385633}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 2,
    'date': 25,
    'hour': 2,
    'minute': 50,
    'dateString': '2月25日',
    'timeString': '02:50',
    'jd0_ut': 1976731.5,
    'jd1_ut': 55.78494146449858}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 3,
    'date': 3,
    'hour': 13,
    'minute': 54,
    'dateString': '3月3日',
    'timeString': '13:54',
    'jd0_ut': 1976731.5,
    'jd1_ut': 63.24560192530407}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 3,
    'date': 10,
    'hour': 5,
    'minute': 46,
    'dateString': '3月10日',
    'timeString': '05:46',
    'jd0_ut': 1976731.5,
    'jd1_ut': 69.90726973766519}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 3,
    'date': 17,
    'hour': 16,
    'minute': 39,
    'dateString': '3月17日',
    'timeString': '16:39',
    'jd0_ut': 1976731.5,
    'jd1_ut': 77.36049855715197}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 3,
    'date': 25,
    'hour': 17,
    'minute': 25,
    'dateString': '3月25日',
    'timeString': '17:25',
    'jd0_ut': 1976731.5,
    'jd1_ut': 85.39234181637907}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 4,
    'date': 1,
    'hour': 20,
    'minute': 25,
    'dateString': '4月1日',
    'timeString': '20:25',
    'jd0_ut': 1976731.5,
    'jd1_ut': 92.51712304239679}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 4,
    'date': 8,
    'hour': 16,
    'minute': 10,
    'dateString': '4月8日',
    'timeString': '16:10',
    'jd0_ut': 1976731.5,
    'jd1_ut': 99.34036401967046}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 4,
    'date': 16,
    'hour': 11,
    'minute': 15,
    'dateString': '4月16日',
    'timeString': '11:15',
    'jd0_ut': 1976731.5,
    'jd1_ut': 107.13570307978425}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 4,
    'date': 24,
    'hour': 5,
    'minute': 14,
    'dateString': '4月24日',
    'timeString': '05:14',
    'jd0_ut': 1976731.5,
    'jd1_ut': 114.88467191180538}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 5,
    'date': 1,
    'hour': 1,
    'minute': 23,
    'dateString': '5月1日',
    'timeString': '01:23',
    'jd0_ut': 1976731.5,
    'jd1_ut': 121.72429054274421}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 5,
    'date': 8,
    'hour': 3,
    'minute': 44,
    'dateString': '5月8日',
    'timeString': '03:44',
    'jd0_ut': 1976731.5,
    'jd1_ut': 128.8225468598756,
    'eclipse': '半影月食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=601&ind=255&DE=441&shrule=revised_Danjon&ref=python'}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 5,
    'date': 16,
    'hour': 4,
    'minute': 40,
    'dateString': '5月16日',
    'timeString': '04:40',
    'jd0_ut': 1976731.5,
    'jd1_ut': 136.86135004661148}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 5,
    'date': 23,
    'hour': 14,
    'minute': 43,
    'dateString': '5月23日',
    'timeString': '14:43',
    'jd0_ut': 1976731.5,
    'jd1_ut': 144.28011332830945,
    'eclipse': '日全食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=601&ind=249&DE=441&ref=python'}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 5,
    'date': 30,
    'hour': 6,
    'minute': 18,
    'dateString': '5月30日',
    'timeString': '06:18',
    'jd0_ut': 1976731.5,
    'jd1_ut': 150.92934077397865}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 6,
    'date': 6,
    'hour': 16,
    'minute': 49,
    'dateString': '6月6日',
    'timeString': '16:49',
    'jd0_ut': 1976731.5,
    'jd1_ut': 158.36764579887225}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 6,
    'date': 14,
    'hour': 20,
    'minute': 16,
    'dateString': '6月14日',
    'timeString': '20:16',
    'jd0_ut': 1976731.5,
    'jd1_ut': 166.51078961120638}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 6,
    'date': 21,
    'hour': 22,
    'minute': 34,
    'dateString': '6月21日',
    'timeString': '22:34',
    'jd0_ut': 1976731.5,
    'jd1_ut': 173.60664655657408}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 6,
    'date': 28,
    'hour': 12,
    'minute': 43,
    'dateString': '6月28日',
    'timeString': '12:43',
    'jd0_ut': 1976731.5,
    'jd1_ut': 180.1966689578949}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 7,
    'date': 6,
    'hour': 7,
    'minute': 19,
    'dateString': '7月6日',
    'timeString': '07:19',
    'jd0_ut': 1976731.5,
    'jd1_ut': 187.97161356717876}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 7,
    'date': 14,
    'hour': 9,
    'minute': 48,
    'dateString': '7月14日',
    'timeString': '09:48',
    'jd0_ut': 1976731.5,
    'jd1_ut': 196.07514555433985}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 7,
    'date': 21,
    'hour': 5,
    'minute': 37,
    'dateString': '7月21日',
    'timeString': '05:37',
    'jd0_ut': 1976731.5,
    'jd1_ut': 202.9006064032989}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 7,
    'date': 27,
    'hour': 21,
    'minute': 59,
    'dateString': '7月27日',
    'timeString': '21:59',
    'jd0_ut': 1976731.5,
    'jd1_ut': 209.58274818984617}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 8,
    'date': 4,
    'hour': 22,
    'minute': 51,
    'dateString': '8月4日',
    'timeString': '22:51',
    'jd0_ut': 1976731.5,
    'jd1_ut': 217.61878323204536}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 8,
    'date': 12,
    'hour': 21,
    'minute': 18,
    'dateString': '8月12日',
    'timeString': '21:18',
    'jd0_ut': 1976731.5,
    'jd1_ut': 225.55434502125357}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 8,
    'date': 19,
    'hour': 12,
    'minute': 56,
    'dateString': '8月19日',
    'timeString': '12:56',
    'jd0_ut': 1976731.5,
    'jd1_ut': 232.20569791630103}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 8,
    'date': 26,
    'hour': 10,
    'minute': 59,
    'dateString': '8月26日',
    'timeString': '10:59',
    'jd0_ut': 1976731.5,
    'jd1_ut': 239.12435959494346}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 9,
    'date': 3,
    'hour': 14,
    'minute': 57,
    'dateString': '9月3日',
    'timeString': '14:57',
    'jd0_ut': 1976731.5,
    'jd1_ut': 247.28942618687475}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 9,
    'date': 11,
    'hour': 6,
    'minute': 55,
    'dateString': '9月11日',
    'timeString': '06:55',
    'jd0_ut': 1976731.5,
    'jd1_ut': 254.95503692092132}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 9,
    'date': 17,
    'hour': 21,
    'minute': 39,
    'dateString': '9月17日',
    'timeString': '21:39',
    'jd0_ut': 1976731.5,
    'jd1_ut': 261.5684137474932}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 9,
    'date': 25,
    'hour': 3,
    'minute': 51,
    'dateString': '9月25日',
    'timeString': '03:51',
    'jd0_ut': 1976731.5,
    'jd1_ut': 268.82686881350537}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 10,
    'date': 3,
    'hour': 7,
    'minute': 4,
    'dateString': '10月3日',
    'timeString': '07:04',
    'jd0_ut': 1976731.5,
    'jd1_ut': 276.96131142970205}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 10,
    'date': 10,
    'hour': 15,
    'minute': 5,
    'dateString': '10月10日',
    'timeString': '15:05',
    'jd0_ut': 1976731.5,
    'jd1_ut': 284.2953053181167}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 10,
    'date': 17,
    'hour': 8,
    'minute': 41,
    'dateString': '10月17日',
    'timeString': '08:41',
    'jd0_ut': 1976731.5,
    'jd1_ut': 291.0282895938344}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 10,
    'date': 24,
    'hour': 23,
    'minute': 49,
    'dateString': '10月24日',
    'timeString': '23:49',
    'jd0_ut': 1976731.5,
    'jd1_ut': 298.6591313744126}],
  ['Q2',
   {'event': '望',
    'year': 700,
    'month': 11,
    'date': 1,
    'hour': 22,
    'minute': 35,
    'dateString': '11月1日',
    'timeString': '22:35',
    'jd0_ut': 1976731.5,
    'jd1_ut': 306.60729885913,
    'eclipse': '月偏食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=601&ind=256&DE=441&shrule=revised_Danjon&ref=python'}],
  ['Q3',
   {'event': '下弦',
    'year': 700,
    'month': 11,
    'date': 8,
    'hour': 22,
    'minute': 37,
    'dateString': '11月8日',
    'timeString': '22:37',
    'jd0_ut': 1976731.5,
    'jd1_ut': 313.6088303155866}],
  ['Q0',
   {'event': '朔',
    'year': 700,
    'month': 11,
    'date': 15,
    'hour': 22,
    'minute': 30,
    'dateString': '11月15日',
    'timeString': '22:30',
    'jd0_ut': 1976731.5,
    'jd1_ut': 320.60438975135355,
    'eclipse': '日環食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=601&ind=250&DE=441&ref=python'}],
  ['Q1',
   {'event': '上弦',
    'year': 700,
    'month': 11,
    'date': 23,
    'hour': 21,
    'minute': 25,

此函數輸出 python dictionary，有以下字鍵：

`'cm'`: python list 含有以下中曆資料： \[{'cm':m1, 'JDN':JDN1, 'jian':'jian1', 'n':n1}, {'cm':m2, 'JDN':JDN2, 'jian':'jian2', 'n':n2}, ...\]，'cm' 表示中曆月序(負數表示閏月), 'JDN' 表示朔日的正午儒略日數， 'jian' 表示用月建來算的月干支數 ('jian'='1' 表示甲子，'2' 表示乙丑，⋯⋯，'60' 表示癸亥，'NA' 表示中曆月沒有月建，一般是閏月，但-103年以前的曆法因不用無中氣置閏也不列月建，'NZ' 表示此月不含中氣，這只適用於古六曆的月份)，'n' 表示中曆月的日數。 此 python list 以 'JDN' 的數值由小至大排序。

`'calendar'`: 中曆的版本 (例如 '三統曆'， '時憲曆' 等)。

`'reign/era'` (只適用於 1912年前的年份): 中曆年的年號或皇帝紀年。

`'calst'`: 曆書節氣 tuples \[(lab1, jdn1), (lab2, jdn2), ...\]， lab1, lab2, ... 是曆書節氣的標記，例如 'J1' 表示正月節(立春)，'Z4' 表示四月中(小滿) 等，jdn1, jdn2, ... 是曆書節氣的正午儒略日數。

`'datongST'` (只適用於1667至1669的中曆年): 用大統曆算出的節氣 \[(lab1, jdn1), (lab2, jdn2), ...\]。康熙六年(1667)至八年(1669)清朝因曆獄而復用明朝《大統曆》，但後來清朝欽天監編的《御定萬年書》試圖抹去這段歷史，用時憲曆追推這幾年的節氣，但臺灣國立故宮博物院的清代檔案檢索系統藏有這幾年的《大清七政經緯躔度時憲曆》，顯示這幾年的節氣日期確是符合大統曆的推算，而不符合時憲曆的推算，所以此處在這幾年列出大統曆的節氣。

`'sterm'`: python list \[\[lab1, info1\], \[lab2, info2\], ...\] 顯示用 DE441曆表算出的節氣，lab1, lab2, ... 為節氣標記，info1, info2, ... 則是 python dictionary，顯示節氣的日期及 UT+8 時刻。

`'mphase'`: python list \[\[lab1, info1\], \[lab2, info2\], ...\] 顯示用 DE441 曆表算出的中曆年內所有的月相資料。lab1, lab2, ... 是月相的標記： 'Q0' 是朔，'Q1' 是上弦，'Q2' 是望，'Q3' 是下弦。 info1, info2, ... 是 python dictionary，顯示月相的日期及 UT+8 時刻。

此函數輸出的 python list 不方便瀏覽， 函數 `.chinese_year_info_html()` 輸出 HTML 文字，可用 `IPython.display.HTML()` 函數將資料以表格形式顯示。

In [12]:
# 700年的中曆年資料
HTML(cal.chinese_year_html(700))

In [13]:
# 1669年的中曆年資料
HTML(cal.chinese_year_html(1669))

In [14]:
# 2025年的中曆年資料
HTML(cal.chinese_year_html(2025))

In [15]:
# 中曆156年九月的所有日期
cal.chinese_to_western_year(156, 9)

[{'Chinese ymd': [156, 9, 1],
  'Western ymd': [156, 10, 2],
  'Western calendar': '儒略曆',
  'JDN': 1778312,
  'cyear': 156,
  'cdate': '九月初一',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['乙酉', 22],
  'Week': ['星期五', 5],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 2],
  'Western ymd': [156, 10, 3],
  'Western calendar': '儒略曆',
  'JDN': 1778313,
  'cyear': 156,
  'cdate': '九月初二',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['丙戌', 23],
  'Week': ['星期六', 6],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 3],
  'Western ymd': [156, 10, 4],
  'Western calendar': '儒略曆',
  'JDN': 1778314,
  'cyear': 156,
  'cdate': '九月初三',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁亥', 24],
  'Week': ['星期日', 0],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 4],
  'Western ymd': [156, 10, 5],
  'Western calendar': '儒略曆',
  'JDN': 1778315,
  'cyear': 156,
  'cdate': '九月初四',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊子', 25],
  'Week': ['星期一', 1],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 5],
  'Western ymd': [156, 10, 6],
  'Western calendar': '儒略曆',
  'JDN': 1778316,
  'cyear': 156,
  'cdate': '九月初五',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['己丑', 26],
  'Week': ['星期二', 2],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 6],
  'Western ymd': [156, 10, 7],
  'Western calendar': '儒略曆',
  'JDN': 1778317,
  'cyear': 156,
  'cdate': '九月初六',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚寅', 27],
  'Week': ['星期三', 3],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 7],
  'Western ymd': [156, 10, 8],
  'Western calendar': '儒略曆',
  'JDN': 1778318,
  'cyear': 156,
  'cdate': '九月初七',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛卯', 28],
  'Week': ['星期四', 4],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 8],
  'Western ymd': [156, 10, 9],
  'Western calendar': '儒略曆',
  'JDN': 1778319,
  'cyear': 156,
  'cdate': '九月初八',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['壬辰', 29],
  'Week': ['星期五', 5],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 9],
  'Western ymd': [156, 10, 10],
  'Western calendar': '儒略曆',
  'JDN': 1778320,
  'cyear': 156,
  'cdate': '九月初九',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['癸巳', 30],
  'Week': ['星期六', 6],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 10],
  'Western ymd': [156, 10, 11],
  'Western calendar': '儒略曆',
  'JDN': 1778321,
  'cyear': 156,
  'cdate': '九月初十',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['甲午', 31],
  'Week': ['星期日', 0],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 11],
  'Western ymd': [156, 10, 12],
  'Western calendar': '儒略曆',
  'JDN': 1778322,
  'cyear': 156,
  'cdate': '九月十一',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['乙未', 32],
  'Week': ['星期一', 1],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 12],
  'Western ymd': [156, 10, 13],
  'Western calendar': '儒略曆',
  'JDN': 1778323,
  'cyear': 156,
  'cdate': '九月十二',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['丙申', 33],
  'Week': ['星期二', 2],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 13],
  'Western ymd': [156, 10, 14],
  'Western calendar': '儒略曆',
  'JDN': 1778324,
  'cyear': 156,
  'cdate': '九月十三',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁酉', 34],
  'Week': ['星期三', 3],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 14],
  'Western ymd': [156, 10, 15],
  'Western calendar': '儒略曆',
  'JDN': 1778325,
  'cyear': 156,
  'cdate': '九月十四',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊戌', 35],
  'Week': ['星期四', 4],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 15],
  'Western ymd': [156, 10, 16],
  'Western calendar': '儒略曆',
  'JDN': 1778326,
  'cyear': 156,
  'cdate': '九月十五',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['己亥', 36],
  'Week': ['星期五', 5],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 16],
  'Western ymd': [156, 10, 17],
  'Western calendar': '儒略曆',
  'JDN': 1778327,
  'cyear': 156,
  'cdate': '九月十六',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚子', 37],
  'Week': ['星期六', 6],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 17],
  'Western ymd': [156, 10, 18],
  'Western calendar': '儒略曆',
  'JDN': 1778328,
  'cyear': 156,
  'cdate': '九月十七',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛丑', 38],
  'Week': ['星期日', 0],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 18],
  'Western ymd': [156, 10, 19],
  'Western calendar': '儒略曆',
  'JDN': 1778329,
  'cyear': 156,
  'cdate': '九月十八',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['壬寅', 39],
  'Week': ['星期一', 1],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 19],
  'Western ymd': [156, 10, 20],
  'Western calendar': '儒略曆',
  'JDN': 1778330,
  'cyear': 156,
  'cdate': '九月十九',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['癸卯', 40],
  'Week': ['星期二', 2],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 20],
  'Western ymd': [156, 10, 21],
  'Western calendar': '儒略曆',
  'JDN': 1778331,
  'cyear': 156,
  'cdate': '九月二十',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['甲辰', 41],
  'Week': ['星期三', 3],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 21],
  'Western ymd': [156, 10, 22],
  'Western calendar': '儒略曆',
  'JDN': 1778332,
  'cyear': 156,
  'cdate': '九月廿一',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['乙巳', 42],
  'Week': ['星期四', 4],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 22],
  'Western ymd': [156, 10, 23],
  'Western calendar': '儒略曆',
  'JDN': 1778333,
  'cyear': 156,
  'cdate': '九月廿二',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['丙午', 43],
  'Week': ['星期五', 5],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 23],
  'Western ymd': [156, 10, 24],
  'Western calendar': '儒略曆',
  'JDN': 1778334,
  'cyear': 156,
  'cdate': '九月廿三',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁未', 44],
  'Week': ['星期六', 6],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 24],
  'Western ymd': [156, 10, 25],
  'Western calendar': '儒略曆',
  'JDN': 1778335,
  'cyear': 156,
  'cdate': '九月廿四',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊申', 45],
  'Week': ['星期日', 0],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 25],
  'Western ymd': [156, 10, 26],
  'Western calendar': '儒略曆',
  'JDN': 1778336,
  'cyear': 156,
  'cdate': '九月廿五',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['己酉', 46],
  'Week': ['星期一', 1],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 26],
  'Western ymd': [156, 10, 27],
  'Western calendar': '儒略曆',
  'JDN': 1778337,
  'cyear': 156,
  'cdate': '九月廿六',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚戌', 47],
  'Week': ['星期二', 2],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 27],
  'Western ymd': [156, 10, 28],
  'Western calendar': '儒略曆',
  'JDN': 1778338,
  'cyear': 156,
  'cdate': '九月廿七',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛亥', 48],
  'Week': ['星期三', 3],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 28],
  'Western ymd': [156, 10, 29],
  'Western calendar': '儒略曆',
  'JDN': 1778339,
  'cyear': 156,
  'cdate': '九月廿八',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['壬子', 49],
  'Week': ['星期四', 4],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 29],
  'Western ymd': [156, 10, 30],
  'Western calendar': '儒略曆',
  'JDN': 1778340,
  'cyear': 156,
  'cdate': '九月廿九',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['癸丑', 50],
  'Week': ['星期五', 5],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'},
 {'Chinese ymd': [156, 9, 30],
  'Western ymd': [156, 10, 31],
  'Western calendar': '儒略曆',
  'JDN': 1778341,
  'cyear': 156,
  'cdate': '九月三十',
  'sexagenary year': ['丙申', '猴', 33],
  'jian': ['建戊戌', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['甲寅', 51],
  'Week': ['星期六', 6],
  'period': '東漢 (25 - 219)',
  'reign/era': '漢桓帝永壽二年',
  'Chinese calendar': '四分曆'}]

In [16]:
# 中曆156年九月的月曆表 
HTML(cal.chinese_to_western_year_html(156, 9))

In [17]:
# 中曆1980年的年曆表 
HTML(cal.chinese_to_western_year_html(1980))

注意此處列出的月相和節氣日期是中曆日期，而不是公曆日期。

## 月相和二十四節氣

`ChineseCalendar_py.sunMoon.sunMoon` class 提供用現代曆表算出的月相和二十四節氣的 UT+8 日期和時刻，以下指令建立這 class 的實體。

In [18]:
sm = ccal.sunMoon.sunMoon('ChiT')

第一個輸入參數 'ChiT' 表示輸出的語言是傳統中文，其他可選的是 'Eng'(英文)和 'ChiS' (簡體中文)。

第二個可輸入的參數是 'DE431' 或 'DE441'， 表示計算月相和節氣用的曆表，默認值是 'DE441'。如前述，紫金山天文臺自2014年起用 DE421 曆表編算天文年曆，直至2025年仍是如此，DE421、DE431及DE441曆表算出的月相和節氣在距今幾十年間差異甚微(DE421 曆表的年限是1899年至2053年)，在遠古和遙遠將來 DE431 和 DE441 算出的時刻雖然差異較大，但仍未超出 TDB 轉換 UT1 的估計誤差。1929年至2013年中曆的月相和節氣用舊曆表計算，與 DE 曆表的差異可達半分鐘。

In [19]:
# 2025年全年的月相和節氣
st, mp = sm.st_mp(2025)
print('節氣:\n', st)
print('月相:\n', mp)

節氣:
 [['J12', {'event': '小寒', 'year': 2025, 'month': 1, 'date': 5, 'hour': 10, 'minute': 33, 'dateString': '1月5日', 'timeString': '10:33', 'jd0_ut': 2460675.5, 'jd1_ut': 5.106092071880626}], ['Z12', {'event': '大寒', 'year': 2025, 'month': 1, 'date': 20, 'hour': 4, 'minute': 0, 'dateString': '1月20日', 'timeString': '04:00', 'jd0_ut': 2460675.5, 'jd1_ut': 19.83341960335423}], ['J1', {'event': '立春', 'year': 2025, 'month': 2, 'date': 3, 'hour': 22, 'minute': 10, 'dateString': '2月3日', 'timeString': '22:10', 'jd0_ut': 2460675.5, 'jd1_ut': 34.59060328647452}], ['Z1', {'event': '雨水', 'year': 2025, 'month': 2, 'date': 18, 'hour': 18, 'minute': 7, 'dateString': '2月18日', 'timeString': '18:07', 'jd0_ut': 2460675.5, 'jd1_ut': 49.42122993693512}], ['J2', {'event': '驚蟄', 'year': 2025, 'month': 3, 'date': 5, 'hour': 16, 'minute': 7, 'dateString': '3月5日', 'timeString': '16:07', 'jd0_ut': 2460675.5, 'jd1_ut': 64.33838170980152}], ['Z2', {'event': '春分', 'year': 2025, 'month': 3, 'date': 20, 'hour': 17, 'minute': 1, 'dateString': '3月20日', 'timeString': '17:01', 'jd0_ut': 2460675.5, 'jd1_ut': 79.37602936184282}], ['J3', {'event': '清明', 'year': 2025, 'month': 4, 'date': 4, 'hour': 20, 'minute': 49, 'dateString': '4月4日', 'timeString': '20:49', 'jd0_ut': 2460675.5, 'jd1_ut': 94.53372417348322}], ['Z3', {'event': '穀雨', 'year': 2025, 'month': 4, 'date': 20, 'hour': 3, 'minute': 56, 'dateString': '4月20日', 'timeString': '03:56', 'jd0_ut': 2460675.5, 'jd1_ut': 109.83056878571793}], ['J4', {'event': '立夏', 'year': 2025, 'month': 5, 'date': 5, 'hour': 13, 'minute': 57, 'dateString': '5月5日', 'timeString': '13:57', 'jd0_ut': 2460675.5, 'jd1_ut': 125.24804905646992}], ['Z4', {'event': '小滿', 'year': 2025, 'month': 5, 'date': 21, 'hour': 2, 'minute': 55, 'dateString': '5月21日', 'timeString': '02:55', 'jd0_ut': 2460675.5, 'jd1_ut': 140.7879417198639}], ['J5', {'event': '芒種', 'year': 2025, 'month': 6, 'date': 5, 'hour': 17, 'minute': 57, 'dateString': '6月5日', 'timeString': '17:57', 'jd0_ut': 2460675.5, 'jd1_ut': 156.4142496984179}], ['Z5', {'event': '夏至', 'year': 2025, 'month': 6, 'date': 21, 'hour': 10, 'minute': 42, 'dateString': '6月21日', 'timeString': '10:42', 'jd0_ut': 2460675.5, 'jd1_ut': 172.1126815013149}], ['J6', {'event': '小暑', 'year': 2025, 'month': 7, 'date': 7, 'hour': 4, 'minute': 5, 'dateString': '7月7日', 'timeString': '04:05', 'jd0_ut': 2460675.5, 'jd1_ut': 187.83679511281792}], ['Z6', {'event': '大暑', 'year': 2025, 'month': 7, 'date': 22, 'hour': 21, 'minute': 29, 'dateString': '7月22日', 'timeString': '21:29', 'jd0_ut': 2460675.5, 'jd1_ut': 203.56211940597592}], ['J7', {'event': '立秋', 'year': 2025, 'month': 8, 'date': 7, 'hour': 13, 'minute': 52, 'dateString': '8月7日', 'timeString': '13:52', 'jd0_ut': 2460675.5, 'jd1_ut': 219.2441517825249}], ['Z7', {'event': '處暑', 'year': 2025, 'month': 8, 'date': 23, 'hour': 4, 'minute': 34, 'dateString': '8月23日', 'timeString': '04:34', 'jd0_ut': 2460675.5, 'jd1_ut': 234.85684575782793}], ['J8', {'event': '白露', 'year': 2025, 'month': 9, 'date': 7, 'hour': 16, 'minute': 52, 'dateString': '9月7日', 'timeString': '16:52', 'jd0_ut': 2460675.5, 'jd1_ut': 250.3694060566639}], ['Z8', {'event': '秋分', 'year': 2025, 'month': 9, 'date': 23, 'hour': 2, 'minute': 19, 'dateString': '9月23日', 'timeString': '02:19', 'jd0_ut': 2460675.5, 'jd1_ut': 265.763431731398}], ['J9', {'event': '寒露', 'year': 2025, 'month': 10, 'date': 8, 'hour': 8, 'minute': 41, 'dateString': '10月8日', 'timeString': '08:41', 'jd0_ut': 2460675.5, 'jd1_ut': 281.02861235101096}], ['Z9', {'event': '霜降', 'year': 2025, 'month': 10, 'date': 23, 'hour': 11, 'minute': 51, 'dateString': '10月23日', 'timeString': '11:51', 'jd0_ut': 2460675.5, 'jd1_ut': 296.16036407889897}], ['J10', {'event': '立冬', 'year': 2025, 'month': 11, 'date': 7, 'hour': 12, 'minute': 4, 'dateString': '11月7日', 'timeString': '12:04', 'jd0_ut': 2460675.5, 'jd1_ut': 311.16947619983597}], ['Z10', {'event': '小雪', 'year': 2025, 'month': 11, 'date': 22, 'hour': 9, 'minute': 36, 'dateString': '11月22日', 'timeString': '09:36', 'jd0_ut': 2460675.5, 'jd1_ut': 326.066372247889}], ['J11', {'event': '大雪', 'year': 2025, 'month': 12, 'date': 7, 'hour': 5, 'minute': 5, 'dateString': '12月7日', 'timeString': '05:05', 'jd0_ut': 2460675.5, 'jd1_ut': 340.87818211916}], ['Z11', {'event': '冬至', 'year': 2025, 'month': 12, 'date': 21, 'hour': 23, 'minute': 3, 'dateString': '12月21日', 'timeString': '23:03', 'jd0_ut': 2460675.5, 'jd1_ut': 355.627142970562}]]
月相:
 [['Q1', {'event': '上弦', 'year': 2025, 'month': 1, 'date': 7, 'hour': 7, 'minute': 56, 'dateString': '1月7日', 'timeString': '07:56', 'jd0_ut': 2460675.5, 'jd1_ut': 6.997426499745337}], ['Q2', {'event': '望', 'year': 2025, 'month': 1, 'date': 14, 'hour': 6, 'minute': 27, 'dateString': '1月14日', 'timeString': '06:27', 'jd0_ut': 2460675.5, 'jd1_ut': 13.935353490223724}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 1, 'date': 22, 'hour': 4, 'minute': 31, 'dateString': '1月22日', 'timeString': '04:31', 'jd0_ut': 2460675.5, 'jd1_ut': 21.85471605012533}], ['Q0', {'event': '朔', 'year': 2025, 'month': 1, 'date': 29, 'hour': 20, 'minute': 36, 'dateString': '1月29日', 'timeString': '20:36', 'jd0_ut': 2460675.5, 'jd1_ut': 29.52498730700813}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 2, 'date': 5, 'hour': 16, 'minute': 2, 'dateString': '2月5日', 'timeString': '16:02', 'jd0_ut': 2460675.5, 'jd1_ut': 36.33482814883092}], ['Q2', {'event': '望', 'year': 2025, 'month': 2, 'date': 12, 'hour': 21, 'minute': 53, 'dateString': '2月12日', 'timeString': '21:53', 'jd0_ut': 2460675.5, 'jd1_ut': 43.57874926958232}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 2, 'date': 21, 'hour': 1, 'minute': 33, 'dateString': '2月21日', 'timeString': '01:33', 'jd0_ut': 2460675.5, 'jd1_ut': 51.73093342133332}], ['Q0', {'event': '朔', 'year': 2025, 'month': 2, 'date': 28, 'hour': 8, 'minute': 45, 'dateString': '2月28日', 'timeString': '08:45', 'jd0_ut': 2460675.5, 'jd1_ut': 59.03112868022792}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 3, 'date': 7, 'hour': 0, 'minute': 32, 'dateString': '3月7日', 'timeString': '00:32', 'jd0_ut': 2460675.5, 'jd1_ut': 65.68863105878413}], ['Q2', {'event': '望', 'year': 2025, 'month': 3, 'date': 14, 'hour': 14, 'minute': 55, 'dateString': '3月14日', 'timeString': '14:55', 'jd0_ut': 2460675.5, 'jd1_ut': 73.28795360964983, 'eclipse': '月全食', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=2001&ind=56&DE=441&shrule=revised_Danjon&ref=python'}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 3, 'date': 22, 'hour': 19, 'minute': 29, 'dateString': '3月22日', 'timeString': '19:29', 'jd0_ut': 2460675.5, 'jd1_ut': 81.47877817938983}], ['Q0', {'event': '朔', 'year': 2025, 'month': 3, 'date': 29, 'hour': 18, 'minute': 58, 'dateString': '3月29日', 'timeString': '18:58', 'jd0_ut': 2460675.5, 'jd1_ut': 88.45682775942673, 'eclipse': '日偏食', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=2001&ind=52&DE=441&ref=python'}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 4, 'date': 5, 'hour': 10, 'minute': 15, 'dateString': '4月5日', 'timeString': '10:15', 'jd0_ut': 2460675.5, 'jd1_ut': 95.09353156687573}], ['Q2', {'event': '望', 'year': 2025, 'month': 4, 'date': 13, 'hour': 8, 'minute': 22, 'dateString': '4月13日', 'timeString': '08:22', 'jd0_ut': 2460675.5, 'jd1_ut': 103.01545855832393}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 4, 'date': 21, 'hour': 9, 'minute': 36, 'dateString': '4月21日', 'timeString': '09:36', 'jd0_ut': 2460675.5, 'jd1_ut': 111.06636856068192}], ['Q0', {'event': '朔', 'year': 2025, 'month': 4, 'date': 28, 'hour': 3, 'minute': 31, 'dateString': '4月28日', 'timeString': '03:31', 'jd0_ut': 2460675.5, 'jd1_ut': 117.81330174351592}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 5, 'date': 4, 'hour': 21, 'minute': 52, 'dateString': '5月4日', 'timeString': '21:52', 'jd0_ut': 2460675.5, 'jd1_ut': 124.57761137351893}], ['Q2', {'event': '望', 'year': 2025, 'month': 5, 'date': 13, 'hour': 0, 'minute': 56, 'dateString': '5月13日', 'timeString': '00:56', 'jd0_ut': 2460675.5, 'jd1_ut': 132.7055130367809}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 5, 'date': 20, 'hour': 19, 'minute': 59, 'dateString': '5月20日', 'timeString': '19:59', 'jd0_ut': 2460675.5, 'jd1_ut': 140.49914448437892}], ['Q0', {'event': '朔', 'year': 2025, 'month': 5, 'date': 27, 'hour': 11, 'minute': 2, 'dateString': '5月27日', 'timeString': '11:02', 'jd0_ut': 2460675.5, 'jd1_ut': 147.12663254637093}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 6, 'date': 3, 'hour': 11, 'minute': 41, 'dateString': '6月3日', 'timeString': '11:41', 'jd0_ut': 2460675.5, 'jd1_ut': 154.1534506400329}], ['Q2', {'event': '望', 'year': 2025, 'month': 6, 'date': 11, 'hour': 15, 'minute': 44, 'dateString': '6月11日', 'timeString': '15:44', 'jd0_ut': 2460675.5, 'jd1_ut': 162.32211035673492}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 6, 'date': 19, 'hour': 3, 'minute': 19, 'dateString': '6月19日', 'timeString': '03:19', 'jd0_ut': 2460675.5, 'jd1_ut': 169.80493859105192}], ['Q0', {'event': '朔', 'year': 2025, 'month': 6, 'date': 25, 'hour': 18, 'minute': 32, 'dateString': '6月25日', 'timeString': '18:32', 'jd0_ut': 2460675.5, 'jd1_ut': 176.43862369488193}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 7, 'date': 3, 'hour': 3, 'minute': 30, 'dateString': '7月3日', 'timeString': '03:30', 'jd0_ut': 2460675.5, 'jd1_ut': 183.81263244977492}], ['Q2', {'event': '望', 'year': 2025, 'month': 7, 'date': 11, 'hour': 4, 'minute': 37, 'dateString': '7月11日', 'timeString': '04:37', 'jd0_ut': 2460675.5, 'jd1_ut': 191.8588846595249}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 7, 'date': 18, 'hour': 8, 'minute': 38, 'dateString': '7月18日', 'timeString': '08:38', 'jd0_ut': 2460675.5, 'jd1_ut': 199.02615836602192}], ['Q0', {'event': '朔', 'year': 2025, 'month': 7, 'date': 25, 'hour': 3, 'minute': 11, 'dateString': '7月25日', 'timeString': '03:11', 'jd0_ut': 2460675.5, 'jd1_ut': 205.79944498391592}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 8, 'date': 1, 'hour': 20, 'minute': 41, 'dateString': '8月1日', 'timeString': '20:41', 'jd0_ut': 2460675.5, 'jd1_ut': 213.5286960989409}], ['Q2', {'event': '望', 'year': 2025, 'month': 8, 'date': 9, 'hour': 15, 'minute': 55, 'dateString': '8月9日', 'timeString': '15:55', 'jd0_ut': 2460675.5, 'jd1_ut': 221.3299118558479}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 8, 'date': 16, 'hour': 13, 'minute': 12, 'dateString': '8月16日', 'timeString': '13:12', 'jd0_ut': 2460675.5, 'jd1_ut': 228.2168311195549}], ['Q0', {'event': '朔', 'year': 2025, 'month': 8, 'date': 23, 'hour': 14, 'minute': 7, 'dateString': '8月23日', 'timeString': '14:07', 'jd0_ut': 2460675.5, 'jd1_ut': 235.2545487174299}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 8, 'date': 31, 'hour': 14, 'minute': 25, 'dateString': '8月31日', 'timeString': '14:25', 'jd0_ut': 2460675.5, 'jd1_ut': 243.26749951340392}], ['Q2', {'event': '望', 'year': 2025, 'month': 9, 'date': 8, 'hour': 2, 'minute': 9, 'dateString': '9月8日', 'timeString': '02:09', 'jd0_ut': 2460675.5, 'jd1_ut': 250.75617874416892, 'eclipse': '月全食', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=2001&ind=57&DE=441&shrule=revised_Danjon&ref=python'}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 9, 'date': 14, 'hour': 18, 'minute': 33, 'dateString': '9月14日', 'timeString': '18:33', 'jd0_ut': 2460675.5, 'jd1_ut': 257.439552214294}], ['Q0', {'event': '朔', 'year': 2025, 'month': 9, 'date': 22, 'hour': 3, 'minute': 54, 'dateString': '9月22日', 'timeString': '03:54', 'jd0_ut': 2460675.5, 'jd1_ut': 264.82925758711895, 'eclipse': '日偏食', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=2001&ind=53&DE=441&ref=python'}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 9, 'date': 30, 'hour': 7, 'minute': 54, 'dateString': '9月30日', 'timeString': '07:54', 'jd0_ut': 2460675.5, 'jd1_ut': 272.99571627087795}], ['Q2', {'event': '望', 'year': 2025, 'month': 10, 'date': 7, 'hour': 11, 'minute': 48, 'dateString': '10月7日', 'timeString': '11:48', 'jd0_ut': 2460675.5, 'jd1_ut': 280.15806562510295}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 10, 'date': 14, 'hour': 2, 'minute': 13, 'dateString': '10月14日', 'timeString': '02:13', 'jd0_ut': 2460675.5, 'jd1_ut': 286.758814270732}], ['Q0', {'event': '朔', 'year': 2025, 'month': 10, 'date': 21, 'hour': 20, 'minute': 25, 'dateString': '10月21日', 'timeString': '20:25', 'jd0_ut': 2460675.5, 'jd1_ut': 294.51748183067696}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 10, 'date': 30, 'hour': 0, 'minute': 21, 'dateString': '10月30日', 'timeString': '00:21', 'jd0_ut': 2460675.5, 'jd1_ut': 302.681124447078}], ['Q2', {'event': '望', 'year': 2025, 'month': 11, 'date': 5, 'hour': 21, 'minute': 19, 'dateString': '11月5日', 'timeString': '21:19', 'jd0_ut': 2460675.5, 'jd1_ut': 309.55507464925597}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 11, 'date': 12, 'hour': 13, 'minute': 28, 'dateString': '11月12日', 'timeString': '13:28', 'jd0_ut': 2460675.5, 'jd1_ut': 316.227878018918}], ['Q0', {'event': '朔', 'year': 2025, 'month': 11, 'date': 20, 'hour': 14, 'minute': 47, 'dateString': '11月20日', 'timeString': '14:47', 'jd0_ut': 2460675.5, 'jd1_ut': 324.28282513227197}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 11, 'date': 28, 'hour': 14, 'minute': 59, 'dateString': '11月28日', 'timeString': '14:59', 'jd0_ut': 2460675.5, 'jd1_ut': 332.29083264566697}], ['Q2', {'event': '望', 'year': 2025, 'month': 12, 'date': 5, 'hour': 7, 'minute': 14, 'dateString': '12月5日', 'timeString': '07:14', 'jd0_ut': 2460675.5, 'jd1_ut': 338.96810757277797}], ['Q3', {'event': '下弦', 'year': 2025, 'month': 12, 'date': 12, 'hour': 4, 'minute': 52, 'dateString': '12月12日', 'timeString': '04:52', 'jd0_ut': 2460675.5, 'jd1_ut': 345.86922848582196}], ['Q0', {'event': '朔', 'year': 2025, 'month': 12, 'date': 20, 'hour': 9, 'minute': 43, 'dateString': '12月20日', 'timeString': '09:43', 'jd0_ut': 2460675.5, 'jd1_ut': 354.07176785431994}], ['Q1', {'event': '上弦', 'year': 2025, 'month': 12, 'date': 28, 'hour': 3, 'minute': 10, 'dateString': '12月28日', 'timeString': '03:10', 'jd0_ut': 2460675.5, 'jd1_ut': 361.79851133850997}]]

In [20]:
# 2025年全年的月相和節氣，轉為 pandas dataframe 來顯示。
st, mp = sm.st_mp_df(2025)
display(st)
display(mp)

    節氣      時刻 (UT+8)
0   小寒    1月5日, 10:33
1   大寒   1月20日, 04:00
2   立春    2月3日, 22:10
3   雨水   2月18日, 18:07
4   驚蟄    3月5日, 16:07
5   春分   3月20日, 17:01
6   清明    4月4日, 20:49
7   穀雨   4月20日, 03:56
8   立夏    5月5日, 13:57
9   小滿   5月21日, 02:55
10  芒種    6月5日, 17:57
11  夏至   6月21日, 10:42
12  小暑    7月7日, 04:05
13  大暑   7月22日, 21:29
14  立秋    8月7日, 13:52
15  處暑   8月23日, 04:34
16  白露    9月7日, 16:52
17  秋分   9月23日, 02:19
18  寒露   10月8日, 08:41
19  霜降  10月23日, 11:51
20  立冬   11月7日, 12:04
21  小雪  11月22日, 09:36
22  大雪   12月7日, 05:05
23  冬至  12月21日, 23:03

,朔,上弦,望,下弦
0,,"1月7日, 07:56","1月14日, 06:27","1月22日, 04:31"
1,"1月29日, 20:36","2月5日, 16:02","2月12日, 21:53","2月21日, 01:33"
2,"2月28日, 08:45","3月7日, 00:32","3月14日, 14:55<br /><a href=""http://ytliu.epizy....","3月22日, 19:29"
3,"3月29日, 18:58<br /><a href=""http://ytliu.epizy....","4月5日, 10:15","4月13日, 08:22","4月21日, 09:36"
4,"4月28日, 03:31","5月4日, 21:52","5月13日, 00:56","5月20日, 19:59"
5,"5月27日, 11:02","6月3日, 11:41","6月11日, 15:44","6月19日, 03:19"
6,"6月25日, 18:32","7月3日, 03:30","7月11日, 04:37","7月18日, 08:38"
7,"7月25日, 03:11","8月1日, 20:41","8月9日, 15:55","8月16日, 13:12"
8,"8月23日, 14:07","8月31日, 14:25","9月8日, 02:09<br /><a href=""http://ytliu.epizy.c...","9月14日, 18:33"
9,"9月22日, 03:54<br /><a href=""http://ytliu.epizy....","9月30日, 07:54","10月7日, 11:48","10月14日, 02:13"
10,"10月21日, 20:25","10月30日, 00:21","11月5日, 21:19","11月12日, 13:28"
11,"11月20日, 14:47","11月28日, 14:59","12月5日, 07:14","12月12日, 04:52"
12,"12月20日, 09:43","12月28日, 03:10",,

月相中朔和望還提供日月食的資料，有連結到我製的日月食網頁，要恰當顯示連結，可用 pandas dataframe 提供的 `.to_html` 函數轉為 HTML 文字，然後用 `IPython.display.HTML()` 顯示，得出的輸出類此[氣朔網頁](https://ytliu0.github.io/ChineseCalendar/sunMoon_chinese.html)的表格。

In [21]:
HTML(mp.to_html(
    render_links=True,
    escape=False,
))

## 曆書節氣

古代的節氣用當時的曆法計算，算出的節氣與用現代曆表的節氣常有大差異，函數`.calendrical_solar_terms(y)`提供公曆 y 年的曆書節氣，即按當時曆法計算的節氣。

In [22]:
# 1532年的曆書節氣
cal.calendrical_solar_terms(1532)

[{'節氣': '大寒', '日期': '1月12日'},
 {'節氣': '立春', '日期': '1月27日'},
 {'節氣': '雨水', '日期': '2月11日'},
 {'節氣': '驚蟄', '日期': '2月27日'},
 {'節氣': '春分', '日期': '3月13日'},
 {'節氣': '清明', '日期': '3月28日'},
 {'節氣': '穀雨', '日期': '4月12日'},
 {'節氣': '立夏', '日期': '4月27日'},
 {'節氣': '小滿', '日期': '5月13日'},
 {'節氣': '芒種', '日期': '5月28日'},
 {'節氣': '夏至', '日期': '6月12日'},
 {'節氣': '小暑', '日期': '6月27日'},
 {'節氣': '大暑', '日期': '7月12日'},
 {'節氣': '立秋', '日期': '7月28日'},
 {'節氣': '處暑', '日期': '8月12日'},
 {'節氣': '白露', '日期': '8月27日'},
 {'節氣': '秋分', '日期': '9月11日'},
 {'節氣': '寒露', '日期': '9月27日'},
 {'節氣': '霜降', '日期': '10月12日'},
 {'節氣': '立冬', '日期': '10月27日'},
 {'節氣': '小雪', '日期': '11月11日'},
 {'節氣': '大雪', '日期': '11月26日'},
 {'節氣': '冬至', '日期': '12月12日'},
 {'節氣': '小寒', '日期': '12月27日'}]

In [23]:
# 1532年的曆書節氣轉為 pandas dataframe 顯示 
display(pd.DataFrame(cal.calendrical_solar_terms(1532)))

    節氣      日期
0   大寒   1月12日
1   立春   1月27日
2   雨水   2月11日
3   驚蟄   2月27日
4   春分   3月13日
5   清明   3月28日
6   穀雨   4月12日
7   立夏   4月27日
8   小滿   5月13日
9   芒種   5月28日
10  夏至   6月12日
11  小暑   6月27日
12  大暑   7月12日
13  立秋   7月28日
14  處暑   8月12日
15  白露   8月27日
16  秋分   9月11日
17  寒露   9月27日
18  霜降  10月12日
19  立冬  10月27日
20  小雪  11月11日
21  大雪  11月26日
22  冬至  12月12日
23  小寒  12月27日

In [24]:
# -106年(公元前107年)的曆書節氣
display(pd.DataFrame(cal.calendrical_solar_terms(-106)))

    節氣      日期
0   小寒    1月9日
1   大寒   1月24日
2   立春    2月8日
3   雨水   2月24日
4   驚蟄   3月11日
5   春分   3月26日
6   清明   4月10日
7   穀雨   4月26日
8   立夏   5月11日
9   小滿   5月26日
10  芒種   6月10日
11  夏至   6月25日
12  小暑   7月11日
13  大暑   7月26日
14  立秋   8月10日
15  處暑   8月25日
16  白露    9月9日
17  秋分   9月25日
18  寒露  10月10日
19  霜降  10月25日
20  立冬   11月9日
21  小雪  11月25日
22  大雪  12月10日
23  冬至  12月25日

此函數輸出公曆 y 年的曆書節氣，如要中曆 y 年的曆書節氣，可用上述
`.chinese_year_info(y)` 或 `.chinese_year_html(y)` 函數。

## 進階指引

以上的指南展示了此軟體套件的基本函數用法，如要深入了解這些函數的用法，可參閱`tutorial/traditional_chinese/tutorial.ipyb` 的進階指引，而 `tutorial/traditional_chinese/calendar_exercises.ipyb` 則展示較為複雜的日曆計算。