# Quick Start Guide

This guide shows examples of basic usage of this package. It covers functions that generate calendar information found on [this Chinese calendar website](https://ytliu0.github.io/ChineseCalendar).

## Installation

Use the following `pip` command to install and update this package.

In [1]:
#pip install --upgrade ChineseCalendar_py

## Load package

In [2]:
import ChineseCalendar_py.calendar_conversion as ccal
from IPython.display import HTML
import pandas as pd

Use the following command to create an instance of the Chinese calendar object. The input parameter `'Eng'` means the calendar information will be displayed in English. Two other possible parameters are `'ChiT'` for traditional Chinese and `'ChiS'` for simplified Chinese.

In [3]:
cal = ccal.calendar_conversion('Eng')

## Western calendar to Chinese calendar conversion

Three methods are provides to do the conversion:

- `.western_to_chinese_date(y, m, d, ...)`: Western date (year = y, month = m, date = d) to Chinese date.

- `.western_to_chinese_year(y, m=None, ...)`: Western year y, month m (if m is not None) to Chinese dates

- `.western_to_chinese_year_html(y, m=None, ...)`: Same as `western_to_chinese_year()` but return an HTML text.

Note that `...` denotes other optional parameters not covered in this guide. See the tutorial notebook for detail.

The following command converts January 26, 2025 to Chinese date.

In [4]:
cal.western_to_chinese_date(2025, 1, 26)

{'Western ymd': [2025, 1, 26],
 'Western calendar': 'Gregorian',
 'JDN': 2460702,
 'Chinese ymd': [2024, 12, 27],
 'cyear': 2024,
 'cdate': '12-27',
 'sexagenary year': ['Jia Chen', 'Dragon', 41],
 'jian': ['Ding Chou', 14],
 'Nday_cmonth': 29,
 'sexagenary date': ['Yi Wei', 32],
 'Week': ['Sun', 0],
 'period': 'Modern (1912 - )',
 'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'}

This shows that January 26, 2025 corresponds to the 27th day in the 12th month in the Chinese year Jia Chen (the year of Dragon). 

This method `.western_to_chinese_date(y, m, d)` returns a python dictionary with the following keys:

`'Western ymd'`: a list containing Western year, month, day

`'Western calendar'`: version of the Western calendar (Gregorian, Julian or propleptic Julian).

`'JDN'`: Julian date at noon. 

`'Chinese ymd'`: a list containing Chinese year, month (negative means leap month) and date. 

`'cyear'`: Western year with the most overlap of days in the Chinese year.

`'cdate'`: Chinese month number-day number. 

`'sexagenary year'`: a list with \[sexagenary year cycle, sexagenary number\]. Sexagenary number 1 means Jia zi, 2 means Yi chow, and so on (see Table 2 on [this page](https://ytliu0.github.io/ChineseCalendar/sexagenary.html) for the complete list). 

`'jian'`: sexagenary month cycle. See [this page](https://ytliu0.github.io/ChineseCalendar/sexagenary.html) for an explanation of the sexagenary month cycle and *jian*.

`'Nday_cmonth'`: number of days in the Chinese month, usually 29 or 30.

`'sexagenary date'`: sexagenary date cycle. See [this page](https://ytliu0.github.io/ChineseCalendar/sexagenary.html) for an explanation of the sexagenary date cycle.

`'Week'`: \[day of week, week number\]. Week number convention: 0 for Sunday, 1 for Monday, 2 for Tuesday, 3 for Wednesday, 4 for Thursday, 5 for Friday and 6 for Saturday.

`'period'`: Period in the Chinese history.

`'Chinese calendar'`: version of the Chinese calendar.

As in [my Chinese calendar webpage](https://ytliu0.github.io/ChineseCalendar), the year y should be between -721 and 2200. In some years in the past, there were multiple versions of Chinese calendar used in those years, and the command returns only one of them. Multiple versions of calendar dates can be retrieved using parameters `...` not covered here. See the tutroial notebook for detail.

The following command `cal.western_to_chinese_year(2025, 1)` returns a list of dictaionary showing all dates in January 2025. The command `cal.western_to_chinese_year(2025)` shows all dates in 2025.

In [5]:
cal.western_to_chinese_year(2025, 1)

[{'Western ymd': [2025, 1, 1],
  'Western calendar': 'Gregorian',
  'JDN': 2460677,
  'Chinese ymd': [2024, 12, 2],
  'cyear': 2024,
  'cdate': '12-02',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Geng Wu', 7],
  'Week': ['Wed', 3],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 2],
  'Western calendar': 'Gregorian',
  'JDN': 2460678,
  'Chinese ymd': [2024, 12, 3],
  'cyear': 2024,
  'cdate': '12-03',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Xin Wei', 8],
  'Week': ['Thu', 4],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 3],
  'Western calendar': 'Gregorian',
  'JDN': 2460679,
  'Chinese ymd': [2024, 12, 4],
  'cyear': 2024,
  'cdate': '12-04',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Ren Shen', 9],
  'Week': ['Fri', 5],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 4],
  'Western calendar': 'Gregorian',
  'JDN': 2460680,
  'Chinese ymd': [2024, 12, 5],
  'cyear': 2024,
  'cdate': '12-05',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Gui You', 10],
  'Week': ['Sat', 6],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 5],
  'Western calendar': 'Gregorian',
  'JDN': 2460681,
  'Chinese ymd': [2024, 12, 6],
  'cyear': 2024,
  'cdate': '12-06',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Jia Xu', 11],
  'Week': ['Sun', 0],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 6],
  'Western calendar': 'Gregorian',
  'JDN': 2460682,
  'Chinese ymd': [2024, 12, 7],
  'cyear': 2024,
  'cdate': '12-07',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Yi Hai', 12],
  'Week': ['Mon', 1],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 7],
  'Western calendar': 'Gregorian',
  'JDN': 2460683,
  'Chinese ymd': [2024, 12, 8],
  'cyear': 2024,
  'cdate': '12-08',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Bing Zi', 13],
  'Week': ['Tue', 2],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 8],
  'Western calendar': 'Gregorian',
  'JDN': 2460684,
  'Chinese ymd': [2024, 12, 9],
  'cyear': 2024,
  'cdate': '12-09',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Ding Chou', 14],
  'Week': ['Wed', 3],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 9],
  'Western calendar': 'Gregorian',
  'JDN': 2460685,
  'Chinese ymd': [2024, 12, 10],
  'cyear': 2024,
  'cdate': '12-10',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Wu Yin', 15],
  'Week': ['Thu', 4],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 10],
  'Western calendar': 'Gregorian',
  'JDN': 2460686,
  'Chinese ymd': [2024, 12, 11],
  'cyear': 2024,
  'cdate': '12-11',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Ji Mao', 16],
  'Week': ['Fri', 5],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 11],
  'Western calendar': 'Gregorian',
  'JDN': 2460687,
  'Chinese ymd': [2024, 12, 12],
  'cyear': 2024,
  'cdate': '12-12',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Geng Chen', 17],
  'Week': ['Sat', 6],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 12],
  'Western calendar': 'Gregorian',
  'JDN': 2460688,
  'Chinese ymd': [2024, 12, 13],
  'cyear': 2024,
  'cdate': '12-13',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Xin Si', 18],
  'Week': ['Sun', 0],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 13],
  'Western calendar': 'Gregorian',
  'JDN': 2460689,
  'Chinese ymd': [2024, 12, 14],
  'cyear': 2024,
  'cdate': '12-14',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Ren Wu', 19],
  'Week': ['Mon', 1],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 14],
  'Western calendar': 'Gregorian',
  'JDN': 2460690,
  'Chinese ymd': [2024, 12, 15],
  'cyear': 2024,
  'cdate': '12-15',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Gui Wei', 20],
  'Week': ['Tue', 2],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 15],
  'Western calendar': 'Gregorian',
  'JDN': 2460691,
  'Chinese ymd': [2024, 12, 16],
  'cyear': 2024,
  'cdate': '12-16',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Jia Shen', 21],
  'Week': ['Wed', 3],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 16],
  'Western calendar': 'Gregorian',
  'JDN': 2460692,
  'Chinese ymd': [2024, 12, 17],
  'cyear': 2024,
  'cdate': '12-17',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Yi You', 22],
  'Week': ['Thu', 4],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 17],
  'Western calendar': 'Gregorian',
  'JDN': 2460693,
  'Chinese ymd': [2024, 12, 18],
  'cyear': 2024,
  'cdate': '12-18',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Bing Xu', 23],
  'Week': ['Fri', 5],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 18],
  'Western calendar': 'Gregorian',
  'JDN': 2460694,
  'Chinese ymd': [2024, 12, 19],
  'cyear': 2024,
  'cdate': '12-19',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Ding Hai', 24],
  'Week': ['Sat', 6],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 19],
  'Western calendar': 'Gregorian',
  'JDN': 2460695,
  'Chinese ymd': [2024, 12, 20],
  'cyear': 2024,
  'cdate': '12-20',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Wu Zi', 25],
  'Week': ['Sun', 0],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 20],
  'Western calendar': 'Gregorian',
  'JDN': 2460696,
  'Chinese ymd': [2024, 12, 21],
  'cyear': 2024,
  'cdate': '12-21',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Ji Chou', 26],
  'Week': ['Mon', 1],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 21],
  'Western calendar': 'Gregorian',
  'JDN': 2460697,
  'Chinese ymd': [2024, 12, 22],
  'cyear': 2024,
  'cdate': '12-22',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Geng Yin', 27],
  'Week': ['Tue', 2],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 22],
  'Western calendar': 'Gregorian',
  'JDN': 2460698,
  'Chinese ymd': [2024, 12, 23],
  'cyear': 2024,
  'cdate': '12-23',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Xin Mao', 28],
  'Week': ['Wed', 3],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 23],
  'Western calendar': 'Gregorian',
  'JDN': 2460699,
  'Chinese ymd': [2024, 12, 24],
  'cyear': 2024,
  'cdate': '12-24',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Ren Chen', 29],
  'Week': ['Thu', 4],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 24],
  'Western calendar': 'Gregorian',
  'JDN': 2460700,
  'Chinese ymd': [2024, 12, 25],
  'cyear': 2024,
  'cdate': '12-25',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Gui Si', 30],
  'Week': ['Fri', 5],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 25],
  'Western calendar': 'Gregorian',
  'JDN': 2460701,
  'Chinese ymd': [2024, 12, 26],
  'cyear': 2024,
  'cdate': '12-26',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Jia Wu', 31],
  'Week': ['Sat', 6],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 26],
  'Western calendar': 'Gregorian',
  'JDN': 2460702,
  'Chinese ymd': [2024, 12, 27],
  'cyear': 2024,
  'cdate': '12-27',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Yi Wei', 32],
  'Week': ['Sun', 0],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 27],
  'Western calendar': 'Gregorian',
  'JDN': 2460703,
  'Chinese ymd': [2024, 12, 28],
  'cyear': 2024,
  'cdate': '12-28',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Bing Shen', 33],
  'Week': ['Mon', 1],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 28],
  'Western calendar': 'Gregorian',
  'JDN': 2460704,
  'Chinese ymd': [2024, 12, 29],
  'cyear': 2024,
  'cdate': '12-29',
  'sexagenary year': ['Jia Chen', 'Dragon', 41],
  'jian': ['Ding Chou', 14],
  'Nday_cmonth': 29,
  'sexagenary date': ['Ding You', 34],
  'Week': ['Tue', 2],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 29],
  'Western calendar': 'Gregorian',
  'JDN': 2460705,
  'Chinese ymd': [2025, 1, 1],
  'cyear': 2025,
  'cdate': '1-01',
  'sexagenary year': ['Yi Si', 'Snake', 42],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Wu Xu', 35],
  'Week': ['Wed', 3],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 30],
  'Western calendar': 'Gregorian',
  'JDN': 2460706,
  'Chinese ymd': [2025, 1, 2],
  'cyear': 2025,
  'cdate': '1-02',
  'sexagenary year': ['Yi Si', 'Snake', 42],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji Hai', 36],
  'Week': ['Thu', 4],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'},
 {'Western ymd': [2025, 1, 31],
  'Western calendar': 'Gregorian',
  'JDN': 2460707,
  'Chinese ymd': [2025, 1, 3],
  'cyear': 2025,
  'cdate': '1-03',
  'sexagenary year': ['Yi Si', 'Snake', 42],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Zi', 37],
  'Week': ['Fri', 5],
  'period': 'Modern (1912 - )',
  'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'}]

The list above may be useful for further calendar calculations but is not convenient to view. The method `.western_to_chinese_year_html()` returns an html text, which can be displayed nicely in a Jupyter notebook using the `IPython.display.HTML()` function. The result is similar to the calendar table on [this Chinese calendar webpage](https://ytliu0.github.io/ChineseCalendar).

In [6]:
# Calendar table for November, 2025
HTML(cal.western_to_chinese_year_html(2025, 11))

In [7]:
# Calendar table for the year 1979
HTML(cal.western_to_chinese_year_html(1979))

In [8]:
# Calendar table for the year 690
HTML(cal.western_to_chinese_year_html(690))

As in [my Chinese calendar page](https://ytliu0.github.io/ChineseCalendar), moon phases and solar terms refer to the modern calculation using JPL's DE441 ephemeris, whereas calendrical solar terms refer to the solar terms calculated using the method at that time. Starting from 2014 and as of 2025, the official moon phases and solar terms promulgated by the Purple Mountain Observatory (the calendrical moon phases and solar terms of modern times) are computed using JPL's DE421/LE421, which are very close to our results based on DE441. All times calculated by DE441 are in UT+8 (UT1+8 for years before 1972, UTC+8 for years between 1972 and present year, and projected UTC+8 for future years).

## Chinese calendar to Western calendar conversion

Four methods are provided to do the conversion:

`.chinese_to_western_date(y, m, d, ...)`: Given a Chinese date (year = y, month = m, date = d), convert to the date in the Western calendar. For a leap month, enter a negative number for `m`.

`.chinese_year_info(y, ...)`: Given a Chinese year whose New Year day is closest to Jan 1, y in the Western calendar, this function returns a list containing the first days in Chinese months, calendrical solar terms and solar terms computed by a DE ephemeris in the Chinese year.

`.chinese_year_html(y, ...)`: Same as the previous function but returns an HTML text.

`.chinese_to_western_year(y, m=None, ...)`: Given a Chinese year y, return a list containing the Western dates corresponding to all days in the year if m is None or Western dates corresponding to all days in month m in the Western calendar.

`chinese_to_western_year_html(y, m=None, ...)`: Same as the previous function but returns an HTML text.

Again `...` denotes other optional parameters not covered in this guide.

In [9]:
# Convert the 7th day in the 7th month in Chinese year 2025 to Western date
cal.chinese_to_western_date(2025, 7, 7)

{'Chinese ymd': [2025, 7, 7],
 'Western ymd': [2025, 8, 29],
 'Western calendar': 'Gregorian',
 'JDN': 2460917,
 'cyear': 2025,
 'cdate': '7-07',
 'sexagenary year': ['Yi Si', 'Snake', 42],
 'jian': ['Jia Shen', 21],
 'Nday_cmonth': 30,
 'sexagenary date': ['Geng Wu', 7],
 'Week': ['Fri', 5],
 'period': 'Modern (1912 - )',
 'Chinese calendar': 'Purple Mountain (GB/T 33661-2017)'}

Ocassionally there are multiple days corresponding to the same Chinese date in the past. This is caused by a Chinese calendar reform. As an example, let's look at the 23rd day in the 11th month in the Chinese year 700.

In [10]:
cal.chinese_to_western_date(700, 11, 23)

[{'Chinese ymd': [700, 11, 23],
  'Western ymd': [699, 12, 19],
  'Western calendar': 'Julian',
  'JDN': 1976720,
  'cyear': 700,
  'cdate': '11-23',
  'sexagenary year': ['Geng Zi', 'Rat', 37],
  'jian': ['Bing Zi', 13],
  'Nday_cmonth': 30,
  'sexagenary date': ['Gui You', 10],
  'Week': ['Fri', 5],
  'period': 'Tang (618 - 907)',
  'reign/era': '[Zhou] Shènglì 3/Jiǔshì 1',
  'Chinese calendar': 'Linde'},
 {'Chinese ymd': [700, 11, 23],
  'Western ymd': [701, 1, 6],
  'Western calendar': 'Julian',
  'JDN': 1977104,
  'cyear': 700,
  'cdate': '11-23',
  'sexagenary year': ['Geng Zi', 'Rat', 37],
  'jian': ['Wu Zi', 25],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ding You', 34],
  'Week': ['Thu', 4],
  'period': 'Tang (618 - 907)',
  'reign/era': '[Zhou] Shènglì 3/Jiǔshì 1',
  'Chinese calendar': 'Linde'}]

The following command returns the information of the Chinese year 700.

In [11]:
cal.chinese_year_info(700)

{'cm': [{'cm': 11, 'JDN': 1976698, 'jian': '13', 'n': 30},
  {'cm': 12, 'JDN': 1976728, 'jian': '14', 'n': 30},
  {'cm': 1, 'JDN': 1976758, 'jian': '15', 'n': 30},
  {'cm': 2, 'JDN': 1976788, 'jian': '16', 'n': 29},
  {'cm': 3, 'JDN': 1976817, 'jian': '17', 'n': 30},
  {'cm': 4, 'JDN': 1976847, 'jian': '18', 'n': 29},
  {'cm': 5, 'JDN': 1976876, 'jian': '19', 'n': 29},
  {'cm': 6, 'JDN': 1976905, 'jian': '20', 'n': 30},
  {'cm': 7, 'JDN': 1976935, 'jian': '21', 'n': 29},
  {'cm': -7, 'JDN': 1976964, 'jian': 'NA', 'n': 29},
  {'cm': 8, 'JDN': 1976993, 'jian': '22', 'n': 30},
  {'cm': 9, 'JDN': 1977023, 'jian': '23', 'n': 29},
  {'cm': 10, 'JDN': 1977052, 'jian': '24', 'n': 30},
  {'cm': 11, 'JDN': 1977082, 'jian': '25', 'n': 30},
  {'cm': 12, 'JDN': 1977112, 'jian': '26', 'n': 30}],
 'calendar': 'Linde',
 'reign/era': '[Zhou] Shènglì 3/Jiǔshì 1',
 'calst': [('J11', 1976704),
  ('Z11', 1976719),
  ('J12', 1976735),
  ('Z12', 1976750),
  ('J1', 1976765),
  ('Z1', 1976780),
  ('J2', 1976796),
  ('Z2', 1976811),
  ('J3', 1976826),
  ('Z3', 1976841),
  ('J4', 1976856),
  ('Z4', 1976872),
  ('J5', 1976887),
  ('Z5', 1976902),
  ('J6', 1976917),
  ('Z6', 1976933),
  ('J7', 1976948),
  ('Z7', 1976963),
  ('J8', 1976978),
  ('Z8', 1976993),
  ('J9', 1977009),
  ('Z9', 1977024),
  ('J10', 1977039),
  ('Z10', 1977054),
  ('J11', 1977070),
  ('Z11', 1977085),
  ('J12', 1977100),
  ('Z12', 1977115),
  ('J1', 1977130)],
 'datongST': [],
 'sterm': [['J11',
   {'event': 'J11',
    'year': 699,
    'month': 12,
    'date': 4,
    'hour': 6,
    'minute': 7,
    'dateString': 'Dec 4',
    'timeString': '06:07',
    'jd0_ut': 1976366.5,
    'jd1_ut': 337.9215101693816}],
  ['Z11',
   {'event': 'Z11 (Dec. solstice)',
    'year': 699,
    'month': 12,
    'date': 18,
    'hour': 23,
    'minute': 4,
    'dateString': 'Dec 18',
    'timeString': '23:04',
    'jd0_ut': 1976366.5,
    'jd1_ut': 352.62778805956}],
  ['J12',
   {'event': 'J12',
    'year': 700,
    'month': 1,
    'date': 2,
    'hour': 16,
    'minute': 21,
    'dateString': 'Jan 2',
    'timeString': '16:21',
    'jd0_ut': 1976731.5,
    'jd1_ut': 2.3481674345704246}],
  ['Z12',
   {'event': 'Z12',
    'year': 700,
    'month': 1,
    'date': 17,
    'hour': 11,
    'minute': 6,
    'dateString': 'Jan 17',
    'timeString': '11:06',
    'jd0_ut': 1976731.5,
    'jd1_ut': 17.12891498304114}],
  ['J1',
   {'event': 'J1',
    'year': 700,
    'month': 2,
    'date': 1,
    'hour': 7,
    'minute': 40,
    'dateString': 'Feb 1',
    'timeString': '07:40',
    'jd0_ut': 1976731.5,
    'jd1_ut': 31.98584674592126}],
  ['Z1',
   {'event': 'Z1',
    'year': 700,
    'month': 2,
    'date': 16,
    'hour': 6,
    'minute': 58,
    'dateString': 'Feb 16',
    'timeString': '06:58',
    'jd0_ut': 1976731.5,
    'jd1_ut': 46.95714066913762}],
  ['J2',
   {'event': 'J2',
    'year': 700,
    'month': 3,
    'date': 2,
    'hour': 9,
    'minute': 7,
    'dateString': 'Mar 2',
    'timeString': '09:07',
    'jd0_ut': 1976731.5,
    'jd1_ut': 62.04677931037536}],
  ['Z2',
   {'event': 'Z2 (March equinox)',
    'year': 700,
    'month': 3,
    'date': 17,
    'hour': 14,
    'minute': 41,
    'dateString': 'Mar 17',
    'timeString': '14:41',
    'jd0_ut': 1976731.5,
    'jd1_ut': 77.27854363767912}],
  ['J3',
   {'event': 'J3',
    'year': 700,
    'month': 4,
    'date': 1,
    'hour': 23,
    'minute': 20,
    'dateString': 'Apr 1',
    'timeString': '23:20',
    'jd0_ut': 1976731.5,
    'jd1_ut': 92.63889503223206}],
  ['Z3',
   {'event': 'Z3',
    'year': 700,
    'month': 4,
    'date': 17,
    'hour': 11,
    'minute': 12,
    'dateString': 'Apr 17',
    'timeString': '11:12',
    'jd0_ut': 1976731.5,
    'jd1_ut': 108.13359658092664}],
  ['J4',
   {'event': 'J4',
    'year': 700,
    'month': 5,
    'date': 3,
    'hour': 1,
    'minute': 32,
    'dateString': 'May 3',
    'timeString': '01:32',
    'jd0_ut': 1976731.5,
    'jd1_ut': 123.73032607134814}],
  ['Z4',
   {'event': 'Z4',
    'year': 700,
    'month': 5,
    'date': 18,
    'hour': 18,
    'minute': 0,
    'dateString': 'May 18',
    'timeString': '18:00',
    'jd0_ut': 1976731.5,
    'jd1_ut': 139.41690309829764}],
  ['J5',
   {'event': 'J5',
    'year': 700,
    'month': 6,
    'date': 3,
    'hour': 11,
    'minute': 33,
    'dateString': 'Jun 3',
    'timeString': '11:33',
    'jd0_ut': 1976731.5,
    'jd1_ut': 155.14802213267387}],
  ['Z5',
   {'event': 'Z5 (June solstice)',
    'year': 700,
    'month': 6,
    'date': 19,
    'hour': 5,
    'minute': 34,
    'dateString': 'Jun 19',
    'timeString': '05:34',
    'jd0_ut': 1976731.5,
    'jd1_ut': 170.89835912068702}],
  ['J6',
   {'event': 'J6',
    'year': 700,
    'month': 7,
    'date': 4,
    'hour': 22,
    'minute': 55,
    'dateString': 'Jul 4',
    'timeString': '22:55',
    'jd0_ut': 1976731.5,
    'jd1_ut': 186.62150729515815}],
  ['Z6',
   {'event': 'Z6',
    'year': 700,
    'month': 7,
    'date': 20,
    'hour': 14,
    'minute': 55,
    'dateString': 'Jul 20',
    'timeString': '14:55',
    'jd0_ut': 1976731.5,
    'jd1_ut': 202.2881220833286}],
  ['J7',
   {'event': 'J7',
    'year': 700,
    'month': 8,
    'date': 5,
    'hour': 4,
    'minute': 44,
    'dateString': 'Aug 5',
    'timeString': '04:44',
    'jd0_ut': 1976731.5,
    'jd1_ut': 217.86380357633357}],
  ['Z7',
   {'event': 'Z7',
    'year': 700,
    'month': 8,
    'date': 20,
    'hour': 15,
    'minute': 48,
    'dateString': 'Aug 20',
    'timeString': '15:48',
    'jd0_ut': 1976731.5,
    'jd1_ut': 233.32488180149394}],
  ['J8',
   {'event': 'J8',
    'year': 700,
    'month': 9,
    'date': 4,
    'hour': 23,
    'minute': 47,
    'dateString': 'Sep 4',
    'timeString': '23:47',
    'jd0_ut': 1976731.5,
    'jd1_ut': 248.65748931951256}],
  ['Z8',
   {'event': 'Z8 (Sep. equinox)',
    'year': 700,
    'month': 9,
    'date': 20,
    'hour': 4,
    'minute': 26,
    'dateString': 'Sep 20',
    'timeString': '04:26',
    'jd0_ut': 1976731.5,
    'jd1_ut': 263.8511791635494}],
  ['J9',
   {'event': 'J9',
    'year': 700,
    'month': 10,
    'date': 5,
    'hour': 5,
    'minute': 57,
    'dateString': 'Oct 5',
    'timeString': '05:57',
    'jd0_ut': 1976731.5,
    'jd1_ut': 278.9142605761686}],
  ['Z9',
   {'event': 'Z9',
    'year': 700,
    'month': 10,
    'date': 20,
    'hour': 4,
    'minute': 27,
    'dateString': 'Oct 20',
    'timeString': '04:27',
    'jd0_ut': 1976731.5,
    'jd1_ut': 293.85207611782624}],
  ['J10',
   {'event': 'J10',
    'year': 700,
    'month': 11,
    'date': 4,
    'hour': 0,
    'minute': 35,
    'dateString': 'Nov 4',
    'timeString': '00:35',
    'jd0_ut': 1976731.5,
    'jd1_ut': 308.69123727544155}],
  ['Z10',
   {'event': 'Z10',
    'year': 700,
    'month': 11,
    'date': 18,
    'hour': 18,
    'minute': 48,
    'dateString': 'Nov 18',
    'timeString': '18:48',
    'jd0_ut': 1976731.5,
    'jd1_ut': 323.4502977908783}],
  ['J11',
   {'event': 'J11',
    'year': 700,
    'month': 12,
    'date': 3,
    'hour': 12,
    'minute': 0,
    'dateString': 'Dec 3',
    'timeString': '12:00',
    'jd0_ut': 1976731.5,
    'jd1_ut': 338.1670075413189}],
  ['Z11',
   {'event': 'Z11 (Dec. solstice)',
    'year': 700,
    'month': 12,
    'date': 18,
    'hour': 4,
    'minute': 49,
    'dateString': 'Dec 18',
    'timeString': '04:49',
    'jd0_ut': 1976731.5,
    'jd1_ut': 352.86744622431104}],
  ['J12',
   {'event': 'J12',
    'year': 701,
    'month': 1,
    'date': 1,
    'hour': 22,
    'minute': 13,
    'dateString': 'Jan 1',
    'timeString': '22:13',
    'jd0_ut': 1977097.5,
    'jd1_ut': 1.5922736895132177}],
  ['Z12',
   {'event': 'Z12',
    'year': 701,
    'month': 1,
    'date': 16,
    'hour': 16,
    'minute': 49,
    'dateString': 'Jan 16',
    'timeString': '16:49',
    'jd0_ut': 1977097.5,
    'jd1_ut': 16.367678836813926}],
  ['J1',
   {'event': 'J1',
    'year': 701,
    'month': 1,
    'date': 31,
    'hour': 13,
    'minute': 30,
    'dateString': 'Jan 31',
    'timeString': '13:30',
    'jd0_ut': 1977097.5,
    'jd1_ut': 31.229459936626977}]],
 'mphase': [['Q0',
   {'event': 'New Moon',
    'year': 699,
    'month': 11,
    'date': 27,
    'hour': 18,
    'minute': 27,
    'dateString': 'Nov 27',
    'timeString': '18:27',
    'jd0_ut': 1976366.5,
    'jd1_ut': 331.4357120734951,
    'eclipse': 'Annular solar eclipse',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=601&ind=248&DE=441&ref=python'}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 699,
    'month': 12,
    'date': 5,
    'hour': 23,
    'minute': 43,
    'dateString': 'Dec 5',
    'timeString': '23:43',
    'jd0_ut': 1976366.5,
    'jd1_ut': 339.6547673874774}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 699,
    'month': 12,
    'date': 12,
    'hour': 22,
    'minute': 53,
    'dateString': 'Dec 12',
    'timeString': '22:53',
    'jd0_ut': 1976366.5,
    'jd1_ut': 346.6200537443031,
    'eclipse': 'Penumbral lunar eclipse',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=601&ind=254&DE=441&shrule=revised_Danjon&ref=python'}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 699,
    'month': 12,
    'date': 19,
    'hour': 14,
    'minute': 30,
    'dateString': 'Dec 19',
    'timeString': '14:30',
    'jd0_ut': 1976366.5,
    'jd1_ut': 353.2708277570382}],
  ['Q0',
   {'event': 'New Moon',
    'year': 699,
    'month': 12,
    'date': 27,
    'hour': 14,
    'minute': 8,
    'dateString': 'Dec 27',
    'timeString': '14:08',
    'jd0_ut': 1976366.5,
    'jd1_ut': 361.2553242897828}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 1,
    'date': 4,
    'hour': 15,
    'minute': 55,
    'dateString': 'Jan 4',
    'timeString': '15:55',
    'jd0_ut': 1976731.5,
    'jd1_ut': 4.329952425347095}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 1,
    'date': 11,
    'hour': 9,
    'minute': 43,
    'dateString': 'Jan 11',
    'timeString': '09:43',
    'jd0_ut': 1976731.5,
    'jd1_ut': 11.071642169442}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 700,
    'month': 1,
    'date': 18,
    'hour': 4,
    'minute': 57,
    'dateString': 'Jan 18',
    'timeString': '04:57',
    'jd0_ut': 1976731.5,
    'jd1_ut': 17.873138425217537}],
  ['Q0',
   {'event': 'New Moon',
    'year': 700,
    'month': 1,
    'date': 26,
    'hour': 9,
    'minute': 29,
    'dateString': 'Jan 26',
    'timeString': '09:29',
    'jd0_ut': 1976731.5,
    'jd1_ut': 26.061944848194486}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 2,
    'date': 3,
    'hour': 4,
    'minute': 38,
    'dateString': 'Feb 3',
    'timeString': '04:38',
    'jd0_ut': 1976731.5,
    'jd1_ut': 33.859527520457966}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 2,
    'date': 9,
    'hour': 19,
    'minute': 52,
    'dateString': 'Feb 9',
    'timeString': '19:52',
    'jd0_ut': 1976731.5,
    'jd1_ut': 40.494611271081574}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 700,
    'month': 2,
    'date': 16,
    'hour': 22,
    'minute': 3,
    'dateString': 'Feb 16',
    'timeString': '22:03',
    'jd0_ut': 1976731.5,
    'jd1_ut': 47.58567921385633}],
  ['Q0',
   {'event': 'New Moon',
    'year': 700,
    'month': 2,
    'date': 25,
    'hour': 2,
    'minute': 50,
    'dateString': 'Feb 25',
    'timeString': '02:50',
    'jd0_ut': 1976731.5,
    'jd1_ut': 55.78494146449858}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 3,
    'date': 3,
    'hour': 13,
    'minute': 54,
    'dateString': 'Mar 3',
    'timeString': '13:54',
    'jd0_ut': 1976731.5,
    'jd1_ut': 63.24560192530407}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 3,
    'date': 10,
    'hour': 5,
    'minute': 46,
    'dateString': 'Mar 10',
    'timeString': '05:46',
    'jd0_ut': 1976731.5,
    'jd1_ut': 69.90726973766519}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 700,
    'month': 3,
    'date': 17,
    'hour': 16,
    'minute': 39,
    'dateString': 'Mar 17',
    'timeString': '16:39',
    'jd0_ut': 1976731.5,
    'jd1_ut': 77.36049855715197}],
  ['Q0',
   {'event': 'New Moon',
    'year': 700,
    'month': 3,
    'date': 25,
    'hour': 17,
    'minute': 25,
    'dateString': 'Mar 25',
    'timeString': '17:25',
    'jd0_ut': 1976731.5,
    'jd1_ut': 85.39234181637907}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 4,
    'date': 1,
    'hour': 20,
    'minute': 25,
    'dateString': 'Apr 1',
    'timeString': '20:25',
    'jd0_ut': 1976731.5,
    'jd1_ut': 92.51712304239679}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 4,
    'date': 8,
    'hour': 16,
    'minute': 10,
    'dateString': 'Apr 8',
    'timeString': '16:10',
    'jd0_ut': 1976731.5,
    'jd1_ut': 99.34036401967046}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 700,
    'month': 4,
    'date': 16,
    'hour': 11,
    'minute': 15,
    'dateString': 'Apr 16',
    'timeString': '11:15',
    'jd0_ut': 1976731.5,
    'jd1_ut': 107.13570307978425}],
  ['Q0',
   {'event': 'New Moon',
    'year': 700,
    'month': 4,
    'date': 24,
    'hour': 5,
    'minute': 14,
    'dateString': 'Apr 24',
    'timeString': '05:14',
    'jd0_ut': 1976731.5,
    'jd1_ut': 114.88467191180538}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 5,
    'date': 1,
    'hour': 1,
    'minute': 23,
    'dateString': 'May 1',
    'timeString': '01:23',
    'jd0_ut': 1976731.5,
    'jd1_ut': 121.72429054274421}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 5,
    'date': 8,
    'hour': 3,
    'minute': 44,
    'dateString': 'May 8',
    'timeString': '03:44',
    'jd0_ut': 1976731.5,
    'jd1_ut': 128.8225468598756,
    'eclipse': 'Penumbral lunar eclipse',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=601&ind=255&DE=441&shrule=revised_Danjon&ref=python'}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 700,
    'month': 5,
    'date': 16,
    'hour': 4,
    'minute': 40,
    'dateString': 'May 16',
    'timeString': '04:40',
    'jd0_ut': 1976731.5,
    'jd1_ut': 136.86135004661148}],
  ['Q0',
   {'event': 'New Moon',
    'year': 700,
    'month': 5,
    'date': 23,
    'hour': 14,
    'minute': 43,
    'dateString': 'May 23',
    'timeString': '14:43',
    'jd0_ut': 1976731.5,
    'jd1_ut': 144.28011332830945,
    'eclipse': 'Total solar eclipse',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=601&ind=249&DE=441&ref=python'}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 5,
    'date': 30,
    'hour': 6,
    'minute': 18,
    'dateString': 'May 30',
    'timeString': '06:18',
    'jd0_ut': 1976731.5,
    'jd1_ut': 150.92934077397865}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 6,
    'date': 6,
    'hour': 16,
    'minute': 49,
    'dateString': 'Jun 6',
    'timeString': '16:49',
    'jd0_ut': 1976731.5,
    'jd1_ut': 158.36764579887225}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 700,
    'month': 6,
    'date': 14,
    'hour': 20,
    'minute': 16,
    'dateString': 'Jun 14',
    'timeString': '20:16',
    'jd0_ut': 1976731.5,
    'jd1_ut': 166.51078961120638}],
  ['Q0',
   {'event': 'New Moon',
    'year': 700,
    'month': 6,
    'date': 21,
    'hour': 22,
    'minute': 34,
    'dateString': 'Jun 21',
    'timeString': '22:34',
    'jd0_ut': 1976731.5,
    'jd1_ut': 173.60664655657408}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 6,
    'date': 28,
    'hour': 12,
    'minute': 43,
    'dateString': 'Jun 28',
    'timeString': '12:43',
    'jd0_ut': 1976731.5,
    'jd1_ut': 180.1966689578949}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 7,
    'date': 6,
    'hour': 7,
    'minute': 19,
    'dateString': 'Jul 6',
    'timeString': '07:19',
    'jd0_ut': 1976731.5,
    'jd1_ut': 187.97161356717876}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 700,
    'month': 7,
    'date': 14,
    'hour': 9,
    'minute': 48,
    'dateString': 'Jul 14',
    'timeString': '09:48',
    'jd0_ut': 1976731.5,
    'jd1_ut': 196.07514555433985}],
  ['Q0',
   {'event': 'New Moon',
    'year': 700,
    'month': 7,
    'date': 21,
    'hour': 5,
    'minute': 37,
    'dateString': 'Jul 21',
    'timeString': '05:37',
    'jd0_ut': 1976731.5,
    'jd1_ut': 202.9006064032989}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 7,
    'date': 27,
    'hour': 21,
    'minute': 59,
    'dateString': 'Jul 27',
    'timeString': '21:59',
    'jd0_ut': 1976731.5,
    'jd1_ut': 209.58274818984617}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 8,
    'date': 4,
    'hour': 22,
    'minute': 51,
    'dateString': 'Aug 4',
    'timeString': '22:51',
    'jd0_ut': 1976731.5,
    'jd1_ut': 217.61878323204536}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 700,
    'month': 8,
    'date': 12,
    'hour': 21,
    'minute': 18,
    'dateString': 'Aug 12',
    'timeString': '21:18',
    'jd0_ut': 1976731.5,
    'jd1_ut': 225.55434502125357}],
  ['Q0',
   {'event': 'New Moon',
    'year': 700,
    'month': 8,
    'date': 19,
    'hour': 12,
    'minute': 56,
    'dateString': 'Aug 19',
    'timeString': '12:56',
    'jd0_ut': 1976731.5,
    'jd1_ut': 232.20569791630103}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 8,
    'date': 26,
    'hour': 10,
    'minute': 59,
    'dateString': 'Aug 26',
    'timeString': '10:59',
    'jd0_ut': 1976731.5,
    'jd1_ut': 239.12435959494346}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 9,
    'date': 3,
    'hour': 14,
    'minute': 57,
    'dateString': 'Sep 3',
    'timeString': '14:57',
    'jd0_ut': 1976731.5,
    'jd1_ut': 247.28942618687475}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 700,
    'month': 9,
    'date': 11,
    'hour': 6,
    'minute': 55,
    'dateString': 'Sep 11',
    'timeString': '06:55',
    'jd0_ut': 1976731.5,
    'jd1_ut': 254.95503692092132}],
  ['Q0',
   {'event': 'New Moon',
    'year': 700,
    'month': 9,
    'date': 17,
    'hour': 21,
    'minute': 39,
    'dateString': 'Sep 17',
    'timeString': '21:39',
    'jd0_ut': 1976731.5,
    'jd1_ut': 261.5684137474932}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 9,
    'date': 25,
    'hour': 3,
    'minute': 51,
    'dateString': 'Sep 25',
    'timeString': '03:51',
    'jd0_ut': 1976731.5,
    'jd1_ut': 268.82686881350537}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 10,
    'date': 3,
    'hour': 7,
    'minute': 4,
    'dateString': 'Oct 3',
    'timeString': '07:04',
    'jd0_ut': 1976731.5,
    'jd1_ut': 276.96131142970205}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': 700,
    'month': 10,
    'date': 10,
    'hour': 15,
    'minute': 5,
    'dateString': 'Oct 10',
    'timeString': '15:05',
    'jd0_ut': 1976731.5,
    'jd1_ut': 284.2953053181167}],
  ['Q0',
   {'event': 'New Moon',
    'year': 700,
    'month': 10,
    'date': 17,
    'hour': 8,
    'minute': 41,
    'dateString': 'Oct 17',
    'timeString': '08:41',
    'jd0_ut': 1976731.5,
    'jd1_ut': 291.0282895938344}],
  ['Q1',
   {'event': 'First Quarter',
    'year': 700,
    'month': 10,
    'date': 24,
    'hour': 23,
    'minute': 49,
    'dateString': 'Oct 24',
    'timeString': '23:49',
    'jd0_ut': 1976731.5,
    'jd1_ut': 298.6591313744126}],
  ['Q2',
   {'event': 'Full Moon',
    'year': 700,
    'month': 11,
    'date': 1,
    'hour': 22,
    'minute': 35,
    'dateString': 'Nov 1',
    'timeString': '22:35',
    'jd0_ut': 1976731.5,
    'jd1_ut': 306.60729885913,
    'eclipse': 'Partial lunar eclipse',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=601&ind=256&DE=441&shrule=revised_Danjon&ref=python'}],
  ['Q3',
   {'event': 'Last Quarter',

The function returns a python dictionary with the following keys:

`'cm'`: a list containing the information of all Chinese months in the form of \[{'cm':m1, 'JDN':JDN1, 'jian':'jian1', 'n':n1}, {'cm':m2, 'JDN':JDN2, 'jian':'jian2', 'n':n2}, ...\] with 'cm' indicating the Chinese month number (negative for a leap month), 'JDN' indicating the Julian date at noon of the first day of the Chinese month, 'jian' indicating the sexagenary month cycle associated with jian ('jian'='1' for jia zi, '2' for yi chou, ... '60' for gui hai, 'NA' for months without jian (leap months or months before -103 when no Zhongqi rule was not imposed), 'NZ' for a month not containing a major solar term (only for the ancient six calendars)), and 'n' indicating the number of days in the Chinese month. The list is sorted in ascending order in the values in 'JDN'.

`'calendar'`: version of the Chinese calendar (e.g. 'Santong', 'Shixian').

`'reign/era'` (optional): reign and/or era name of the Chinese year (only for years before 1912).

`'calst'`: list of tuples \[(lab1, jdn1), (lab2, jdn2), ...\] where lab1, lab2, ... are the lables of the calendrical solar terms (e.g. 'J1', 'Z4') and jdn1, jdn2, ... are the Julian dates at noon of the solar terms.

`'datongST'` (optional): list of tuples \[(lab1, jdn1), (lab2, jdn2), ...\] of all the Datong solar terms in the Chinese year. This is only present for 1667 <= y <= 1669.

`'sterm'`: a list \[\[lab1, info1\], \[lab2, info2\], ...\] containing all solar terms based on DE441 in Chinese year y, where lab1, lab2, ... are the labels of the solar terms (e.g. 'J8', 'Z3') and info1, info2, ... are dictionaries containing the Western date and time information of the solar terms.

`'mphase'`: a list \[\[lab1, info1\], \[lab2, info2\], ...\] containing all moon phases based on DE441 in year y, where lab1, lab2, ... are the labels of the moon phases (e.g. 'Q0', 'Q3') and info1, info2, ... are dictionaries containing the Western date and time information of the moon phases.

The returned python list is not convenient for viewing. The `.chinese_year_info_html()` method geneartes an HTML text for a table, which can be viewed in the Jupyter notebook using `IPython.display.HTML()` function.

In [12]:
# Chinese year 700
HTML(cal.chinese_year_html(700))

In [13]:
# Chinese year 1669
HTML(cal.chinese_year_html(1669))

In [14]:
# Chinese year 2025
HTML(cal.chinese_year_html(2025))

In [15]:
# Extract all days in Chinese month 9 in the Chinese year 156
cal.chinese_to_western_year(156, 9)

[{'Chinese ymd': [156, 9, 1],
  'Western ymd': [156, 10, 2],
  'Western calendar': 'Julian',
  'JDN': 1778312,
  'cyear': 156,
  'cdate': '9-01',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Yi You', 22],
  'Week': ['Fri', 5],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 2],
  'Western ymd': [156, 10, 3],
  'Western calendar': 'Julian',
  'JDN': 1778313,
  'cyear': 156,
  'cdate': '9-02',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Bing Xu', 23],
  'Week': ['Sat', 6],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 3],
  'Western ymd': [156, 10, 4],
  'Western calendar': 'Julian',
  'JDN': 1778314,
  'cyear': 156,
  'cdate': '9-03',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ding Hai', 24],
  'Week': ['Sun', 0],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 4],
  'Western ymd': [156, 10, 5],
  'Western calendar': 'Julian',
  'JDN': 1778315,
  'cyear': 156,
  'cdate': '9-04',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Wu Zi', 25],
  'Week': ['Mon', 1],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 5],
  'Western ymd': [156, 10, 6],
  'Western calendar': 'Julian',
  'JDN': 1778316,
  'cyear': 156,
  'cdate': '9-05',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji Chou', 26],
  'Week': ['Tue', 2],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 6],
  'Western ymd': [156, 10, 7],
  'Western calendar': 'Julian',
  'JDN': 1778317,
  'cyear': 156,
  'cdate': '9-06',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Yin', 27],
  'Week': ['Wed', 3],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 7],
  'Western ymd': [156, 10, 8],
  'Western calendar': 'Julian',
  'JDN': 1778318,
  'cyear': 156,
  'cdate': '9-07',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Xin Mao', 28],
  'Week': ['Thu', 4],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 8],
  'Western ymd': [156, 10, 9],
  'Western calendar': 'Julian',
  'JDN': 1778319,
  'cyear': 156,
  'cdate': '9-08',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ren Chen', 29],
  'Week': ['Fri', 5],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 9],
  'Western ymd': [156, 10, 10],
  'Western calendar': 'Julian',
  'JDN': 1778320,
  'cyear': 156,
  'cdate': '9-09',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Gui Si', 30],
  'Week': ['Sat', 6],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 10],
  'Western ymd': [156, 10, 11],
  'Western calendar': 'Julian',
  'JDN': 1778321,
  'cyear': 156,
  'cdate': '9-10',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Jia Wu', 31],
  'Week': ['Sun', 0],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 11],
  'Western ymd': [156, 10, 12],
  'Western calendar': 'Julian',
  'JDN': 1778322,
  'cyear': 156,
  'cdate': '9-11',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Yi Wei', 32],
  'Week': ['Mon', 1],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 12],
  'Western ymd': [156, 10, 13],
  'Western calendar': 'Julian',
  'JDN': 1778323,
  'cyear': 156,
  'cdate': '9-12',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Bing Shen', 33],
  'Week': ['Tue', 2],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 13],
  'Western ymd': [156, 10, 14],
  'Western calendar': 'Julian',
  'JDN': 1778324,
  'cyear': 156,
  'cdate': '9-13',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ding You', 34],
  'Week': ['Wed', 3],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 14],
  'Western ymd': [156, 10, 15],
  'Western calendar': 'Julian',
  'JDN': 1778325,
  'cyear': 156,
  'cdate': '9-14',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Wu Xu', 35],
  'Week': ['Thu', 4],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 15],
  'Western ymd': [156, 10, 16],
  'Western calendar': 'Julian',
  'JDN': 1778326,
  'cyear': 156,
  'cdate': '9-15',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji Hai', 36],
  'Week': ['Fri', 5],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 16],
  'Western ymd': [156, 10, 17],
  'Western calendar': 'Julian',
  'JDN': 1778327,
  'cyear': 156,
  'cdate': '9-16',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Zi', 37],
  'Week': ['Sat', 6],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 17],
  'Western ymd': [156, 10, 18],
  'Western calendar': 'Julian',
  'JDN': 1778328,
  'cyear': 156,
  'cdate': '9-17',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Xin Chou', 38],
  'Week': ['Sun', 0],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 18],
  'Western ymd': [156, 10, 19],
  'Western calendar': 'Julian',
  'JDN': 1778329,
  'cyear': 156,
  'cdate': '9-18',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ren Yin', 39],
  'Week': ['Mon', 1],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 19],
  'Western ymd': [156, 10, 20],
  'Western calendar': 'Julian',
  'JDN': 1778330,
  'cyear': 156,
  'cdate': '9-19',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Gui Mao', 40],
  'Week': ['Tue', 2],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 20],
  'Western ymd': [156, 10, 21],
  'Western calendar': 'Julian',
  'JDN': 1778331,
  'cyear': 156,
  'cdate': '9-20',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Jia Chen', 41],
  'Week': ['Wed', 3],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 21],
  'Western ymd': [156, 10, 22],
  'Western calendar': 'Julian',
  'JDN': 1778332,
  'cyear': 156,
  'cdate': '9-21',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Yi Si', 42],
  'Week': ['Thu', 4],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 22],
  'Western ymd': [156, 10, 23],
  'Western calendar': 'Julian',
  'JDN': 1778333,
  'cyear': 156,
  'cdate': '9-22',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Bing Wu', 43],
  'Week': ['Fri', 5],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 23],
  'Western ymd': [156, 10, 24],
  'Western calendar': 'Julian',
  'JDN': 1778334,
  'cyear': 156,
  'cdate': '9-23',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ding Wei', 44],
  'Week': ['Sat', 6],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 24],
  'Western ymd': [156, 10, 25],
  'Western calendar': 'Julian',
  'JDN': 1778335,
  'cyear': 156,
  'cdate': '9-24',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Wu Shen', 45],
  'Week': ['Sun', 0],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 25],
  'Western ymd': [156, 10, 26],
  'Western calendar': 'Julian',
  'JDN': 1778336,
  'cyear': 156,
  'cdate': '9-25',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji You', 46],
  'Week': ['Mon', 1],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 26],
  'Western ymd': [156, 10, 27],
  'Western calendar': 'Julian',
  'JDN': 1778337,
  'cyear': 156,
  'cdate': '9-26',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Xu', 47],
  'Week': ['Tue', 2],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 27],
  'Western ymd': [156, 10, 28],
  'Western calendar': 'Julian',
  'JDN': 1778338,
  'cyear': 156,
  'cdate': '9-27',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Xin Hai', 48],
  'Week': ['Wed', 3],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 28],
  'Western ymd': [156, 10, 29],
  'Western calendar': 'Julian',
  'JDN': 1778339,
  'cyear': 156,
  'cdate': '9-28',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ren Zi', 49],
  'Week': ['Thu', 4],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 29],
  'Western ymd': [156, 10, 30],
  'Western calendar': 'Julian',
  'JDN': 1778340,
  'cyear': 156,
  'cdate': '9-29',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Gui Chou', 50],
  'Week': ['Fri', 5],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'},
 {'Chinese ymd': [156, 9, 30],
  'Western ymd': [156, 10, 31],
  'Western calendar': 'Julian',
  'JDN': 1778341,
  'cyear': 156,
  'cdate': '9-30',
  'sexagenary year': ['Bing Shen', 'Monkey', 33],
  'jian': ['Wu Xu', 35],
  'Nday_cmonth': 30,
  'sexagenary date': ['Jia Yin', 51],
  'Week': ['Sat', 6],
  'period': 'Eastern Han (25 - 219)',
  'reign/era': '[Han] Huándì Yǒngshòu 2',
  'Chinese calendar': 'Sifen'}]

In [16]:
# Create an HTML table for the Chinese month 9 in the Chinese year 156
HTML(cal.chinese_to_western_year_html(156, 9))

In [17]:
# Create an HTML table for the Chinese year 1980
HTML(cal.chinese_to_western_year_html(1980))

Unlike `.western_to_chinese_year_html()`, the dates of moon phases and solar terms under each month refer to the dates in the Chinese calendar.

## Moon phases and solar terms

Dates and times of moon phases and solar terms calculated by a modern ephemeris can be obtained from the `.sunMoon.sunMoon` class. The following commands create an instance of the `sunMoon` object.

In [18]:
sm = ccal.sunMoon.sunMoon('Eng', 'DE441')

The first parameter 'Eng' sets the display language as English. Two other possible parameters are 'ChiT' for traditional Chinese and 'ChiS' for simplified Chinese.

The second parameter 'DE441' sets the ephemeris for moon phases and solar terms to be JPL's DE441 ephemeris. Another option is 'DE431' for JPL's DE431 ephemeris. These two ephemerides give practically identical moon phase and solar term times in years within a few hundred years from 2000. As mentioned above, the official moon phases and solar terms promulgated by the Purple Mountain Observatory in 2014-present (as of 2025) are calculated by JPL's DE421/LE421, which also gives practially identical moon phase and solar term times from 2014-present. The moon phases and solar terms promulgated by the Purple Mountain Observatory in 1951-2013 were calculated by older ephemerides and could deviate from those of DE431/DE441 by one minute.

In [19]:
# Extract solar terms and moon phases in 2025
st, mp = sm.st_mp(2025)
print('solar terms:\n', st)
print('moon phases:\n', mp)

solar terms:
 [['J12', {'event': 'J12', 'year': 2025, 'month': 1, 'date': 5, 'hour': 10, 'minute': 33, 'dateString': 'Jan 5', 'timeString': '10:33', 'jd0_ut': 2460675.5, 'jd1_ut': 5.106092071880626}], ['Z12', {'event': 'Z12', 'year': 2025, 'month': 1, 'date': 20, 'hour': 4, 'minute': 0, 'dateString': 'Jan 20', 'timeString': '04:00', 'jd0_ut': 2460675.5, 'jd1_ut': 19.83341960335423}], ['J1', {'event': 'J1', 'year': 2025, 'month': 2, 'date': 3, 'hour': 22, 'minute': 10, 'dateString': 'Feb 3', 'timeString': '22:10', 'jd0_ut': 2460675.5, 'jd1_ut': 34.59060328647452}], ['Z1', {'event': 'Z1', 'year': 2025, 'month': 2, 'date': 18, 'hour': 18, 'minute': 7, 'dateString': 'Feb 18', 'timeString': '18:07', 'jd0_ut': 2460675.5, 'jd1_ut': 49.42122993693512}], ['J2', {'event': 'J2', 'year': 2025, 'month': 3, 'date': 5, 'hour': 16, 'minute': 7, 'dateString': 'Mar 5', 'timeString': '16:07', 'jd0_ut': 2460675.5, 'jd1_ut': 64.33838170980152}], ['Z2', {'event': 'Z2 (March equinox)', 'year': 2025, 'month': 3, 'date': 20, 'hour': 17, 'minute': 1, 'dateString': 'Mar 20', 'timeString': '17:01', 'jd0_ut': 2460675.5, 'jd1_ut': 79.37602936184282}], ['J3', {'event': 'J3', 'year': 2025, 'month': 4, 'date': 4, 'hour': 20, 'minute': 49, 'dateString': 'Apr 4', 'timeString': '20:49', 'jd0_ut': 2460675.5, 'jd1_ut': 94.53372417348322}], ['Z3', {'event': 'Z3', 'year': 2025, 'month': 4, 'date': 20, 'hour': 3, 'minute': 56, 'dateString': 'Apr 20', 'timeString': '03:56', 'jd0_ut': 2460675.5, 'jd1_ut': 109.83056878571793}], ['J4', {'event': 'J4', 'year': 2025, 'month': 5, 'date': 5, 'hour': 13, 'minute': 57, 'dateString': 'May 5', 'timeString': '13:57', 'jd0_ut': 2460675.5, 'jd1_ut': 125.24804905646992}], ['Z4', {'event': 'Z4', 'year': 2025, 'month': 5, 'date': 21, 'hour': 2, 'minute': 55, 'dateString': 'May 21', 'timeString': '02:55', 'jd0_ut': 2460675.5, 'jd1_ut': 140.7879417198639}], ['J5', {'event': 'J5', 'year': 2025, 'month': 6, 'date': 5, 'hour': 17, 'minute': 57, 'dateString': 'Jun 5', 'timeString': '17:57', 'jd0_ut': 2460675.5, 'jd1_ut': 156.4142496984179}], ['Z5', {'event': 'Z5 (June solstice)', 'year': 2025, 'month': 6, 'date': 21, 'hour': 10, 'minute': 42, 'dateString': 'Jun 21', 'timeString': '10:42', 'jd0_ut': 2460675.5, 'jd1_ut': 172.1126815013149}], ['J6', {'event': 'J6', 'year': 2025, 'month': 7, 'date': 7, 'hour': 4, 'minute': 5, 'dateString': 'Jul 7', 'timeString': '04:05', 'jd0_ut': 2460675.5, 'jd1_ut': 187.83679511281792}], ['Z6', {'event': 'Z6', 'year': 2025, 'month': 7, 'date': 22, 'hour': 21, 'minute': 29, 'dateString': 'Jul 22', 'timeString': '21:29', 'jd0_ut': 2460675.5, 'jd1_ut': 203.56211940597592}], ['J7', {'event': 'J7', 'year': 2025, 'month': 8, 'date': 7, 'hour': 13, 'minute': 52, 'dateString': 'Aug 7', 'timeString': '13:52', 'jd0_ut': 2460675.5, 'jd1_ut': 219.2441517825249}], ['Z7', {'event': 'Z7', 'year': 2025, 'month': 8, 'date': 23, 'hour': 4, 'minute': 34, 'dateString': 'Aug 23', 'timeString': '04:34', 'jd0_ut': 2460675.5, 'jd1_ut': 234.85684575782793}], ['J8', {'event': 'J8', 'year': 2025, 'month': 9, 'date': 7, 'hour': 16, 'minute': 52, 'dateString': 'Sep 7', 'timeString': '16:52', 'jd0_ut': 2460675.5, 'jd1_ut': 250.3694060566639}], ['Z8', {'event': 'Z8 (Sep. equinox)', 'year': 2025, 'month': 9, 'date': 23, 'hour': 2, 'minute': 19, 'dateString': 'Sep 23', 'timeString': '02:19', 'jd0_ut': 2460675.5, 'jd1_ut': 265.763431731398}], ['J9', {'event': 'J9', 'year': 2025, 'month': 10, 'date': 8, 'hour': 8, 'minute': 41, 'dateString': 'Oct 8', 'timeString': '08:41', 'jd0_ut': 2460675.5, 'jd1_ut': 281.02861235101096}], ['Z9', {'event': 'Z9', 'year': 2025, 'month': 10, 'date': 23, 'hour': 11, 'minute': 51, 'dateString': 'Oct 23', 'timeString': '11:51', 'jd0_ut': 2460675.5, 'jd1_ut': 296.16036407889897}], ['J10', {'event': 'J10', 'year': 2025, 'month': 11, 'date': 7, 'hour': 12, 'minute': 4, 'dateString': 'Nov 7', 'timeString': '12:04', 'jd0_ut': 2460675.5, 'jd1_ut': 311.16947619983597}], ['Z10', {'event': 'Z10', 'year': 2025, 'month': 11, 'date': 22, 'hour': 9, 'minute': 36, 'dateString': 'Nov 22', 'timeString': '09:36', 'jd0_ut': 2460675.5, 'jd1_ut': 326.066372247889}], ['J11', {'event': 'J11', 'year': 2025, 'month': 12, 'date': 7, 'hour': 5, 'minute': 5, 'dateString': 'Dec 7', 'timeString': '05:05', 'jd0_ut': 2460675.5, 'jd1_ut': 340.87818211916}], ['Z11', {'event': 'Z11 (Dec. solstice)', 'year': 2025, 'month': 12, 'date': 21, 'hour': 23, 'minute': 3, 'dateString': 'Dec 21', 'timeString': '23:03', 'jd0_ut': 2460675.5, 'jd1_ut': 355.627142970562}]]
moon phases:
 [['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 1, 'date': 7, 'hour': 7, 'minute': 56, 'dateString': 'Jan 7', 'timeString': '07:56', 'jd0_ut': 2460675.5, 'jd1_ut': 6.997426499745337}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 1, 'date': 14, 'hour': 6, 'minute': 27, 'dateString': 'Jan 14', 'timeString': '06:27', 'jd0_ut': 2460675.5, 'jd1_ut': 13.935353490223724}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 1, 'date': 22, 'hour': 4, 'minute': 31, 'dateString': 'Jan 22', 'timeString': '04:31', 'jd0_ut': 2460675.5, 'jd1_ut': 21.85471605012533}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 1, 'date': 29, 'hour': 20, 'minute': 36, 'dateString': 'Jan 29', 'timeString': '20:36', 'jd0_ut': 2460675.5, 'jd1_ut': 29.52498730700813}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 2, 'date': 5, 'hour': 16, 'minute': 2, 'dateString': 'Feb 5', 'timeString': '16:02', 'jd0_ut': 2460675.5, 'jd1_ut': 36.33482814883092}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 2, 'date': 12, 'hour': 21, 'minute': 53, 'dateString': 'Feb 12', 'timeString': '21:53', 'jd0_ut': 2460675.5, 'jd1_ut': 43.57874926958232}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 2, 'date': 21, 'hour': 1, 'minute': 33, 'dateString': 'Feb 21', 'timeString': '01:33', 'jd0_ut': 2460675.5, 'jd1_ut': 51.73093342133332}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 2, 'date': 28, 'hour': 8, 'minute': 45, 'dateString': 'Feb 28', 'timeString': '08:45', 'jd0_ut': 2460675.5, 'jd1_ut': 59.03112868022792}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 3, 'date': 7, 'hour': 0, 'minute': 32, 'dateString': 'Mar 7', 'timeString': '00:32', 'jd0_ut': 2460675.5, 'jd1_ut': 65.68863105878413}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 3, 'date': 14, 'hour': 14, 'minute': 55, 'dateString': 'Mar 14', 'timeString': '14:55', 'jd0_ut': 2460675.5, 'jd1_ut': 73.28795360964983, 'eclipse': 'Total lunar eclipse', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=2001&ind=56&DE=441&shrule=revised_Danjon&ref=python'}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 3, 'date': 22, 'hour': 19, 'minute': 29, 'dateString': 'Mar 22', 'timeString': '19:29', 'jd0_ut': 2460675.5, 'jd1_ut': 81.47877817938983}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 3, 'date': 29, 'hour': 18, 'minute': 58, 'dateString': 'Mar 29', 'timeString': '18:58', 'jd0_ut': 2460675.5, 'jd1_ut': 88.45682775942673, 'eclipse': 'Partial solar eclipse', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=2001&ind=52&DE=441&ref=python'}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 4, 'date': 5, 'hour': 10, 'minute': 15, 'dateString': 'Apr 5', 'timeString': '10:15', 'jd0_ut': 2460675.5, 'jd1_ut': 95.09353156687573}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 4, 'date': 13, 'hour': 8, 'minute': 22, 'dateString': 'Apr 13', 'timeString': '08:22', 'jd0_ut': 2460675.5, 'jd1_ut': 103.01545855832393}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 4, 'date': 21, 'hour': 9, 'minute': 36, 'dateString': 'Apr 21', 'timeString': '09:36', 'jd0_ut': 2460675.5, 'jd1_ut': 111.06636856068192}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 4, 'date': 28, 'hour': 3, 'minute': 31, 'dateString': 'Apr 28', 'timeString': '03:31', 'jd0_ut': 2460675.5, 'jd1_ut': 117.81330174351592}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 5, 'date': 4, 'hour': 21, 'minute': 52, 'dateString': 'May 4', 'timeString': '21:52', 'jd0_ut': 2460675.5, 'jd1_ut': 124.57761137351893}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 5, 'date': 13, 'hour': 0, 'minute': 56, 'dateString': 'May 13', 'timeString': '00:56', 'jd0_ut': 2460675.5, 'jd1_ut': 132.7055130367809}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 5, 'date': 20, 'hour': 19, 'minute': 59, 'dateString': 'May 20', 'timeString': '19:59', 'jd0_ut': 2460675.5, 'jd1_ut': 140.49914448437892}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 5, 'date': 27, 'hour': 11, 'minute': 2, 'dateString': 'May 27', 'timeString': '11:02', 'jd0_ut': 2460675.5, 'jd1_ut': 147.12663254637093}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 6, 'date': 3, 'hour': 11, 'minute': 41, 'dateString': 'Jun 3', 'timeString': '11:41', 'jd0_ut': 2460675.5, 'jd1_ut': 154.1534506400329}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 6, 'date': 11, 'hour': 15, 'minute': 44, 'dateString': 'Jun 11', 'timeString': '15:44', 'jd0_ut': 2460675.5, 'jd1_ut': 162.32211035673492}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 6, 'date': 19, 'hour': 3, 'minute': 19, 'dateString': 'Jun 19', 'timeString': '03:19', 'jd0_ut': 2460675.5, 'jd1_ut': 169.80493859105192}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 6, 'date': 25, 'hour': 18, 'minute': 32, 'dateString': 'Jun 25', 'timeString': '18:32', 'jd0_ut': 2460675.5, 'jd1_ut': 176.43862369488193}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 7, 'date': 3, 'hour': 3, 'minute': 30, 'dateString': 'Jul 3', 'timeString': '03:30', 'jd0_ut': 2460675.5, 'jd1_ut': 183.81263244977492}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 7, 'date': 11, 'hour': 4, 'minute': 37, 'dateString': 'Jul 11', 'timeString': '04:37', 'jd0_ut': 2460675.5, 'jd1_ut': 191.8588846595249}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 7, 'date': 18, 'hour': 8, 'minute': 38, 'dateString': 'Jul 18', 'timeString': '08:38', 'jd0_ut': 2460675.5, 'jd1_ut': 199.02615836602192}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 7, 'date': 25, 'hour': 3, 'minute': 11, 'dateString': 'Jul 25', 'timeString': '03:11', 'jd0_ut': 2460675.5, 'jd1_ut': 205.79944498391592}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 8, 'date': 1, 'hour': 20, 'minute': 41, 'dateString': 'Aug 1', 'timeString': '20:41', 'jd0_ut': 2460675.5, 'jd1_ut': 213.5286960989409}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 8, 'date': 9, 'hour': 15, 'minute': 55, 'dateString': 'Aug 9', 'timeString': '15:55', 'jd0_ut': 2460675.5, 'jd1_ut': 221.3299118558479}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 8, 'date': 16, 'hour': 13, 'minute': 12, 'dateString': 'Aug 16', 'timeString': '13:12', 'jd0_ut': 2460675.5, 'jd1_ut': 228.2168311195549}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 8, 'date': 23, 'hour': 14, 'minute': 7, 'dateString': 'Aug 23', 'timeString': '14:07', 'jd0_ut': 2460675.5, 'jd1_ut': 235.2545487174299}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 8, 'date': 31, 'hour': 14, 'minute': 25, 'dateString': 'Aug 31', 'timeString': '14:25', 'jd0_ut': 2460675.5, 'jd1_ut': 243.26749951340392}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 9, 'date': 8, 'hour': 2, 'minute': 9, 'dateString': 'Sep 8', 'timeString': '02:09', 'jd0_ut': 2460675.5, 'jd1_ut': 250.75617874416892, 'eclipse': 'Total lunar eclipse', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=2001&ind=57&DE=441&shrule=revised_Danjon&ref=python'}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 9, 'date': 14, 'hour': 18, 'minute': 33, 'dateString': 'Sep 14', 'timeString': '18:33', 'jd0_ut': 2460675.5, 'jd1_ut': 257.439552214294}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 9, 'date': 22, 'hour': 3, 'minute': 54, 'dateString': 'Sep 22', 'timeString': '03:54', 'jd0_ut': 2460675.5, 'jd1_ut': 264.82925758711895, 'eclipse': 'Partial solar eclipse', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=2001&ind=53&DE=441&ref=python'}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 9, 'date': 30, 'hour': 7, 'minute': 54, 'dateString': 'Sep 30', 'timeString': '07:54', 'jd0_ut': 2460675.5, 'jd1_ut': 272.99571627087795}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 10, 'date': 7, 'hour': 11, 'minute': 48, 'dateString': 'Oct 7', 'timeString': '11:48', 'jd0_ut': 2460675.5, 'jd1_ut': 280.15806562510295}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 10, 'date': 14, 'hour': 2, 'minute': 13, 'dateString': 'Oct 14', 'timeString': '02:13', 'jd0_ut': 2460675.5, 'jd1_ut': 286.758814270732}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 10, 'date': 21, 'hour': 20, 'minute': 25, 'dateString': 'Oct 21', 'timeString': '20:25', 'jd0_ut': 2460675.5, 'jd1_ut': 294.51748183067696}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 10, 'date': 30, 'hour': 0, 'minute': 21, 'dateString': 'Oct 30', 'timeString': '00:21', 'jd0_ut': 2460675.5, 'jd1_ut': 302.681124447078}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 11, 'date': 5, 'hour': 21, 'minute': 19, 'dateString': 'Nov 5', 'timeString': '21:19', 'jd0_ut': 2460675.5, 'jd1_ut': 309.55507464925597}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 11, 'date': 12, 'hour': 13, 'minute': 28, 'dateString': 'Nov 12', 'timeString': '13:28', 'jd0_ut': 2460675.5, 'jd1_ut': 316.227878018918}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 11, 'date': 20, 'hour': 14, 'minute': 47, 'dateString': 'Nov 20', 'timeString': '14:47', 'jd0_ut': 2460675.5, 'jd1_ut': 324.28282513227197}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 11, 'date': 28, 'hour': 14, 'minute': 59, 'dateString': 'Nov 28', 'timeString': '14:59', 'jd0_ut': 2460675.5, 'jd1_ut': 332.29083264566697}], ['Q2', {'event': 'Full Moon', 'year': 2025, 'month': 12, 'date': 5, 'hour': 7, 'minute': 14, 'dateString': 'Dec 5', 'timeString': '07:14', 'jd0_ut': 2460675.5, 'jd1_ut': 338.96810757277797}], ['Q3', {'event': 'Last Quarter', 'year': 2025, 'month': 12, 'date': 12, 'hour': 4, 'minute': 52, 'dateString': 'Dec 12', 'timeString': '04:52', 'jd0_ut': 2460675.5, 'jd1_ut': 345.86922848582196}], ['Q0', {'event': 'New Moon', 'year': 2025, 'month': 12, 'date': 20, 'hour': 9, 'minute': 43, 'dateString': 'Dec 20', 'timeString': '09:43', 'jd0_ut': 2460675.5, 'jd1_ut': 354.07176785431994}], ['Q1', {'event': 'First Quarter', 'year': 2025, 'month': 12, 'date': 28, 'hour': 3, 'minute': 10, 'dateString': 'Dec 28', 'timeString': '03:10', 'jd0_ut': 2460675.5, 'jd1_ut': 361.79851133850997}]]

In [20]:
# Extract solar terms and moon phases in 2025 and put them into pandas df's
st, mp = sm.st_mp_df(2025)
display(st)
display(mp)

             solar term    time (UT+8)
0                   J12   Jan 5, 10:33
1                   Z12  Jan 20, 04:00
2                    J1   Feb 3, 22:10
3                    Z1  Feb 18, 18:07
4                    J2   Mar 5, 16:07
5    Z2 (March equinox)  Mar 20, 17:01
6                    J3   Apr 4, 20:49
7                    Z3  Apr 20, 03:56
8                    J4   May 5, 13:57
9                    Z4  May 21, 02:55
10                   J5   Jun 5, 17:57
11   Z5 (June solstice)  Jun 21, 10:42
12                   J6   Jul 7, 04:05
13                   Z6  Jul 22, 21:29
14                   J7   Aug 7, 13:52
15                   Z7  Aug 23, 04:34
16                   J8   Sep 7, 16:52
17    Z8 (Sep. equinox)  Sep 23, 02:19
18                   J9   Oct 8, 08:41
19                   Z9  Oct 23, 11:51
20                  J10   Nov 7, 12:04
21                  Z10  Nov 22, 09:36
22                  J11   Dec 7, 05:05
23  Z11 (Dec. solstice)  Dec 21, 23:03

,New Moon,First Quarter,Full Moon,Last Quarter
0,,"Jan 7, 07:56","Jan 14, 06:27","Jan 22, 04:31"
1,"Jan 29, 20:36","Feb 5, 16:02","Feb 12, 21:53","Feb 21, 01:33"
2,"Feb 28, 08:45","Mar 7, 00:32","Mar 14, 14:55<br /><a href=""http://ytliu.epizy...","Mar 22, 19:29"
3,"Mar 29, 18:58<br /><a href=""http://ytliu.epizy...","Apr 5, 10:15","Apr 13, 08:22","Apr 21, 09:36"
4,"Apr 28, 03:31","May 4, 21:52","May 13, 00:56","May 20, 19:59"
5,"May 27, 11:02","Jun 3, 11:41","Jun 11, 15:44","Jun 19, 03:19"
6,"Jun 25, 18:32","Jul 3, 03:30","Jul 11, 04:37","Jul 18, 08:38"
7,"Jul 25, 03:11","Aug 1, 20:41","Aug 9, 15:55","Aug 16, 13:12"
8,"Aug 23, 14:07","Aug 31, 14:25","Sep 8, 02:09<br /><a href=""http://ytliu.epizy....","Sep 14, 18:33"
9,"Sep 22, 03:54<br /><a href=""http://ytliu.epizy...","Sep 30, 07:54","Oct 7, 11:48","Oct 14, 02:13"
10,"Oct 21, 20:25","Oct 30, 00:21","Nov 5, 21:19","Nov 12, 13:28"
11,"Nov 20, 14:47","Nov 28, 14:59","Dec 5, 07:14","Dec 12, 04:52"
12,"Dec 20, 09:43","Dec 28, 03:10",,

Note that links to information on eclipses are provided in the moon phase data. To properly display the links, we can convert the pandas df to html and then use HTML to display the result. The resulting table is similar to my [moon phase and solar term page](https://ytliu0.github.io/ChineseCalendar/sunMoon.html).

In [21]:
HTML(mp.to_html(
    render_links=True,
    escape=False,
))

## Calendrical solar terms

Solar terms in the past were not calculated using modern ephemerides, but were calculated using the astronomical systems developed in the past. I call them the calendrical solar terms. The method `.calendrical_solar_terms(y)` returns the calendrical solar terms in Western year y.

In [22]:
# calendrical solar term in 1532
cal.calendrical_solar_terms(1532)

[{'solar term': 'Z12', 'date': 'Jan 12'},
 {'solar term': 'J1', 'date': 'Jan 27'},
 {'solar term': 'Z1', 'date': 'Feb 11'},
 {'solar term': 'J2', 'date': 'Feb 27'},
 {'solar term': 'Z2 (March equinox)', 'date': 'Mar 13'},
 {'solar term': 'J3', 'date': 'Mar 28'},
 {'solar term': 'Z3', 'date': 'Apr 12'},
 {'solar term': 'J4', 'date': 'Apr 27'},
 {'solar term': 'Z4', 'date': 'May 13'},
 {'solar term': 'J5', 'date': 'May 28'},
 {'solar term': 'Z5 (June solstice)', 'date': 'Jun 12'},
 {'solar term': 'J6', 'date': 'Jun 27'},
 {'solar term': 'Z6', 'date': 'Jul 12'},
 {'solar term': 'J7', 'date': 'Jul 28'},
 {'solar term': 'Z7', 'date': 'Aug 12'},
 {'solar term': 'J8', 'date': 'Aug 27'},
 {'solar term': 'Z8 (Sep. equinox)', 'date': 'Sep 11'},
 {'solar term': 'J9', 'date': 'Sep 27'},
 {'solar term': 'Z9', 'date': 'Oct 12'},
 {'solar term': 'J10', 'date': 'Oct 27'},
 {'solar term': 'Z10', 'date': 'Nov 11'},
 {'solar term': 'J11', 'date': 'Nov 26'},
 {'solar term': 'Z11 (Dec. solstice)', 'date': 'Dec 12'},
 {'solar term': 'J12', 'date': 'Dec 27'}]

In [23]:
# calendrical solar term in 1532 displayed as a pandas df
display(pd.DataFrame(cal.calendrical_solar_terms(1532)))

             solar term    date
0                   Z12  Jan 12
1                    J1  Jan 27
2                    Z1  Feb 11
3                    J2  Feb 27
4    Z2 (March equinox)  Mar 13
5                    J3  Mar 28
6                    Z3  Apr 12
7                    J4  Apr 27
8                    Z4  May 13
9                    J5  May 28
10   Z5 (June solstice)  Jun 12
11                   J6  Jun 27
12                   Z6  Jul 12
13                   J7  Jul 28
14                   Z7  Aug 12
15                   J8  Aug 27
16    Z8 (Sep. equinox)  Sep 11
17                   J9  Sep 27
18                   Z9  Oct 12
19                  J10  Oct 27
20                  Z10  Nov 11
21                  J11  Nov 26
22  Z11 (Dec. solstice)  Dec 12
23                  J12  Dec 27

In [24]:
# calendrical solar terms for -106 (107 BCE)
display(pd.DataFrame(cal.calendrical_solar_terms(-106)))

             solar term    date
0                   J12   Jan 9
1                   Z12  Jan 24
2                    J1   Feb 8
3                    Z1  Feb 24
4                    J2  Mar 11
5    Z2 (March equinox)  Mar 26
6                    J3  Apr 10
7                    Z3  Apr 26
8                    J4  May 11
9                    Z4  May 26
10                   J5  Jun 10
11   Z5 (June solstice)  Jun 25
12                   J6  Jul 11
13                   Z6  Jul 26
14                   J7  Aug 10
15                   Z7  Aug 25
16                   J8   Sep 9
17    Z8 (Sep. equinox)  Sep 25
18                   J9  Oct 10
19                   Z9  Oct 25
20                  J10   Nov 9
21                  Z10  Nov 25
22                  J11  Dec 10
23  Z11 (Dec. solstice)  Dec 25

Calendrical solar terms in a Chinese year can be obtained using the method `.chinese_year_info(y)` or `.chinese_year_html(y)` shown above.

## Go Deeper

The above summarizes the basic usage of this package. To learn more about the detail of each command, look at our tutorial and examples of using the commands to perform more complicated calendar calculations.