# 進階指引

此進階指引深入解釋軟體套件提供的基本函數，建議讀者先按照入門指南試用這些函數，才來看此進階指引，入門指南舉的例子不會有此重複。

## 安裝

用以下`pip`措令安裝及更新軟體套件。.

In [1]:
#取消註解字串#來執行措令
#pip install --upgrade ChineseCalendar_py

## 載入軟體套件

In [2]:
import ChineseCalendar_py.calendar_conversion as ccal
from IPython.display import HTML
import pandas as pd

用以下指令建立中曆物件實例。輸入參數`'ChiT'`表示函數的輸出的語言是傳統中文，其他兩個可用的參數是`'Eng'`(英文)及`'ChiS'`(簡體中文)。

In [3]:
cal = ccal.calendar_conversion('ChiT')

## 預設中曆及其他支持的中曆

中國有時處於分裂局面，各政權行用不同的曆法，本軟體在分裂時代提供多部（但非全部）同時行用的曆法。

為免混亂，如果用者沒有指明用某一特定曆法，本軟體在中國分裂時代選取了一套曆法，稱為「預設中曆」。預設中曆在春秋時代用魯國曆法（春秋曆），戰國時代用周朝曆法，三國時代用魏國曆法，東晉南北朝用南朝（東晉、宋、齊、梁、陳）曆法，五代十國用北朝（梁、唐、晉、漢、周）曆法，宋、遼、金、蒙古時期用宋朝曆法，南明、明鄭、清時期用清朝曆法，詳情可參閱[預設中曆網頁](https://ytliu0.github.io/ChineseCalendar-python/tutorial/traditional_Chinese/default_calendar.html)，預設中曆的年限是-721年至2200年。

如[預設中曆網頁](https://ytliu0.github.io/ChineseCalendar-python/tutorial/traditional_Chinese/default_calendar.html)所述，-103年至2200年的中曆用查表法獲取，這段時期中曆的朔閏及曆書節氣數據存於源碼文件夾'src/ChineseCalendar_py/'的'default_calendar_M105_2201.csv'檔案中，曆日以距公曆年1月0日的日數表示。當中曆物件實例建立時，檔案中的朔閏數據載入 numpy array `.calData`，曆書節氣數據載入 numpy array `.calSterm`。在這資料夾的日曆計算習題 notebook 中會有實例展示這兩個 numpy array 在某些計算上很有用。為了方便計算日曆，這兩個 numpy array 的曆日資料其實涵蓋-105年至2202年。

除了預設中曆外，本軟體還提供一些其他的中曆，詳情可參閱[其他中曆網頁](https://ytliu0.github.io/ChineseCalendar-python/tutorial/traditional_Chinese/available_calendars.html)。網頁中列出的所有中曆都有行用年份，大多數中曆用其曆法法則計算，原則上可用於行用年份之外，但這裡極不鼓勵用者如此做。

## 公曆轉中曆

本軟體套件提供下列三個函數轉公曆為中曆：

- `.western_to_chinese_date(y, m, d, calendar='default', multiple_calendars=False, ephemeris='None')`: 公曆日期(年 = y, 月 = m, 日 = d)轉中曆日期。

- `.western_to_chinese_year(y, m=None, calendar='default', ephemeris='None')`: 公曆 y 年 m 月 中所有日期轉為中曆日期。如果 m 是 None，則將公曆年 y 中所有日期轉為中曆日期。

- `.western_to_chinese_year_html(y, m=None, calendar='default', showJDN=False, ephemeris='None', show_chinese_year_info=True,show_chinese_calendar_info=True)`: 與函數`.western_to_chinese_year(y, m=None, calendar='default', ephemeris='None')`的功能一樣，但會輸出 HTML 格式的文字。

`calendar`參數用來選取某中曆，默認值是'default'，表示預設中曆，用者可選擇[其他中曆網頁](https://ytliu0.github.io/ChineseCalendar-python/tutorial/traditional_Chinese/available_calendars.html)列出的中曆標記選擇其他中曆。

`multiple_calendars`參數只有當`calendar`參數是'default'(預設中曆)時才有作用。如果`multiple_calendars`設定為`True`，分裂時代的輸出中曆會列出多個當時行用的中曆。

`ephemeris`參數讓用者選擇用哪個現代曆表計算月相和節氣時刻，這裡只支持'DE431'和'DE441'，默認值是'None'，表示會用已設定的曆表，如果還未設定曆表，則用默認值'DE441'。

以下指令轉公曆445年2月25日為北魏行用的曆法。根據[其他中曆網頁](https://ytliu0.github.io/ChineseCalendar-python/tutorial/traditional_Chinese/available_calendars.html)，北魏的日曆要用 'WeiZhouSui' 標記。

In [4]:
cal.western_to_chinese_date(445, 2, 25, calendar='WeiZhouSui')

{'Western ymd': [445, 2, 25],
 'Western calendar': '儒略曆',
 'JDN': 1883650,
 'Chinese ymd': [445, -1, 3],
 'cyear': 445,
 'cdate': '閏正月初三',
 'sexagenary year': ['乙酉', '雞', 22],
 'Nday_cmonth': 29,
 'sexagenary date': ['癸亥', 60],
 'Week': ['星期日', 0],
 'period': '南北朝 (420 - 580)',
 'reign/era': '北魏太武帝太平真君六年',
 'Chinese calendar': '景初曆'}

函數輸出顯示公曆445年2月25日，在北魏的日曆是太武帝太平真君六年閏正月初三，年干支是乙酉、日干支是癸亥，當時北魏行用的曆法是景初曆。

此函數的輸出是 python dictionary，有下列的字典鍵(keys):

`'Western ymd'`: python list 包含公曆的年月日。

`'Western calendar'`: 公曆版本 (格里曆、儒略曆或逆推儒略曆)。

`'JDN'`: 正午儒略日數。

`'Chinese ymd'`: 包含中曆的年月日，閏月的月份用負數表示。 

`'cyear'`: 與中曆年日期重疊最多的公曆年份，也是`'Chinese ymd'` list 中第一個數字。此例的太平真君六年就是445年，因為太平真君六年始於445年1月24日，終於446年2月11日，太平真君六年與公曆445年有342日重疊，是重疊日數最多的公曆年，因此甲辰年的`'cyear'`取445。

`'cdate'`: 中曆日期。

`'sexagenary year'`: python list 顯示年干支，年地支對應的生肖，及干支數 (1=甲子，2＝乙丑，3＝丙寅等，六十干支的干支數可參閱[干支網頁](https://ytliu0.github.io/ChineseCalendar/sexagenary_chinese.html)的表二) 。

`'jian'`: 中曆月的月建干支，月干支的詳情可參閱[干支網頁](https://ytliu0.github.io/ChineseCalendar/sexagenary_chinese.html)。

`'Nday_cmonth'`: 中曆月的日數，一般是29日或30日。

`'sexagenary date'`: 日干支及其干支數，日干支的詳情參閱[干支網頁](https://ytliu0.github.io/ChineseCalendar/sexagenary_chinese.html)。

`'Week'`: 星期及星期數，星期數用 0、1、2、3、4、5、6 表示星期日、一、二、三、四、五、六。 

`'period'`: 中國歷史的時代。

`'Chinese calendar'`: 中曆的版本。

與我的[農曆網站](https://ytliu0.github.io/ChineseCalendar/index_chinese.html)一樣，公曆年 y 的年限是 -721 至 2200。當中國處於分裂時代時常有多個曆法同時使用，這裡用的指令只提供其中一個版本，其他版本的日期也可以獲取，方法是選'calendar'參數為'default'及'multiple_calendars'為True:

In [5]:
cal.western_to_chinese_date(445, 2, 25, multiple_calendars=True)

[{'Western ymd': [445, 2, 25],
  'Western calendar': '儒略曆',
  'JDN': 1883650,
  'Chinese ymd': [445, 2, 3],
  'cyear': 445,
  'cdate': '二月初三',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建己卯', 16],
  'Nday_cmonth': 29,
  'sexagenary date': ['癸亥', 60],
  'Week': ['星期日', 0],
  'period': '南北朝 (420 - 580)',
  'reign/era': '宋文帝元嘉二十二年',
  'Chinese calendar': '元嘉曆'},
 {'Western ymd': [445, 2, 25],
  'Western calendar': '儒略曆',
  'JDN': 1883650,
  'Chinese ymd': [445, -1, 3],
  'cyear': 445,
  'cdate': '閏正月初三',
  'sexagenary year': ['乙酉', '雞', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['癸亥', 60],
  'Week': ['星期日', 0],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'}]

此輸出顯示公曆445年2月25日在劉宋的曆法是文帝元嘉二十二年二月初三，當時宋朝行用的曆法是元嘉曆，此日期就是預設中曆輸出的日期。

指令`cal.western_to_chinese_year(445, 2, calendar='WeiZhouSui')`輸出 python list 包含公曆445年2月對應的北魏曆法日期；`cal.western_to_chinese_year(445, calendar='WeiZhouSui')` 則輸出 python list 包含公曆445年全年對應的北魏曆法日期。

In [6]:
cal.western_to_chinese_year(445, 2, calendar='WeiZhouSui')

[{'Western ymd': [445, 2, 1],
  'Western calendar': '儒略曆',
  'JDN': 1883626,
  'Chinese ymd': [445, 1, 9],
  'cyear': 445,
  'cdate': '正月初九',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['己亥', 36],
  'Week': ['星期四', 4],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 2],
  'Western calendar': '儒略曆',
  'JDN': 1883627,
  'Chinese ymd': [445, 1, 10],
  'cyear': 445,
  'cdate': '正月初十',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚子', 37],
  'Week': ['星期五', 5],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 3],
  'Western calendar': '儒略曆',
  'JDN': 1883628,
  'Chinese ymd': [445, 1, 11],
  'cyear': 445,
  'cdate': '正月十一',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛丑', 38],
  'Week': ['星期六', 6],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 4],
  'Western calendar': '儒略曆',
  'JDN': 1883629,
  'Chinese ymd': [445, 1, 12],
  'cyear': 445,
  'cdate': '正月十二',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['壬寅', 39],
  'Week': ['星期日', 0],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 5],
  'Western calendar': '儒略曆',
  'JDN': 1883630,
  'Chinese ymd': [445, 1, 13],
  'cyear': 445,
  'cdate': '正月十三',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['癸卯', 40],
  'Week': ['星期一', 1],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 6],
  'Western calendar': '儒略曆',
  'JDN': 1883631,
  'Chinese ymd': [445, 1, 14],
  'cyear': 445,
  'cdate': '正月十四',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['甲辰', 41],
  'Week': ['星期二', 2],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 7],
  'Western calendar': '儒略曆',
  'JDN': 1883632,
  'Chinese ymd': [445, 1, 15],
  'cyear': 445,
  'cdate': '正月十五',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['乙巳', 42],
  'Week': ['星期三', 3],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 8],
  'Western calendar': '儒略曆',
  'JDN': 1883633,
  'Chinese ymd': [445, 1, 16],
  'cyear': 445,
  'cdate': '正月十六',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['丙午', 43],
  'Week': ['星期四', 4],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 9],
  'Western calendar': '儒略曆',
  'JDN': 1883634,
  'Chinese ymd': [445, 1, 17],
  'cyear': 445,
  'cdate': '正月十七',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁未', 44],
  'Week': ['星期五', 5],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 10],
  'Western calendar': '儒略曆',
  'JDN': 1883635,
  'Chinese ymd': [445, 1, 18],
  'cyear': 445,
  'cdate': '正月十八',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊申', 45],
  'Week': ['星期六', 6],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 11],
  'Western calendar': '儒略曆',
  'JDN': 1883636,
  'Chinese ymd': [445, 1, 19],
  'cyear': 445,
  'cdate': '正月十九',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['己酉', 46],
  'Week': ['星期日', 0],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 12],
  'Western calendar': '儒略曆',
  'JDN': 1883637,
  'Chinese ymd': [445, 1, 20],
  'cyear': 445,
  'cdate': '正月二十',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚戌', 47],
  'Week': ['星期一', 1],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 13],
  'Western calendar': '儒略曆',
  'JDN': 1883638,
  'Chinese ymd': [445, 1, 21],
  'cyear': 445,
  'cdate': '正月廿一',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛亥', 48],
  'Week': ['星期二', 2],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 14],
  'Western calendar': '儒略曆',
  'JDN': 1883639,
  'Chinese ymd': [445, 1, 22],
  'cyear': 445,
  'cdate': '正月廿二',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['壬子', 49],
  'Week': ['星期三', 3],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 15],
  'Western calendar': '儒略曆',
  'JDN': 1883640,
  'Chinese ymd': [445, 1, 23],
  'cyear': 445,
  'cdate': '正月廿三',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['癸丑', 50],
  'Week': ['星期四', 4],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 16],
  'Western calendar': '儒略曆',
  'JDN': 1883641,
  'Chinese ymd': [445, 1, 24],
  'cyear': 445,
  'cdate': '正月廿四',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['甲寅', 51],
  'Week': ['星期五', 5],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 17],
  'Western calendar': '儒略曆',
  'JDN': 1883642,
  'Chinese ymd': [445, 1, 25],
  'cyear': 445,
  'cdate': '正月廿五',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['乙卯', 52],
  'Week': ['星期六', 6],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 18],
  'Western calendar': '儒略曆',
  'JDN': 1883643,
  'Chinese ymd': [445, 1, 26],
  'cyear': 445,
  'cdate': '正月廿六',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['丙辰', 53],
  'Week': ['星期日', 0],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 19],
  'Western calendar': '儒略曆',
  'JDN': 1883644,
  'Chinese ymd': [445, 1, 27],
  'cyear': 445,
  'cdate': '正月廿七',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁巳', 54],
  'Week': ['星期一', 1],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 20],
  'Western calendar': '儒略曆',
  'JDN': 1883645,
  'Chinese ymd': [445, 1, 28],
  'cyear': 445,
  'cdate': '正月廿八',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊午', 55],
  'Week': ['星期二', 2],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 21],
  'Western calendar': '儒略曆',
  'JDN': 1883646,
  'Chinese ymd': [445, 1, 29],
  'cyear': 445,
  'cdate': '正月廿九',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['己未', 56],
  'Week': ['星期三', 3],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 22],
  'Western calendar': '儒略曆',
  'JDN': 1883647,
  'Chinese ymd': [445, 1, 30],
  'cyear': 445,
  'cdate': '正月三十',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚申', 57],
  'Week': ['星期四', 4],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 23],
  'Western calendar': '儒略曆',
  'JDN': 1883648,
  'Chinese ymd': [445, -1, 1],
  'cyear': 445,
  'cdate': '閏正月初一',
  'sexagenary year': ['乙酉', '雞', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['辛酉', 58],
  'Week': ['星期五', 5],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 24],
  'Western calendar': '儒略曆',
  'JDN': 1883649,
  'Chinese ymd': [445, -1, 2],
  'cyear': 445,
  'cdate': '閏正月初二',
  'sexagenary year': ['乙酉', '雞', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['壬戌', 59],
  'Week': ['星期六', 6],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 25],
  'Western calendar': '儒略曆',
  'JDN': 1883650,
  'Chinese ymd': [445, -1, 3],
  'cyear': 445,
  'cdate': '閏正月初三',
  'sexagenary year': ['乙酉', '雞', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['癸亥', 60],
  'Week': ['星期日', 0],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 26],
  'Western calendar': '儒略曆',
  'JDN': 1883651,
  'Chinese ymd': [445, -1, 4],
  'cyear': 445,
  'cdate': '閏正月初四',
  'sexagenary year': ['乙酉', '雞', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['甲子', 1],
  'Week': ['星期一', 1],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 27],
  'Western calendar': '儒略曆',
  'JDN': 1883652,
  'Chinese ymd': [445, -1, 5],
  'cyear': 445,
  'cdate': '閏正月初五',
  'sexagenary year': ['乙酉', '雞', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['乙丑', 2],
  'Week': ['星期二', 2],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 28],
  'Western calendar': '儒略曆',
  'JDN': 1883653,
  'Chinese ymd': [445, -1, 6],
  'cyear': 445,
  'cdate': '閏正月初六',
  'sexagenary year': ['乙酉', '雞', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['丙寅', 3],
  'Week': ['星期三', 3],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'}]

以上的輸出如果用於其後的日曆計算或許有用，但對於瀏覽來說並不是很方便，函數`.western_to_chinese_year_html()`輸出的 HTML 文字用`IPython.display.HTML()`的函數處理後，就會得到如[這農曆網頁](https://ytliu0.github.io/ChineseCalendar/index_chinese.html)的表列顯示，比較方便瀏覽。

In [7]:
# 公曆445年2月與北魏日曆對照
HTML(cal.western_to_chinese_year_html(445, 2, calendar='WeiZhouSui'))

In [8]:
# 顯示445年2月的北魏月曆，並顯示每日的正午儒略日數。
HTML(cal.western_to_chinese_year_html(445, 2, calendar='WeiZhouSui', showJDN=True))

上面列出的月相和二十四節氣如[農曆網站](https://ytliu0.github.io/ChineseCalendar/index_chinese.html)的一樣是指用現代方法以噴射推進實驗室的 DE441 曆表算出，而曆書節氣指按當時中國曆法算出的節氣日期。

中國科學院紫金山天文臺從 2014年起用 DE421 曆表編算天文年曆，直至2025年還沒有更新曆表，不過 DE421 算出的月相和節氣時刻與 DE431/DE441 在現代相差甚微。所有用現代曆表算出的月相和節氣時刻都用東八區時間 UT+8 (UT 在1972年前指 UT1， 1972年到今年指 UTC，未來年份則是預推的 UTC)。

In [9]:
# 用國標 《農曆的編算和頒行》 GB/T 33661-2017 算出的2500年年曆
HTML(cal.western_to_chinese_year_html(2500, calendar='GBT'))

## 中曆轉公曆

本軟體提供以下四個函數可用來轉中曆為公曆：

`.chinese_to_western_date(y, m, d, calendar='default', ephemeris='None')`: 轉中曆年月日 y, m, d 為公曆日期，閏月的 m 值為負數。

`.chinese_year_info(y, calendar='default', ephemeris='None')`: 函數輸出中曆年 y 的所有中曆月初一的公曆日期，曆書節氣，及用現代曆表 (DE431 或 DE441) 算出的節氣。

`.chinese_year_html(y, calendar='default', ephemeris='None')`: 與上述函數的功能一致，但輸出 HTML 文字。

`.chinese_to_western_year(y, m=None, calendar='default', ephemeris='None')`: 列出中曆年 y 中曆月 m 所有日期的公曆日期。如果 m 是 None，則列出中曆年全年的公曆日期。

`chinese_to_western_year_html(y, m=None, calendar='default', showJDN=False, ephemeris='None', show_chinese_year_info=True, show_chinese_calendar_info=True)`: 與上述函數的功能一致，但輸出 HTML 文字。

我的[農曆網站](https://ytliu0.github.io/ChineseCalendar/index_chinese.html) 並沒有網頁列出這些函數提供的公曆資料，[朔閏表網頁](https://ytliu0.github.io/ChineseCalendar/table_chinese.html)提供與`.chinese_year_html()`函數相近的資料。

這些函數的用法與公曆轉中曆的函數接近，茲舉例展示。

In [10]:
# 轉南明永曆十五年(1661年)八月十五日為公曆
cal.chinese_to_western_date(1661, 8, 15, calendar='SouthernMing')

{'Chinese ymd': [1661, 8, 15],
 'Western ymd': [1661, 9, 8],
 'Western calendar': '格里曆',
 'JDN': 2327979,
 'cyear': 1661,
 'cdate': '八月十五',
 'sexagenary year': ['辛丑', '牛', 38],
 'jian': ['建丁酉', 34],
 'Nday_cmonth': 29,
 'sexagenary date': ['壬辰', 29],
 'Week': ['星期四', 4],
 'period': '清 (1645 - 1911)',
 'reign/era': '南明永曆十五年',
 'Chinese calendar': '殘明大統曆'}

輸出顯示公曆日期是1661年9月8日。注意南明的八月十五在這年與清朝時憲曆不一致，清世祖順治十八年八月十五在1661年10月7日，可用`cal.chinese_to_western_date(1661, 8, 15)`驗證。

歷代中國因曆法改革有時會出現中曆日期對應兩個公曆日期的情況，例如762年的五月十二日：

In [11]:
cal.chinese_to_western_date(762, 5, 12)

[{'Chinese ymd': [762, 5, 12],
  'Western ymd': [762, 4, 10],
  'Western calendar': '儒略曆',
  'JDN': 1999478,
  'cyear': 762,
  'cdate': '五月十二',
  'sexagenary year': ['壬寅', '虎', 39],
  'jian': ['建甲辰', 41],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛卯', 28],
  'Week': ['星期六', 6],
  'period': '唐 (618 - 907)',
  'reign/era': '唐肅宗上元三年/寶應元年',
  'Chinese calendar': '五紀曆'},
 {'Chinese ymd': [762, 5, 12],
  'Western ymd': [762, 6, 8],
  'Western calendar': '儒略曆',
  'JDN': 1999537,
  'cyear': 762,
  'cdate': '五月十二',
  'sexagenary year': ['壬寅', '虎', 39],
  'jian': ['建丙午', 43],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚寅', 27],
  'Week': ['星期二', 2],
  'period': '唐 (618 - 907)',
  'reign/era': '唐肅宗上元三年/寶應元年',
  'Chinese calendar': '五紀曆'}]

以下指令顯示顓頊曆-250年(前251年)的曆日資料。

In [12]:
cal.chinese_year_info(-250, calendar='Zhuanxu')

{'cm': [{'cm': 10, 'JDN': 1629685, 'jian': 'NA', 'n': 29},
  {'cm': 11, 'JDN': 1629714, 'jian': 'NA', 'n': 30},
  {'cm': 12, 'JDN': 1629744, 'jian': 'NA', 'n': 29},
  {'cm': 1, 'JDN': 1629773, 'jian': 'NA', 'n': 30},
  {'cm': 2, 'JDN': 1629803, 'jian': 'NA', 'n': 29},
  {'cm': 3, 'JDN': 1629832, 'jian': 'NA', 'n': 30},
  {'cm': 4, 'JDN': 1629862, 'jian': 'NZ', 'n': 29},
  {'cm': 5, 'JDN': 1629891, 'jian': 'NA', 'n': 30},
  {'cm': 6, 'JDN': 1629921, 'jian': 'NA', 'n': 30},
  {'cm': 7, 'JDN': 1629951, 'jian': 'NA', 'n': 29},
  {'cm': 8, 'JDN': 1629980, 'jian': 'NA', 'n': 30},
  {'cm': 9, 'JDN': 1630010, 'jian': 'NA', 'n': 29},
  {'cm': -9, 'JDN': 1630039, 'jian': 'NA', 'n': 30}],
 'calendar': '顓頊曆',
 'reign/era': '秦昭襄王五十六年',
 'calst': [('J10', 1629693),
  ('Z10', 1629708),
  ('J11', 1629723),
  ('Z11', 1629739),
  ('J12', 1629754),
  ('Z12', 1629769),
  ('J1', 1629784),
  ('Z1', 1629799),
  ('J2', 1629815),
  ('Z2', 1629830),
  ('J3', 1629845),
  ('Z3', 1629860),
  ('J4', 1629876),
  ('Z4', 1629891),
  ('J5', 1629906),
  ('Z5', 1629921),
  ('J6', 1629936),
  ('Z6', 1629952),
  ('J7', 1629967),
  ('Z7', 1629982),
  ('J8', 1629997),
  ('Z8', 1630013),
  ('J9', 1630028),
  ('Z9', 1630043),
  ('J10', 1630058)],
 'datongST': [],
 'sterm': [['J10',
   {'event': '立冬',
    'year': -251,
    'month': 11,
    'date': 11,
    'hour': 0,
    'minute': 5,
    'dateString': '11月11日',
    'timeString': '00:05',
    'jd0_ut': 1629379.5,
    'jd1_ut': 314.6704472091856}],
  ['Z10',
   {'event': '小雪',
    'year': -251,
    'month': 11,
    'date': 25,
    'hour': 17,
    'minute': 2,
    'dateString': '11月25日',
    'timeString': '17:02',
    'jd0_ut': 1629379.5,
    'jd1_ut': 329.3761596532432}],
  ['J11',
   {'event': '大雪',
    'year': -251,
    'month': 12,
    'date': 10,
    'hour': 9,
    'minute': 34,
    'dateString': '12月10日',
    'timeString': '09:34',
    'jd0_ut': 1629379.5,
    'jd1_ut': 344.0652342350903}],
  ['Z11',
   {'event': '冬至',
    'year': -251,
    'month': 12,
    'date': 25,
    'hour': 2,
    'minute': 50,
    'dateString': '12月25日',
    'timeString': '02:50',
    'jd0_ut': 1629379.5,
    'jd1_ut': 358.78462715774}],
  ['J12',
   {'event': '小寒',
    'year': -250,
    'month': 1,
    'date': 8,
    'hour': 21,
    'minute': 19,
    'dateString': '1月8日',
    'timeString': '21:19',
    'jd0_ut': 1629744.5,
    'jd1_ut': 8.55491430365799}],
  ['Z12',
   {'event': '大寒',
    'year': -250,
    'month': 1,
    'date': 23,
    'hour': 18,
    'minute': 3,
    'dateString': '1月23日',
    'timeString': '18:03',
    'jd0_ut': 1629744.5,
    'jd1_ut': 23.418670915664787}],
  ['J1',
   {'event': '立春',
    'year': -250,
    'month': 2,
    'date': 7,
    'hour': 17,
    'minute': 18,
    'dateString': '2月7日',
    'timeString': '17:18',
    'jd0_ut': 1629744.5,
    'jd1_ut': 38.387677983639044}],
  ['Z1',
   {'event': '雨水',
    'year': -250,
    'month': 2,
    'date': 22,
    'hour': 19,
    'minute': 49,
    'dateString': '2月22日',
    'timeString': '19:49',
    'jd0_ut': 1629744.5,
    'jd1_ut': 53.49231758221474}],
  ['J2',
   {'event': '驚蟄',
    'year': -250,
    'month': 3,
    'date': 10,
    'hour': 1,
    'minute': 30,
    'dateString': '3月10日',
    'timeString': '01:30',
    'jd0_ut': 1629744.5,
    'jd1_ut': 68.7294830296245}],
  ['Z2',
   {'event': '春分',
    'year': -250,
    'month': 3,
    'date': 25,
    'hour': 10,
    'minute': 39,
    'dateString': '3月25日',
    'timeString': '10:39',
    'jd0_ut': 1629744.5,
    'jd1_ut': 84.11076204636416}],
  ['J3',
   {'event': '清明',
    'year': -250,
    'month': 4,
    'date': 9,
    'hour': 22,
    'minute': 47,
    'dateString': '4月9日',
    'timeString': '22:47',
    'jd0_ut': 1629744.5,
    'jd1_ut': 99.61585250099941}],
  ['Z3',
   {'event': '穀雨',
    'year': -250,
    'month': 4,
    'date': 25,
    'hour': 13,
    'minute': 37,
    'dateString': '4月25日',
    'timeString': '13:37',
    'jd0_ut': 1629744.5,
    'jd1_ut': 115.23425344113146}],
  ['J4',
   {'event': '立夏',
    'year': -250,
    'month': 5,
    'date': 11,
    'hour': 6,
    'minute': 22,
    'dateString': '5月11日',
    'timeString': '06:22',
    'jd0_ut': 1629744.5,
    'jd1_ut': 130.93199232680843}],
  ['Z4',
   {'event': '小滿',
    'year': -250,
    'month': 5,
    'date': 27,
    'hour': 0,
    'minute': 18,
    'dateString': '5月27日',
    'timeString': '00:18',
    'jd0_ut': 1629744.5,
    'jd1_ut': 146.6792014152924}],
  ['J5',
   {'event': '芒種',
    'year': -250,
    'month': 6,
    'date': 11,
    'hour': 18,
    'minute': 30,
    'dateString': '6月11日',
    'timeString': '18:30',
    'jd0_ut': 1629744.5,
    'jd1_ut': 162.43783074815417}],
  ['Z5',
   {'event': '夏至',
    'year': -250,
    'month': 6,
    'date': 27,
    'hour': 12,
    'minute': 1,
    'dateString': '6月27日',
    'timeString': '12:01',
    'jd0_ut': 1629744.5,
    'jd1_ut': 178.16723182187786}],
  ['J6',
   {'event': '小暑',
    'year': -250,
    'month': 7,
    'date': 13,
    'hour': 4,
    'minute': 5,
    'dateString': '7月13日',
    'timeString': '04:05',
    'jd0_ut': 1629744.5,
    'jd1_ut': 193.83693906002978}],
  ['Z6',
   {'event': '大暑',
    'year': -250,
    'month': 7,
    'date': 28,
    'hour': 17,
    'minute': 47,
    'dateString': '7月28日',
    'timeString': '17:47',
    'jd0_ut': 1629744.5,
    'jd1_ut': 209.40776681216443}],
  ['J7',
   {'event': '立秋',
    'year': -250,
    'month': 8,
    'date': 13,
    'hour': 4,
    'minute': 47,
    'dateString': '8月13日',
    'timeString': '04:47',
    'jd0_ut': 1629744.5,
    'jd1_ut': 224.86590666054565}],
  ['Z7',
   {'event': '處暑',
    'year': -250,
    'month': 8,
    'date': 28,
    'hour': 12,
    'minute': 26,
    'dateString': '8月28日',
    'timeString': '12:26',
    'jd0_ut': 1629744.5,
    'jd1_ut': 240.1844070460951}],
  ['J8',
   {'event': '白露',
    'year': -250,
    'month': 9,
    'date': 12,
    'hour': 16,
    'minute': 53,
    'dateString': '9月12日',
    'timeString': '16:53',
    'jd0_ut': 1629744.5,
    'jd1_ut': 255.37026374160808}],
  ['Z8',
   {'event': '秋分',
    'year': -250,
    'month': 9,
    'date': 27,
    'hour': 17,
    'minute': 56,
    'dateString': '9月27日',
    'timeString': '17:56',
    'jd0_ut': 1629744.5,
    'jd1_ut': 270.41405366707596}],
  ['J9',
   {'event': '寒露',
    'year': -250,
    'month': 10,
    'date': 12,
    'hour': 16,
    'minute': 13,
    'dateString': '10月12日',
    'timeString': '16:13',
    'jd0_ut': 1629744.5,
    'jd1_ut': 285.3420372582834}],
  ['Z9',
   {'event': '霜降',
    'year': -250,
    'month': 10,
    'date': 27,
    'hour': 11,
    'minute': 52,
    'dateString': '10月27日',
    'timeString': '11:52',
    'jd0_ut': 1629744.5,
    'jd1_ut': 300.1611619608815}],
  ['J10',
   {'event': '立冬',
    'year': -250,
    'month': 11,
    'date': 11,
    'hour': 5,
    'minute': 53,
    'dateString': '11月11日',
    'timeString': '05:53',
    'jd0_ut': 1629744.5,
    'jd1_ut': 314.91179084995105}]],
 'mphase': [['Q0',
   {'event': '朔',
    'year': -251,
    'month': 11,
    'date': 1,
    'hour': 8,
    'minute': 6,
    'dateString': '11月1日',
    'timeString': '08:06',
    'jd0_ut': 1629379.5,
    'jd1_ut': 305.0041343972275}],
  ['Q1',
   {'event': '上弦',
    'year': -251,
    'month': 11,
    'date': 8,
    'hour': 10,
    'minute': 56,
    'dateString': '11月8日',
    'timeString': '10:56',
    'jd0_ut': 1629379.5,
    'jd1_ut': 312.1222598391197}],
  ['Q2',
   {'event': '望',
    'year': -251,
    'month': 11,
    'date': 15,
    'hour': 8,
    'minute': 17,
    'dateString': '11月15日',
    'timeString': '08:17',
    'jd0_ut': 1629379.5,
    'jd1_ut': 319.0115389188933}],
  ['Q3',
   {'event': '下弦',
    'year': -251,
    'month': 11,
    'date': 23,
    'hour': 5,
    'minute': 21,
    'dateString': '11月23日',
    'timeString': '05:21',
    'jd0_ut': 1629379.5,
    'jd1_ut': 326.88970718156435}],
  ['Q0',
   {'event': '朔',
    'year': -251,
    'month': 11,
    'date': 30,
    'hour': 22,
    'minute': 54,
    'dateString': '11月30日',
    'timeString': '22:54',
    'jd0_ut': 1629379.5,
    'jd1_ut': 334.6209143938907}],
  ['Q1',
   {'event': '上弦',
    'year': -251,
    'month': 12,
    'date': 7,
    'hour': 18,
    'minute': 57,
    'dateString': '12月7日',
    'timeString': '18:57',
    'jd0_ut': 1629379.5,
    'jd1_ut': 341.45595795450066}],
  ['Q2',
   {'event': '望',
    'year': -251,
    'month': 12,
    'date': 15,
    'hour': 0,
    'minute': 1,
    'dateString': '12月15日',
    'timeString': '00:01',
    'jd0_ut': 1629379.5,
    'jd1_ut': 348.66701798969905,
    'eclipse': '月全食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=-299&ind=111&DE=441&shrule=revised_Danjon&ref=python'}],
  ['Q3',
   {'event': '下弦',
    'year': -251,
    'month': 12,
    'date': 23,
    'hour': 2,
    'minute': 56,
    'dateString': '12月23日',
    'timeString': '02:56',
    'jd0_ut': 1629379.5,
    'jd1_ut': 356.78880866201763}],
  ['Q0',
   {'event': '朔',
    'year': -251,
    'month': 12,
    'date': 30,
    'hour': 11,
    'minute': 58,
    'dateString': '12月30日',
    'timeString': '11:58',
    'jd0_ut': 1629379.5,
    'jd1_ut': 364.16504390002854,
    'eclipse': '日偏食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=-299&ind=109&DE=441&ref=python'}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 1,
    'date': 6,
    'hour': 3,
    'minute': 39,
    'dateString': '1月6日',
    'timeString': '03:39',
    'jd0_ut': 1629744.5,
    'jd1_ut': 5.819029870415639}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 1,
    'date': 13,
    'hour': 17,
    'minute': 36,
    'dateString': '1月13日',
    'timeString': '17:36',
    'jd0_ut': 1629744.5,
    'jd1_ut': 13.39999685301384}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 1,
    'date': 21,
    'hour': 22,
    'minute': 11,
    'dateString': '1月21日',
    'timeString': '22:11',
    'jd0_ut': 1629744.5,
    'jd1_ut': 21.590943639094064}],
  ['Q0',
   {'event': '朔',
    'year': -250,
    'month': 1,
    'date': 28,
    'hour': 23,
    'minute': 0,
    'dateString': '1月28日',
    'timeString': '23:00',
    'jd0_ut': 1629744.5,
    'jd1_ut': 28.62511018926719}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 2,
    'date': 4,
    'hour': 13,
    'minute': 57,
    'dateString': '2月4日',
    'timeString': '13:57',
    'jd0_ut': 1629744.5,
    'jd1_ut': 35.248244974440716}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 2,
    'date': 12,
    'hour': 11,
    'minute': 42,
    'dateString': '2月12日',
    'timeString': '11:42',
    'jd0_ut': 1629744.5,
    'jd1_ut': 43.1539226501219}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 2,
    'date': 20,
    'hour': 13,
    'minute': 50,
    'dateString': '2月20日',
    'timeString': '13:50',
    'jd0_ut': 1629744.5,
    'jd1_ut': 51.243159231803915}],
  ['Q0',
   {'event': '朔',
    'year': -250,
    'month': 2,
    'date': 27,
    'hour': 8,
    'minute': 12,
    'dateString': '2月27日',
    'timeString': '08:12',
    'jd0_ut': 1629744.5,
    'jd1_ut': 58.00831229267649}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 3,
    'date': 6,
    'hour': 2,
    'minute': 19,
    'dateString': '3月6日',
    'timeString': '02:19',
    'jd0_ut': 1629744.5,
    'jd1_ut': 64.76310972482588}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 3,
    'date': 14,
    'hour': 4,
    'minute': 57,
    'dateString': '3月14日',
    'timeString': '04:57',
    'jd0_ut': 1629744.5,
    'jd1_ut': 72.87275274832018}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 3,
    'date': 22,
    'hour': 1,
    'minute': 27,
    'dateString': '3月22日',
    'timeString': '01:27',
    'jd0_ut': 1629744.5,
    'jd1_ut': 80.72697818556273}],
  ['Q0',
   {'event': '朔',
    'year': -250,
    'month': 3,
    'date': 28,
    'hour': 16,
    'minute': 14,
    'dateString': '3月28日',
    'timeString': '16:14',
    'jd0_ut': 1629744.5,
    'jd1_ut': 87.34296210246426}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 4,
    'date': 4,
    'hour': 16,
    'minute': 39,
    'dateString': '4月4日',
    'timeString': '16:39',
    'jd0_ut': 1629744.5,
    'jd1_ut': 94.36054342231938}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 4,
    'date': 12,
    'hour': 20,
    'minute': 30,
    'dateString': '4月12日',
    'timeString': '20:30',
    'jd0_ut': 1629744.5,
    'jd1_ut': 102.52078782260928}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 4,
    'date': 20,
    'hour': 9,
    'minute': 23,
    'dateString': '4月20日',
    'timeString': '09:23',
    'jd0_ut': 1629744.5,
    'jd1_ut': 110.05782797604088}],
  ['Q0',
   {'event': '朔',
    'year': -250,
    'month': 4,
    'date': 27,
    'hour': 0,
    'minute': 6,
    'dateString': '4月27日',
    'timeString': '00:06',
    'jd0_ut': 1629744.5,
    'jd1_ut': 116.67084100248293}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 5,
    'date': 4,
    'hour': 8,
    'minute': 30,
    'dateString': '5月4日',
    'timeString': '08:30',
    'jd0_ut': 1629744.5,
    'jd1_ut': 124.02091017236958}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 5,
    'date': 12,
    'hour': 10,
    'minute': 1,
    'dateString': '5月12日',
    'timeString': '10:01',
    'jd0_ut': 1629744.5,
    'jd1_ut': 132.0840138612833}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 5,
    'date': 19,
    'hour': 14,
    'minute': 42,
    'dateString': '5月19日',
    'timeString': '14:42',
    'jd0_ut': 1629744.5,
    'jd1_ut': 139.2792481594195}],
  ['Q0',
   {'event': '朔',
    'year': -250,
    'month': 5,
    'date': 26,
    'hour': 8,
    'minute': 51,
    'dateString': '5月26日',
    'timeString': '08:51',
    'jd0_ut': 1629744.5,
    'jd1_ut': 146.03554483990834,
    'eclipse': '日偏食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=-299&ind=110&DE=441&ref=python'}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 6,
    'date': 3,
    'hour': 1,
    'minute': 16,
    'dateString': '6月3日',
    'timeString': '01:16',
    'jd0_ut': 1629744.5,
    'jd1_ut': 153.7196359917709}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 6,
    'date': 10,
    'hour': 21,
    'minute': 32,
    'dateString': '6月10日',
    'timeString': '21:32',
    'jd0_ut': 1629744.5,
    'jd1_ut': 161.5636686405566,
    'eclipse': '月全食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=-299&ind=112&DE=441&shrule=revised_Danjon&ref=python'}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 6,
    'date': 17,
    'hour': 18,
    'minute': 52,
    'dateString': '6月17日',
    'timeString': '18:52',
    'jd0_ut': 1629744.5,
    'jd1_ut': 168.4529687332379}],
  ['Q0',
   {'event': '朔',
    'year': -250,
    'month': 6,
    'date': 24,
    'hour': 19,
    'minute': 20,
    'dateString': '6月24日',
    'timeString': '19:20',
    'jd0_ut': 1629744.5,
    'jd1_ut': 175.47245728683188,
    'eclipse': '日偏食',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=-299&ind=111&DE=441&ref=python'}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 7,
    'date': 2,
    'hour': 18,
    'minute': 25,
    'dateString': '7月2日',
    'timeString': '18:25',
    'jd0_ut': 1629744.5,
    'jd1_ut': 183.4338085121368}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 7,
    'date': 10,
    'hour': 7,
    'minute': 21,
    'dateString': '7月10日',
    'timeString': '07:21',
    'jd0_ut': 1629744.5,
    'jd1_ut': 190.97304356756078}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 7,
    'date': 16,
    'hour': 23,
    'minute': 34,
    'dateString': '7月16日',
    'timeString': '23:34',
    'jd0_ut': 1629744.5,
    'jd1_ut': 197.6484026479367}],
  ['Q0',
   {'event': '朔',
    'year': -250,
    'month': 7,
    'date': 24,
    'hour': 8,
    'minute': 4,
    'dateString': '7月24日',
    'timeString': '08:04',
    'jd0_ut': 1629744.5,
    'jd1_ut': 205.00300252383713}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 8,
    'date': 1,
    'hour': 11,
    'minute': 21,
    'dateString': '8月1日',
    'timeString': '11:21',
    'jd0_ut': 1629744.5,
    'jd1_ut': 213.13952120713364}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 8,
    'date': 8,
    'hour': 16,
    'minute': 6,
    'dateString': '8月8日',
    'timeString': '16:06',
    'jd0_ut': 1629744.5,
    'jd1_ut': 220.3375076847566}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 8,
    'date': 15,
    'hour': 6,
    'minute': 23,
    'dateString': '8月15日',
    'timeString': '06:23',
    'jd0_ut': 1629744.5,
    'jd1_ut': 226.93256639302703}],
  ['Q0',
   {'event': '朔',
    'year': -250,
    'month': 8,
    'date': 22,
    'hour': 23,
    'minute': 11,
    'dateString': '8月22日',
    'timeString': '23:11',
    'jd0_ut': 1629744.5,
    'jd1_ut': 234.63295465260558}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 8,
    'date': 31,
    'hour': 3,
    'minute': 22,
    'dateString': '8月31日',
    'timeString': '03:22',
    'jd0_ut': 1629744.5,
    'jd1_ut': 242.80667541271595}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 9,
    'date': 7,
    'hour': 0,
    'minute': 37,
    'dateString': '9月7日',
    'timeString': '00:37',
    'jd0_ut': 1629744.5,
    'jd1_ut': 249.69247580764429}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 9,
    'date': 13,
    'hour': 16,
    'minute': 36,
    'dateString': '9月13日',
    'timeString': '16:36',
    'jd0_ut': 1629744.5,
    'jd1_ut': 256.35852956699784}],
  ['Q0',
   {'event': '朔',
    'year': -250,
    'month': 9,
    'date': 21,
    'hour': 16,
    'minute': 26,
    'dateString': '9月21日',
    'timeString': '16:26',
    'jd0_ut': 1629744.5,
    'jd1_ut': 264.351088169005}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 9,
    'date': 29,
    'hour': 17,
    'minute': 39,
    'dateString': '9月29日',
    'timeString': '17:39',
    'jd0_ut': 1629744.5,
    'jd1_ut': 272.40199571417907}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 10,
    'date': 6,
    'hour': 9,
    'minute': 50,
    'dateString': '10月6日',
    'timeString': '09:50',
    'jd0_ut': 1629744.5,
    'jd1_ut': 279.0761177946032}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 10,
    'date': 13,
    'hour': 6,
    'minute': 52,
    'dateString': '10月13日',
    'timeString': '06:52',
    'jd0_ut': 1629744.5,
    'jd1_ut': 285.9525301161068}],
  ['Q0',
   {'event': '朔',
    'year': -250,
    'month': 10,
    'date': 21,
    'hour': 11,
    'minute': 0,
    'dateString': '10月21日',
    'timeString': '11:00',
    'jd0_ut': 1629744.5,
    'jd1_ut': 294.1246872114843}],
  ['Q1',
   {'event': '上弦',
    'year': -250,
    'month': 10,
    'date': 29,
    'hour': 5,
    'minute': 40,
    'dateString': '10月29日',
    'timeString': '05:40',
    'jd0_ut': 1629744.5,
    'jd1_ut': 301.9028073524435}],
  ['Q2',
   {'event': '望',
    'year': -250,
    'month': 11,
    'date': 4,
    'hour': 20,
    'minute': 26,
    'dateString': '11月4日',
    'timeString': '20:26',
    'jd0_ut': 1629744.5,
    'jd1_ut': 308.5181694842007}],
  ['Q3',
   {'event': '下弦',
    'year': -250,
    'month': 11,
    'date': 12,
    'hour': 0,
    'minute': 55,
    'dateString': '11月12日',
    'timeString': '00:55',
    'jd0_ut': 1629744.5,
    'jd1_ut': 315.7050755860644}]]}

此函數輸出 python dictionary，有以下字鍵：

`'cm'`: python list 含有以下中曆資料： \[{'cm':m1, 'JDN':JDN1, 'jian':'jian1', 'n':n1}, {'cm':m2, 'JDN':JDN2, 'jian':'jian2', 'n':n2}, ...\]，'cm' 表示中曆月序(負數表示閏月), 'JDN' 表示朔日的正午儒略日數， 'jian' 表示用月建來算的月干支數 ('jian'='1' 表示甲子，'2' 表示乙丑，⋯⋯，'60' 表示癸亥，'NA' 表示中曆月沒有月建，一般是閏月，但-103年以前的曆法因不用無中氣置閏也不列月建，'NZ' 表示此月不含中氣，這只適用於古六曆的月份)，'n' 表示中曆月的日數。 此 python list 以 'JDN' 的數值由小至大排序。

`'calendar'`: 中曆的版本 (例如 '三統曆'， '時憲曆' 等)。

`'reign/era'` (只適用於 1912年前的年份): 中曆年的年號或皇帝紀年。

`'calst'`: 曆書節氣 tuples \[(lab1, jdn1), (lab2, jdn2), ...\]， lab1, lab2, ... 是曆書節氣的標記，例如 'J1' 表示正月節(立春)，'Z4' 表示四月中(小滿) 等，jdn1, jdn2, ... 是曆書節氣的正午儒略日數。

`'datongST'` (只適用於預設中曆在1667至1669的中曆年): 用大統曆算出的節氣 \[(lab1, jdn1), (lab2, jdn2), ...\]。康熙六年(1667)至八年(1669)清朝因曆獄而復用明朝《大統曆》，但後來清朝欽天監編的《御定萬年書》試圖抹去這段歷史，用時憲曆追推這幾年的節氣，但臺灣國立故宮博物院的清代檔案檢索系統藏有這幾年的《大清七政經緯躔度時憲曆》，顯示這幾年的節氣日期確是符合大統曆的推算，而不符合時憲曆的推算，所以此處在這幾年列出大統曆的節氣。

`'sterm'`: python list \[\[lab1, info1\], \[lab2, info2\], ...\] 顯示用 DE431/DE441曆表算出的節氣，lab1, lab2, ... 為節氣標記，info1, info2, ... 則是 python dictionary，顯示節氣的日期及 UT+8 時刻。

`'mphase'`: python list \[\[lab1, info1\], \[lab2, info2\], ...\] 顯示用 DE431/DE441 曆表算出的中曆年內所有的月相資料。lab1, lab2, ... 是月相的標記： 'Q0' 是朔，'Q1' 是上弦，'Q2' 是望，'Q3' 是下弦。 info1, info2, ... 是 python dictionary，顯示月相的日期及 UT+8 時刻。

此函數輸出的 python list 不方便瀏覽， 函數 `.chinese_year_info_html()` 輸出 HTML 文字，可用 `IPython.display.HTML()` 函數將資料以表格形式顯示。

In [13]:
# 顓頊曆-250年(前251年)的曆日資料
HTML(cal.chinese_year_html(-250, calendar='Zhuanxu'))

In [14]:
# 用國標《農曆的編算與頒行》 GB/T 33661-2017 算出的2714年中曆
HTML(cal.chinese_year_html(2714, calendar='GBT'))

In [15]:
# 遼穆宗應曆五年(955年)八月的所有日期
cal.chinese_to_western_year(955, 8, calendar='LiaoJinYuan')

[{'Chinese ymd': [955, 8, 1],
  'Western ymd': [955, 8, 20],
  'Western calendar': '儒略曆',
  'JDN': 2070103,
  'cyear': 955,
  'cdate': '八月初一',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['丙申', 33],
  'Week': ['星期一', 1],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 2],
  'Western ymd': [955, 8, 21],
  'Western calendar': '儒略曆',
  'JDN': 2070104,
  'cyear': 955,
  'cdate': '八月初二',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁酉', 34],
  'Week': ['星期二', 2],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 3],
  'Western ymd': [955, 8, 22],
  'Western calendar': '儒略曆',
  'JDN': 2070105,
  'cyear': 955,
  'cdate': '八月初三',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊戌', 35],
  'Week': ['星期三', 3],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 4],
  'Western ymd': [955, 8, 23],
  'Western calendar': '儒略曆',
  'JDN': 2070106,
  'cyear': 955,
  'cdate': '八月初四',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['己亥', 36],
  'Week': ['星期四', 4],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 5],
  'Western ymd': [955, 8, 24],
  'Western calendar': '儒略曆',
  'JDN': 2070107,
  'cyear': 955,
  'cdate': '八月初五',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚子', 37],
  'Week': ['星期五', 5],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 6],
  'Western ymd': [955, 8, 25],
  'Western calendar': '儒略曆',
  'JDN': 2070108,
  'cyear': 955,
  'cdate': '八月初六',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛丑', 38],
  'Week': ['星期六', 6],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 7],
  'Western ymd': [955, 8, 26],
  'Western calendar': '儒略曆',
  'JDN': 2070109,
  'cyear': 955,
  'cdate': '八月初七',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['壬寅', 39],
  'Week': ['星期日', 0],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 8],
  'Western ymd': [955, 8, 27],
  'Western calendar': '儒略曆',
  'JDN': 2070110,
  'cyear': 955,
  'cdate': '八月初八',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['癸卯', 40],
  'Week': ['星期一', 1],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 9],
  'Western ymd': [955, 8, 28],
  'Western calendar': '儒略曆',
  'JDN': 2070111,
  'cyear': 955,
  'cdate': '八月初九',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['甲辰', 41],
  'Week': ['星期二', 2],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 10],
  'Western ymd': [955, 8, 29],
  'Western calendar': '儒略曆',
  'JDN': 2070112,
  'cyear': 955,
  'cdate': '八月初十',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['乙巳', 42],
  'Week': ['星期三', 3],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 11],
  'Western ymd': [955, 8, 30],
  'Western calendar': '儒略曆',
  'JDN': 2070113,
  'cyear': 955,
  'cdate': '八月十一',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['丙午', 43],
  'Week': ['星期四', 4],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 12],
  'Western ymd': [955, 8, 31],
  'Western calendar': '儒略曆',
  'JDN': 2070114,
  'cyear': 955,
  'cdate': '八月十二',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁未', 44],
  'Week': ['星期五', 5],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 13],
  'Western ymd': [955, 9, 1],
  'Western calendar': '儒略曆',
  'JDN': 2070115,
  'cyear': 955,
  'cdate': '八月十三',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊申', 45],
  'Week': ['星期六', 6],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 14],
  'Western ymd': [955, 9, 2],
  'Western calendar': '儒略曆',
  'JDN': 2070116,
  'cyear': 955,
  'cdate': '八月十四',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['己酉', 46],
  'Week': ['星期日', 0],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 15],
  'Western ymd': [955, 9, 3],
  'Western calendar': '儒略曆',
  'JDN': 2070117,
  'cyear': 955,
  'cdate': '八月十五',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚戌', 47],
  'Week': ['星期一', 1],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 16],
  'Western ymd': [955, 9, 4],
  'Western calendar': '儒略曆',
  'JDN': 2070118,
  'cyear': 955,
  'cdate': '八月十六',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛亥', 48],
  'Week': ['星期二', 2],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 17],
  'Western ymd': [955, 9, 5],
  'Western calendar': '儒略曆',
  'JDN': 2070119,
  'cyear': 955,
  'cdate': '八月十七',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['壬子', 49],
  'Week': ['星期三', 3],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 18],
  'Western ymd': [955, 9, 6],
  'Western calendar': '儒略曆',
  'JDN': 2070120,
  'cyear': 955,
  'cdate': '八月十八',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['癸丑', 50],
  'Week': ['星期四', 4],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 19],
  'Western ymd': [955, 9, 7],
  'Western calendar': '儒略曆',
  'JDN': 2070121,
  'cyear': 955,
  'cdate': '八月十九',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['甲寅', 51],
  'Week': ['星期五', 5],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 20],
  'Western ymd': [955, 9, 8],
  'Western calendar': '儒略曆',
  'JDN': 2070122,
  'cyear': 955,
  'cdate': '八月二十',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['乙卯', 52],
  'Week': ['星期六', 6],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 21],
  'Western ymd': [955, 9, 9],
  'Western calendar': '儒略曆',
  'JDN': 2070123,
  'cyear': 955,
  'cdate': '八月廿一',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['丙辰', 53],
  'Week': ['星期日', 0],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 22],
  'Western ymd': [955, 9, 10],
  'Western calendar': '儒略曆',
  'JDN': 2070124,
  'cyear': 955,
  'cdate': '八月廿二',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁巳', 54],
  'Week': ['星期一', 1],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 23],
  'Western ymd': [955, 9, 11],
  'Western calendar': '儒略曆',
  'JDN': 2070125,
  'cyear': 955,
  'cdate': '八月廿三',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊午', 55],
  'Week': ['星期二', 2],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 24],
  'Western ymd': [955, 9, 12],
  'Western calendar': '儒略曆',
  'JDN': 2070126,
  'cyear': 955,
  'cdate': '八月廿四',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['己未', 56],
  'Week': ['星期三', 3],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 25],
  'Western ymd': [955, 9, 13],
  'Western calendar': '儒略曆',
  'JDN': 2070127,
  'cyear': 955,
  'cdate': '八月廿五',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚申', 57],
  'Week': ['星期四', 4],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 26],
  'Western ymd': [955, 9, 14],
  'Western calendar': '儒略曆',
  'JDN': 2070128,
  'cyear': 955,
  'cdate': '八月廿六',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛酉', 58],
  'Week': ['星期五', 5],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 27],
  'Western ymd': [955, 9, 15],
  'Western calendar': '儒略曆',
  'JDN': 2070129,
  'cyear': 955,
  'cdate': '八月廿七',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['壬戌', 59],
  'Week': ['星期六', 6],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 28],
  'Western ymd': [955, 9, 16],
  'Western calendar': '儒略曆',
  'JDN': 2070130,
  'cyear': 955,
  'cdate': '八月廿八',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['癸亥', 60],
  'Week': ['星期日', 0],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 29],
  'Western ymd': [955, 9, 17],
  'Western calendar': '儒略曆',
  'JDN': 2070131,
  'cyear': 955,
  'cdate': '八月廿九',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['甲子', 1],
  'Week': ['星期一', 1],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 30],
  'Western ymd': [955, 9, 18],
  'Western calendar': '儒略曆',
  'JDN': 2070132,
  'cyear': 955,
  'cdate': '八月三十',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['乙丑', 2],
  'Week': ['星期二', 2],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'}]

In [16]:
# 遼穆宗應曆五年(955年)八月的 HTML 月曆表
HTML(cal.chinese_to_western_year_html(955, 8, calendar='LiaoJinYuan'))

`.western_to_chinese_year_html()`函數輸出的月相和節氣是公曆日期，此數輸出的則是中曆日期。

In [17]:
# 蜀後主延熙十七年(254年)的年曆表
HTML(cal.chinese_to_western_year_html(254, calendar='Shu'))

## 月相和二十四節氣

`ChineseCalendar_py.sunMoon.sunMoon` class 提供用現代曆表算出的月相和二十四節氣的 UT+8 日期和時刻，以下指令建立這 class 的實體。

In [18]:
sm = ccal.sunMoon.sunMoon('ChiT')

第一個輸入參數 'ChiT' 表示輸出的語言是傳統中文，其他可選的是 'Eng'(英文)和 'ChiS' (簡體中文)。

第二個可輸入的參數是 'DE431' 或 'DE441'， 表示計算月相和節氣用的曆表，默認值是 'DE441'。如前述，紫金山天文臺自2014年起用 DE421 曆表編算天文年曆，直至2025年仍是如此，DE421、DE431及DE441曆表算出的月相和節氣在距今幾十年間差異甚微(DE421 曆表的年限是1899年至2053年)，在遠古和遙遠將來 DE431 和 DE441 算出的時刻雖然差異較大，但仍未超出 TDB 轉換 UT1 的估計誤差。1929年至2013年中曆的月相和節氣用舊曆表計算，與 DE 曆表的差異可達半分鐘。1929年前的節氣不但用舊曆表計算，時刻也不用UT+8，差異當然更大。

-3502-3503月相與節氣的TDB時刻已預先算好，數據存於源碼資料夾`src/ChineseCalendar_py/sunMoon_DE431.csv`和`src/ChineseCalendar_py/sunMoon_DE441.csv`。在源碼資料夾`src/ChineseCalendar_py/`有函數`get_dTT_UT()`輸出 TT-UT 的數值，用於轉月相和節氣時刻為UT+8，此函數大約一年要更新一次以含括最新閏秒數據，因閏秒將於2035年或更早會被取消，到時便不用頻繁更新。

In [19]:
# 獲取公元3500年的節氣和月相
st, mp = sm.st_mp(3500)
print('節氣:\n', st)
print('月相:\n', mp)

節氣:
 [['J12', {'event': '小寒', 'year': 3500, 'month': 1, 'date': 6, 'hour': 7, 'minute': 2, 'dateString': '1月6日', 'timeString': '07:02', 'jd0_ut': 2999407.5, 'jd1_ut': 5.959842061353328}], ['Z12', {'event': '大寒', 'year': 3500, 'month': 1, 'date': 21, 'hour': 1, 'minute': 14, 'dateString': '1月21日', 'timeString': '01:14', 'jd0_ut': 2999407.5, 'jd1_ut': 20.718280931005655}], ['J1', {'event': '立春', 'year': 3500, 'month': 2, 'date': 4, 'hour': 18, 'minute': 54, 'dateString': '2月4日', 'timeString': '18:54', 'jd0_ut': 2999407.5, 'jd1_ut': 35.454193554548816}], ['Z1', {'event': '雨水', 'year': 3500, 'month': 2, 'date': 19, 'hour': 12, 'minute': 59, 'dateString': '2月19日', 'timeString': '12:59', 'jd0_ut': 2999407.5, 'jd1_ut': 50.20746779877934}], ['J2', {'event': '驚蟄', 'year': 3500, 'month': 3, 'date': 6, 'hour': 8, 'minute': 1, 'dateString': '3月6日', 'timeString': '08:01', 'jd0_ut': 2999407.5, 'jd1_ut': 65.00048394186084}], ['Z2', {'event': '春分', 'year': 3500, 'month': 3, 'date': 21, 'hour': 4, 'minute': 53, 'dateString': '3月21日', 'timeString': '04:53', 'jd0_ut': 2999407.5, 'jd1_ut': 79.86981892632781}], ['J3', {'event': '清明', 'year': 3500, 'month': 4, 'date': 5, 'hour': 3, 'minute': 57, 'dateString': '4月5日', 'timeString': '03:57', 'jd0_ut': 2999407.5, 'jd1_ut': 94.83096817200175}], ['Z3', {'event': '穀雨', 'year': 3500, 'month': 4, 'date': 20, 'hour': 5, 'minute': 50, 'dateString': '4月20日', 'timeString': '05:50', 'jd0_ut': 2999407.5, 'jd1_ut': 109.90977010507072}], ['J4', {'event': '立夏', 'year': 3500, 'month': 5, 'date': 5, 'hour': 10, 'minute': 38, 'dateString': '5月5日', 'timeString': '10:38', 'jd0_ut': 2999407.5, 'jd1_ut': 125.10947091740418}], ['Z4', {'event': '小滿', 'year': 3500, 'month': 5, 'date': 20, 'hour': 18, 'minute': 32, 'dateString': '5月20日', 'timeString': '18:32', 'jd0_ut': 2999407.5, 'jd1_ut': 140.4387534252777}], ['J5', {'event': '芒種', 'year': 3500, 'month': 6, 'date': 5, 'hour': 5, 'minute': 16, 'dateString': '6月5日', 'timeString': '05:16', 'jd0_ut': 2999407.5, 'jd1_ut': 155.88641968348998}], ['Z5', {'event': '夏至', 'year': 3500, 'month': 6, 'date': 20, 'hour': 18, 'minute': 34, 'dateString': '6月20日', 'timeString': '18:34', 'jd0_ut': 2999407.5, 'jd1_ut': 171.44049890975725}], ['J6', {'event': '小暑', 'year': 3500, 'month': 7, 'date': 6, 'hour': 9, 'minute': 52, 'dateString': '7月6日', 'timeString': '09:52', 'jd0_ut': 2999407.5, 'jd1_ut': 187.0776442874307}], ['Z6', {'event': '大暑', 'year': 3500, 'month': 7, 'date': 22, 'hour': 2, 'minute': 25, 'dateString': '7月22日', 'timeString': '02:25', 'jd0_ut': 2999407.5, 'jd1_ut': 202.7670252144291}], ['J7', {'event': '立秋', 'year': 3500, 'month': 8, 'date': 6, 'hour': 19, 'minute': 31, 'dateString': '8月6日', 'timeString': '19:31', 'jd0_ut': 2999407.5, 'jd1_ut': 218.4800733389651}], ['Z7', {'event': '處暑', 'year': 3500, 'month': 8, 'date': 22, 'hour': 12, 'minute': 11, 'dateString': '8月22日', 'timeString': '12:11', 'jd0_ut': 2999407.5, 'jd1_ut': 234.17463316911727}], ['J8', {'event': '白露', 'year': 3500, 'month': 9, 'date': 7, 'hour': 3, 'minute': 50, 'dateString': '9月7日', 'timeString': '03:50', 'jd0_ut': 2999407.5, 'jd1_ut': 249.82667054395995}], ['Z8', {'event': '秋分', 'year': 3500, 'month': 9, 'date': 22, 'hour': 17, 'minute': 28, 'dateString': '9月22日', 'timeString': '17:28', 'jd0_ut': 2999407.5, 'jd1_ut': 265.39453092715394}], ['J9', {'event': '寒露', 'year': 3500, 'month': 10, 'date': 8, 'hour': 4, 'minute': 49, 'dateString': '10月8日', 'timeString': '04:49', 'jd0_ut': 2999407.5, 'jd1_ut': 280.867087507004}], ['Z9', {'event': '霜降', 'year': 3500, 'month': 10, 'date': 23, 'hour': 13, 'minute': 8, 'dateString': '10月23日', 'timeString': '13:08', 'jd0_ut': 2999407.5, 'jd1_ut': 296.21395772260337}], ['J10', {'event': '立冬', 'year': 3500, 'month': 11, 'date': 7, 'hour': 18, 'minute': 36, 'dateString': '11月7日', 'timeString': '18:36', 'jd0_ut': 2999407.5, 'jd1_ut': 311.44143044582245}], ['Z10', {'event': '小雪', 'year': 3500, 'month': 11, 'date': 22, 'hour': 20, 'minute': 51, 'dateString': '11月22日', 'timeString': '20:51', 'jd0_ut': 2999407.5, 'jd1_ut': 326.5356782296335}], ['J11', {'event': '大雪', 'year': 3500, 'month': 12, 'date': 7, 'hour': 20, 'minute': 29, 'dateString': '12月7日', 'timeString': '20:29', 'jd0_ut': 2999407.5, 'jd1_ut': 341.52039177669093}], ['Z11', {'event': '冬至', 'year': 3500, 'month': 12, 'date': 22, 'hour': 17, 'minute': 33, 'dateString': '12月22日', 'timeString': '17:33', 'jd0_ut': 2999407.5, 'jd1_ut': 356.3979728763978}]]
月相:
 [['Q1', {'event': '上弦', 'year': 3500, 'month': 1, 'date': 1, 'hour': 0, 'minute': 36, 'dateString': '1月1日', 'timeString': '00:36', 'jd0_ut': 2999407.5, 'jd1_ut': 0.6920066560282614}], ['Q2', {'event': '望', 'year': 3500, 'month': 1, 'date': 9, 'hour': 3, 'minute': 40, 'dateString': '1月9日', 'timeString': '03:40', 'jd0_ut': 2999407.5, 'jd1_ut': 8.81968228343947, 'eclipse': '半影月食', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=3401&ind=251&DE=441&shrule=revised_Danjon&ref=python'}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 1, 'date': 17, 'hour': 1, 'minute': 5, 'dateString': '1月17日', 'timeString': '01:05', 'jd0_ut': 2999407.5, 'jd1_ut': 16.71162403213348}], ['Q0', {'event': '朔', 'year': 3500, 'month': 1, 'date': 23, 'hour': 17, 'minute': 3, 'dateString': '1月23日', 'timeString': '17:03', 'jd0_ut': 2999407.5, 'jd1_ut': 23.377318247244986}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 1, 'date': 30, 'hour': 17, 'minute': 13, 'dateString': '1月30日', 'timeString': '17:13', 'jd0_ut': 2999407.5, 'jd1_ut': 30.384028430678082}], ['Q2', {'event': '望', 'year': 3500, 'month': 2, 'date': 7, 'hour': 22, 'minute': 50, 'dateString': '2月7日', 'timeString': '22:50', 'jd0_ut': 2999407.5, 'jd1_ut': 38.617791239176576}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 2, 'date': 15, 'hour': 12, 'minute': 2, 'dateString': '2月15日', 'timeString': '12:02', 'jd0_ut': 2999407.5, 'jd1_ut': 46.16826826038512}], ['Q0', {'event': '朔', 'year': 3500, 'month': 2, 'date': 22, 'hour': 4, 'minute': 24, 'dateString': '2月22日', 'timeString': '04:24', 'jd0_ut': 2999407.5, 'jd1_ut': 52.8498902367278}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 3, 'date': 1, 'hour': 12, 'minute': 54, 'dateString': '3月1日', 'timeString': '12:54', 'jd0_ut': 2999407.5, 'jd1_ut': 60.20438817871954}], ['Q2', {'event': '望', 'year': 3500, 'month': 3, 'date': 9, 'hour': 15, 'minute': 55, 'dateString': '3月9日', 'timeString': '15:55', 'jd0_ut': 2999407.5, 'jd1_ut': 68.3296250639521}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 3, 'date': 16, 'hour': 20, 'minute': 48, 'dateString': '3月16日', 'timeString': '20:48', 'jd0_ut': 2999407.5, 'jd1_ut': 75.53299498870601}], ['Q0', {'event': '朔', 'year': 3500, 'month': 3, 'date': 23, 'hour': 16, 'minute': 24, 'dateString': '3月23日', 'timeString': '16:24', 'jd0_ut': 2999407.5, 'jd1_ut': 82.35016297188179}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 3, 'date': 31, 'hour': 9, 'minute': 59, 'dateString': '3月31日', 'timeString': '09:59', 'jd0_ut': 2999407.5, 'jd1_ut': 90.08262437871339}], ['Q2', {'event': '望', 'year': 3500, 'month': 4, 'date': 8, 'hour': 6, 'minute': 10, 'dateString': '4月8日', 'timeString': '06:10', 'jd0_ut': 2999407.5, 'jd1_ut': 97.92373732105295}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 4, 'date': 15, 'hour': 4, 'minute': 1, 'dateString': '4月15日', 'timeString': '04:01', 'jd0_ut': 2999407.5, 'jd1_ut': 104.83400699109681}], ['Q0', {'event': '朔', 'year': 3500, 'month': 4, 'date': 22, 'hour': 5, 'minute': 25, 'dateString': '4月22日', 'timeString': '05:25', 'jd0_ut': 2999407.5, 'jd1_ut': 111.89264053567214}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 4, 'date': 30, 'hour': 6, 'minute': 15, 'dateString': '4月30日', 'timeString': '06:15', 'jd0_ut': 2999407.5, 'jd1_ut': 119.92681408283815}], ['Q2', {'event': '望', 'year': 3500, 'month': 5, 'date': 7, 'hour': 17, 'minute': 43, 'dateString': '5月7日', 'timeString': '17:43', 'jd0_ut': 2999407.5, 'jd1_ut': 127.40501613505016}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 5, 'date': 14, 'hour': 10, 'minute': 39, 'dateString': '5月14日', 'timeString': '10:39', 'jd0_ut': 2999407.5, 'jd1_ut': 134.11028834234236}], ['Q0', {'event': '朔', 'year': 3500, 'month': 5, 'date': 21, 'hour': 19, 'minute': 42, 'dateString': '5月21日', 'timeString': '19:42', 'jd0_ut': 2999407.5, 'jd1_ut': 141.48755136138817}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 5, 'date': 29, 'hour': 23, 'minute': 57, 'dateString': '5月29日', 'timeString': '23:57', 'jd0_ut': 2999407.5, 'jd1_ut': 149.66429954837122}], ['Q2', {'event': '望', 'year': 3500, 'month': 6, 'date': 6, 'hour': 3, 'minute': 4, 'dateString': '6月6日', 'timeString': '03:04', 'jd0_ut': 2999407.5, 'jd1_ut': 156.79471775042782, 'eclipse': '月偏食', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=3401&ind=252&DE=441&shrule=revised_Danjon&ref=python'}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 6, 'date': 12, 'hour': 17, 'minute': 47, 'dateString': '6月12日', 'timeString': '17:47', 'jd0_ut': 2999407.5, 'jd1_ut': 163.40769793681432}], ['Q0', {'event': '朔', 'year': 3500, 'month': 6, 'date': 20, 'hour': 11, 'minute': 1, 'dateString': '6月20日', 'timeString': '11:01', 'jd0_ut': 2999407.5, 'jd1_ut': 171.12551544418866, 'eclipse': '日環食', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=3401&ind=250&DE=441&ref=python'}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 6, 'date': 28, 'hour': 14, 'minute': 21, 'dateString': '6月28日', 'timeString': '14:21', 'jd0_ut': 2999407.5, 'jd1_ut': 179.26460200118035}], ['Q2', {'event': '望', 'year': 3500, 'month': 7, 'date': 5, 'hour': 10, 'minute': 52, 'dateString': '7月5日', 'timeString': '10:52', 'jd0_ut': 2999407.5, 'jd1_ut': 186.1191003268794}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 7, 'date': 12, 'hour': 2, 'minute': 33, 'dateString': '7月12日', 'timeString': '02:33', 'jd0_ut': 2999407.5, 'jd1_ut': 192.773169338639}], ['Q0', {'event': '朔', 'year': 3500, 'month': 7, 'date': 20, 'hour': 2, 'minute': 39, 'dateString': '7月20日', 'timeString': '02:39', 'jd0_ut': 2999407.5, 'jd1_ut': 200.77711769296496}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 7, 'date': 28, 'hour': 1, 'minute': 35, 'dateString': '7月28日', 'timeString': '01:35', 'jd0_ut': 2999407.5, 'jd1_ut': 208.73282494316825}], ['Q2', {'event': '望', 'year': 3500, 'month': 8, 'date': 3, 'hour': 17, 'minute': 50, 'dateString': '8月3日', 'timeString': '17:50', 'jd0_ut': 2999407.5, 'jd1_ut': 215.4094330445667}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 8, 'date': 10, 'hour': 13, 'minute': 55, 'dateString': '8月10日', 'timeString': '13:55', 'jd0_ut': 2999407.5, 'jd1_ut': 222.24632955284363}], ['Q0', {'event': '朔', 'year': 3500, 'month': 8, 'date': 18, 'hour': 17, 'minute': 49, 'dateString': '8月18日', 'timeString': '17:49', 'jd0_ut': 2999407.5, 'jd1_ut': 230.40917836191667}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 8, 'date': 26, 'hour': 10, 'minute': 14, 'dateString': '8月26日', 'timeString': '10:14', 'jd0_ut': 2999407.5, 'jd1_ut': 238.09301618530733}], ['Q2', {'event': '望', 'year': 3500, 'month': 9, 'date': 2, 'hour': 0, 'minute': 56, 'dateString': '9月2日', 'timeString': '00:56', 'jd0_ut': 2999407.5, 'jd1_ut': 244.705384971758}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 9, 'date': 9, 'hour': 4, 'minute': 21, 'dateString': '9月9日', 'timeString': '04:21', 'jd0_ut': 2999407.5, 'jd1_ut': 251.8482209148659}], ['Q0', {'event': '朔', 'year': 3500, 'month': 9, 'date': 17, 'hour': 8, 'minute': 3, 'dateString': '9月17日', 'timeString': '08:03', 'jd0_ut': 2999407.5, 'jd1_ut': 260.00230746307665}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 9, 'date': 24, 'hour': 17, 'minute': 4, 'dateString': '9月24日', 'timeString': '17:04', 'jd0_ut': 2999407.5, 'jd1_ut': 267.3780523834939}], ['Q2', {'event': '望', 'year': 3500, 'month': 10, 'date': 1, 'hour': 9, 'minute': 19, 'dateString': '10月1日', 'timeString': '09:19', 'jd0_ut': 2999407.5, 'jd1_ut': 274.0546344019013}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 10, 'date': 8, 'hour': 21, 'minute': 42, 'dateString': '10月8日', 'timeString': '21:42', 'jd0_ut': 2999407.5, 'jd1_ut': 281.570885521494}], ['Q0', {'event': '朔', 'year': 3500, 'month': 10, 'date': 16, 'hour': 21, 'minute': 19, 'dateString': '10月16日', 'timeString': '21:19', 'jd0_ut': 2999407.5, 'jd1_ut': 289.55510690637067}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 10, 'date': 23, 'hour': 23, 'minute': 4, 'dateString': '10月23日', 'timeString': '23:04', 'jd0_ut': 2999407.5, 'jd1_ut': 296.62796921100306}], ['Q2', {'event': '望', 'year': 3500, 'month': 10, 'date': 30, 'hour': 20, 'minute': 7, 'dateString': '10月30日', 'timeString': '20:07', 'jd0_ut': 2999407.5, 'jd1_ut': 303.50500727377096}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 11, 'date': 7, 'hour': 17, 'minute': 2, 'dateString': '11月7日', 'timeString': '17:02', 'jd0_ut': 2999407.5, 'jd1_ut': 311.3761620230932}], ['Q0', {'event': '朔', 'year': 3500, 'month': 11, 'date': 15, 'hour': 9, 'minute': 49, 'dateString': '11月15日', 'timeString': '09:49', 'jd0_ut': 2999407.5, 'jd1_ut': 319.07537457462996}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 11, 'date': 22, 'hour': 5, 'minute': 23, 'dateString': '11月22日', 'timeString': '05:23', 'jd0_ut': 2999407.5, 'jd1_ut': 325.89108874115215}], ['Q2', {'event': '望', 'year': 3500, 'month': 11, 'date': 29, 'hour': 10, 'minute': 7, 'dateString': '11月29日', 'timeString': '10:07', 'jd0_ut': 2999407.5, 'jd1_ut': 333.08812331508364, 'eclipse': '月偏食', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=3401&ind=253&DE=441&shrule=revised_Danjon&ref=python'}], ['Q3', {'event': '下弦', 'year': 3500, 'month': 12, 'date': 7, 'hour': 12, 'minute': 58, 'dateString': '12月7日', 'timeString': '12:58', 'jd0_ut': 2999407.5, 'jd1_ut': 341.2068875424675}], ['Q0', {'event': '朔', 'year': 3500, 'month': 12, 'date': 14, 'hour': 21, 'minute': 39, 'dateString': '12月14日', 'timeString': '21:39', 'jd0_ut': 2999407.5, 'jd1_ut': 348.5689319389534, 'eclipse': '日全食', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=3401&ind=251&DE=441&ref=python'}], ['Q1', {'event': '上弦', 'year': 3500, 'month': 12, 'date': 21, 'hour': 13, 'minute': 19, 'dateString': '12月21日', 'timeString': '13:19', 'jd0_ut': 2999407.5, 'jd1_ut': 355.2211868041038}], ['Q2', {'event': '望', 'year': 3500, 'month': 12, 'date': 29, 'hour': 3, 'minute': 12, 'dateString': '12月29日', 'timeString': '03:12', 'jd0_ut': 2999407.5, 'jd1_ut': 362.7999416139854}]]

In [20]:
# 公元3500年的全年的月相和節氣，轉為 pandas dataframe 來顯示。
st, mp = sm.st_mp_df(3500)
display(st)
display(mp)

    節氣      時刻 (UT+8)
0   小寒    1月6日, 07:02
1   大寒   1月21日, 01:14
2   立春    2月4日, 18:54
3   雨水   2月19日, 12:59
4   驚蟄    3月6日, 08:01
5   春分   3月21日, 04:53
6   清明    4月5日, 03:57
7   穀雨   4月20日, 05:50
8   立夏    5月5日, 10:38
9   小滿   5月20日, 18:32
10  芒種    6月5日, 05:16
11  夏至   6月20日, 18:34
12  小暑    7月6日, 09:52
13  大暑   7月22日, 02:25
14  立秋    8月6日, 19:31
15  處暑   8月22日, 12:11
16  白露    9月7日, 03:50
17  秋分   9月22日, 17:28
18  寒露   10月8日, 04:49
19  霜降  10月23日, 13:08
20  立冬   11月7日, 18:36
21  小雪  11月22日, 20:51
22  大雪   12月7日, 20:29
23  冬至  12月22日, 17:33

,朔,上弦,望,下弦
0,,"1月1日, 00:36","1月9日, 03:40<br /><a href=""http://ytliu.epizy.c...","1月17日, 01:05"
1,"1月23日, 17:03","1月30日, 17:13","2月7日, 22:50","2月15日, 12:02"
2,"2月22日, 04:24","3月1日, 12:54","3月9日, 15:55","3月16日, 20:48"
3,"3月23日, 16:24","3月31日, 09:59","4月8日, 06:10","4月15日, 04:01"
4,"4月22日, 05:25","4月30日, 06:15","5月7日, 17:43","5月14日, 10:39"
5,"5月21日, 19:42","5月29日, 23:57","6月6日, 03:04<br /><a href=""http://ytliu.epizy.c...","6月12日, 17:47"
6,"6月20日, 11:01<br /><a href=""http://ytliu.epizy....","6月28日, 14:21","7月5日, 10:52","7月12日, 02:33"
7,"7月20日, 02:39","7月28日, 01:35","8月3日, 17:50","8月10日, 13:55"
8,"8月18日, 17:49","8月26日, 10:14","9月2日, 00:56","9月9日, 04:21"
9,"9月17日, 08:03","9月24日, 17:04","10月1日, 09:19","10月8日, 21:42"
10,"10月16日, 21:19","10月23日, 23:04","10月30日, 20:07","11月7日, 17:02"
11,"11月15日, 09:49","11月22日, 05:23","11月29日, 10:07<br /><a href=""http://ytliu.epizy...","12月7日, 12:58"
12,"12月14日, 21:39<br /><a href=""http://ytliu.epizy...","12月21日, 13:19","12月29日, 03:12",

月相中朔和望還提供日月食的資料，有連結到我製的日月食網頁，要恰當顯示連結，可用 pandas dataframe 提供的 `.to_html` 函數轉為 HTML 文字，然後用 `IPython.display.HTML()` 顯示，得出的輸出類此[氣朔網頁](https://ytliu0.github.io/ChineseCalendar/sunMoon_chinese.html)的表格。

In [21]:
HTML(mp.to_html(
    render_links=True,
    escape=False,
))

## 曆書節氣

古代的節氣用當時的曆法計算，算出的節氣與用現代曆表的節氣常有大差異，函數`.calendrical_solar_terms(y, calendar='default', ephemeris='None')`提供公曆 y 年的曆書節氣，即按當時曆法計算的節氣。參數`ephemeris`只有當選取 calendar='GBT' 時用來選擇DE曆表，其他的calendar選項沒有作用。

In [22]:
# 吳大帝赤烏十三年(250年)的曆書節氣
cal.calendrical_solar_terms(250, calendar='Wu')

[{'節氣': '小寒', '日期': '1月8日'},
 {'節氣': '大寒', '日期': '1月23日'},
 {'節氣': '立春', '日期': '2月7日'},
 {'節氣': '雨水', '日期': '2月22日'},
 {'節氣': '驚蟄', '日期': '3月9日'},
 {'節氣': '春分', '日期': '3月25日'},
 {'節氣': '清明', '日期': '4月9日'},
 {'節氣': '穀雨', '日期': '4月24日'},
 {'節氣': '立夏', '日期': '5月9日'},
 {'節氣': '小滿', '日期': '5月25日'},
 {'節氣': '芒種', '日期': '6月9日'},
 {'節氣': '夏至', '日期': '6月24日'},
 {'節氣': '小暑', '日期': '7月9日'},
 {'節氣': '大暑', '日期': '7月24日'},
 {'節氣': '立秋', '日期': '8月9日'},
 {'節氣': '處暑', '日期': '8月24日'},
 {'節氣': '白露', '日期': '9月8日'},
 {'節氣': '秋分', '日期': '9月23日'},
 {'節氣': '寒露', '日期': '10月9日'},
 {'節氣': '霜降', '日期': '10月24日'},
 {'節氣': '立冬', '日期': '11月8日'},
 {'節氣': '小雪', '日期': '11月23日'},
 {'節氣': '大雪', '日期': '12月8日'},
 {'節氣': '冬至', '日期': '12月24日'}]

In [23]:
# 吳大帝赤烏十三年(250年)的曆書節氣轉為 pandas dataframe 顯示
display(pd.DataFrame(cal.calendrical_solar_terms(250, calendar='Wu')))

    節氣      日期
0   小寒    1月8日
1   大寒   1月23日
2   立春    2月7日
3   雨水   2月22日
4   驚蟄    3月9日
5   春分   3月25日
6   清明    4月9日
7   穀雨   4月24日
8   立夏    5月9日
9   小滿   5月25日
10  芒種    6月9日
11  夏至   6月24日
12  小暑    7月9日
13  大暑   7月24日
14  立秋    8月9日
15  處暑   8月24日
16  白露    9月8日
17  秋分   9月23日
18  寒露   10月9日
19  霜降  10月24日
20  立冬   11月8日
21  小雪  11月23日
22  大雪   12月8日
23  冬至  12月24日

此函數輸出公曆 y 年的曆書節氣，如要中曆 y 年的曆書節氣，可用上述
`.chinese_year_info()` 或 `.chinese_year_html()` 函數。

## 日曆計算習題

上面介紹了本軟體套件提供的公曆-中曆互轉基本函數。本資料夾中`calendar_exercises.ipynb`筆記本會展示如何用本軟體提供的函數處理較複雜的日曆計算。