# Tutorial

This tutorial provides more information on the functions of this package. It is useful to go through the Quickstart guide first before reading this tutorial. Examples shown in the Quickstart guide will not be repeated here.

## Installation

Use the following `pip` command to install and update this package.

In [1]:
# Uncomment the following line to install and update the package.
#pip install --upgrade ChineseCalendar_py

## Load package

In [2]:
import ChineseCalendar_py.calendar_conversion as ccal
from IPython.display import HTML
import pandas as pd

Use the following command to create an instance of the Chinese calendar object. The input parameter `'Eng'` means the calendar information will be displayed in English. Two other possible parameters are `'ChiT'` for traditional Chinese and `'ChiS'` for simplified Chinese.

In [3]:
cal = ccal.calendar_conversion('Eng')

## Default and Available Calendars

Over the course of Chinese history, there were periods where multiple Chinese calendars were used in different regions in China. This package supports multiple, but not all, versions of Chinese calendars in those periods. 

To prevent confusion, one set of Chinese calendars is selected in those periods used by particular states/regions. This is called the *default calendars* here. In the past, those states were regarded as the legitimate governments representing China by some Chinese historians. Today they are regarded as just conventions with no legitimacy connotation. The [defaule calendar page](https://ytliu0.github.io/ChineseCalendar-python/tutorial/English/default_calendar.html) lists the versions of Chinese calendars selected by the default calendar, which covers the years from -721 (722 BCE) to 2200.

As stated on the [defaule calendar page](https://ytliu0.github.io/ChineseCalendar-python/tutorial/English/default_calendar.html), the calendar data in -103 – 2200 are stored in an array for table lookup. The data are stored in the source-code folder in the file 'default_calendar_M105_2201.csv', which contains the conjunction dates, leap month information and calendrical solar terms counted from Jan 0 of the year. When an instance of the Chinese calendar class is created, the conjunction and leap month information are loaded to the `.calData` array and the calendrical solar term data are loaded to the `calSterm` array. These arrays may be useful in some calendar calculations, as shown in the calendar exercise notebook in this folder. The year span in the arrays are actually from -105 to 2202 for the convenience of calendar calculations.

Apart from the calendars used by the default calendars, this package also supports a number of other version of Chinese calendars. The [available calendar page](https://ytliu0.github.io/ChineseCalendar-python/tutorial/English/available_calendars.html) lists all supported calendars. Note that all the calendars there were used in certain period and certain regions in China. Most of them are calculated based on their calendar rules and can in principle be used outside the years of usage, but it is strongly discouraged to do so.

## Western calendar to Chinese calendar conversion

Three methods are provides to do the conversion:

- `.western_to_chinese_date(y, m, d, calendar=default, multiple_calendars=False, ephemeris='None')`: Western date (year = y, month = m, date = d) to Chinese date.

- `.western_to_chinese_year(y, m=None, calendar='default', ephemeris='None')`: Western year y, month m (if m is not None) to Chinese dates

- `.western_to_chinese_year_html(y, m=None, calendar='default', showJDN=False, ephemeris='None', show_chinese_year_info=True,show_chinese_calendar_info=True)`: Same as `western_to_chinese_year()` but return an HTML text.

The 'multiple_calendars' argument in `.western_to_chinese_date()` is only for the default calendars. If set to True, it will return the dates from multiple Chinese calendars in the periods when China was divided.

The 'calendar' argument allows the user to select a particular Chinese calendar. It's either 'default' (for the default calendars) or one of the calendar labels listed on the [available calendar page](https://ytliu0.github.io/ChineseCalendar-python/tutorial/English/available_calendars.html).

The 'ephemeris' argument allows a user to specify an ephemeris for the times of modern moon phases and solar terms. It's either DE441 or DE431. When the argument is missing, it will take the default value 'None', which will pick whatever ephemeris previously specified or DE441 if an ephemeris has not been specified.

The following command converts February 25, 445 to the Chinese calendar used in the Northern Wei dynasty. According to the [available calendar page](https://ytliu0.github.io/ChineseCalendar-python/tutorial/English/available_calendars.html), we need to use the 'WeiZhouSui' label.

In [4]:
cal.western_to_chinese_date(445, 2, 25, calendar='WeiZhouSui')

{'Western ymd': [445, 2, 25],
 'Western calendar': 'Julian',
 'JDN': 1883650,
 'Chinese ymd': [445, -1, 3],
 'cyear': 445,
 'cdate': 'leap 1-03',
 'sexagenary year': ['Yi You', 'Chicken', 22],
 'Nday_cmonth': 29,
 'sexagenary date': ['Gui Hai', 60],
 'Week': ['Sun', 0],
 'period': 'Northern and Southern Dynasties (420 - 580)',
 'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
 'Chinese calendar': 'Jingchu'}

This shows that February 25, 445 corresponds to the 3rd day in the leap month 1 in the Northern Wei calendar, which was based on the Jingchu system. The Chinese year was Tàiwǔdì Tàipíngzhēnjūn 6 and its sexagenary year cycle was Yi You.

This method `.western_to_chinese_date()` returns a python dictionary with the following keys:

`'Western ymd'`: a list containing Western year, month, day

`'Western calendar'`: version of the Western calendar (Gregorian, Julian or propleptic Julian).

`'JDN'`: Julian date at noon. 

`'Chinese ymd'`: a list containing Chinese year, month (negative means leap month) and date. 

`'cyear'`: Western year with the most overlap of days in the Chinese year.

`'cdate'`: Chinese month number-day number. 

`'sexagenary year'`: a list with \[sexagenary year cycle, sexagenary number\]. Sexagenary number 1 means Jia zi, 2 means Yi chow, and so on (see Table 2 on [my sexagenary cycle page](https://ytliu0.github.io/ChineseCalendar/sexagenary.html) for the complete list). 

`'jian'`: sexagenary month cycle. See [my sexagenary cycle page](https://ytliu0.github.io/ChineseCalendar/sexagenary.html) for an explanation of the sexagenary month cycle and *jian*.

`'Nday_cmonth'`: number of days in the Chinese month, usually 29 or 30.

`'sexagenary date'`: sexagenary date cycle. See [my sexagenary cycle page](https://ytliu0.github.io/ChineseCalendar/sexagenary.html) for an explanation of the sexagenary date cycle.

`'Week'`: \[day of week, week number\]. Week number convention: 0 for Sunday, 1 for Monday, 2 for Tuesday, 3 for Wednesday, 4 for Thursday, 5 for Friday and 6 for Saturday.

`'period'`: Period in the Chinese history.

`'Chinese calendar'`: version of the Chinese calendar.

As in [my Chinese calendar webpage](https://ytliu0.github.io/ChineseCalendar), the year y should be between -721 and 2200. In some years in the past, there were multiple versions of Chinese calendar used in those years, and the command returns only one of them. Multiple versions of calendar dates can be retrieved by setting calendar='default' and multiple_calendars=True:

In [5]:
cal.western_to_chinese_date(445, 2, 25, multiple_calendars=True)

[{'Western ymd': [445, 2, 25],
  'Western calendar': 'Julian',
  'JDN': 1883650,
  'Chinese ymd': [445, 2, 3],
  'cyear': 445,
  'cdate': '2-03',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Ji Mao', 16],
  'Nday_cmonth': 29,
  'sexagenary date': ['Gui Hai', 60],
  'Week': ['Sun', 0],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Song] Wéndì Yuánjiā 22',
  'Chinese calendar': 'Yuanjia'},
 {'Western ymd': [445, 2, 25],
  'Western calendar': 'Julian',
  'JDN': 1883650,
  'Chinese ymd': [445, -1, 3],
  'cyear': 445,
  'cdate': 'leap 1-03',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['Gui Hai', 60],
  'Week': ['Sun', 0],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'}]

This output shows that February 25, 445 also corresponds to the 3rd day in the second month in the calendar used by the Song dynasty, which was based on the Yuanjia system. This is the date that is returned for calendar='default'.

The following command `cal.western_to_chinese_year(445, 2, calendar='WeiZhouSui')` returns a list of dictaionary showing all dates in February 445 in the Northern Wei calendar. The command `cal.western_to_chinese_year(445, calendar='WeiZhouSui')` shows all dates in 445.

In [6]:
cal.western_to_chinese_year(445, 2, calendar='WeiZhouSui')

[{'Western ymd': [445, 2, 1],
  'Western calendar': 'Julian',
  'JDN': 1883626,
  'Chinese ymd': [445, 1, 9],
  'cyear': 445,
  'cdate': '1-09',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji Hai', 36],
  'Week': ['Thu', 4],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 2],
  'Western calendar': 'Julian',
  'JDN': 1883627,
  'Chinese ymd': [445, 1, 10],
  'cyear': 445,
  'cdate': '1-10',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Zi', 37],
  'Week': ['Fri', 5],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 3],
  'Western calendar': 'Julian',
  'JDN': 1883628,
  'Chinese ymd': [445, 1, 11],
  'cyear': 445,
  'cdate': '1-11',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Xin Chou', 38],
  'Week': ['Sat', 6],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 4],
  'Western calendar': 'Julian',
  'JDN': 1883629,
  'Chinese ymd': [445, 1, 12],
  'cyear': 445,
  'cdate': '1-12',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ren Yin', 39],
  'Week': ['Sun', 0],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 5],
  'Western calendar': 'Julian',
  'JDN': 1883630,
  'Chinese ymd': [445, 1, 13],
  'cyear': 445,
  'cdate': '1-13',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Gui Mao', 40],
  'Week': ['Mon', 1],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 6],
  'Western calendar': 'Julian',
  'JDN': 1883631,
  'Chinese ymd': [445, 1, 14],
  'cyear': 445,
  'cdate': '1-14',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Jia Chen', 41],
  'Week': ['Tue', 2],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 7],
  'Western calendar': 'Julian',
  'JDN': 1883632,
  'Chinese ymd': [445, 1, 15],
  'cyear': 445,
  'cdate': '1-15',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Yi Si', 42],
  'Week': ['Wed', 3],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 8],
  'Western calendar': 'Julian',
  'JDN': 1883633,
  'Chinese ymd': [445, 1, 16],
  'cyear': 445,
  'cdate': '1-16',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Bing Wu', 43],
  'Week': ['Thu', 4],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 9],
  'Western calendar': 'Julian',
  'JDN': 1883634,
  'Chinese ymd': [445, 1, 17],
  'cyear': 445,
  'cdate': '1-17',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ding Wei', 44],
  'Week': ['Fri', 5],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 10],
  'Western calendar': 'Julian',
  'JDN': 1883635,
  'Chinese ymd': [445, 1, 18],
  'cyear': 445,
  'cdate': '1-18',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Wu Shen', 45],
  'Week': ['Sat', 6],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 11],
  'Western calendar': 'Julian',
  'JDN': 1883636,
  'Chinese ymd': [445, 1, 19],
  'cyear': 445,
  'cdate': '1-19',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji You', 46],
  'Week': ['Sun', 0],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 12],
  'Western calendar': 'Julian',
  'JDN': 1883637,
  'Chinese ymd': [445, 1, 20],
  'cyear': 445,
  'cdate': '1-20',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Xu', 47],
  'Week': ['Mon', 1],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 13],
  'Western calendar': 'Julian',
  'JDN': 1883638,
  'Chinese ymd': [445, 1, 21],
  'cyear': 445,
  'cdate': '1-21',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Xin Hai', 48],
  'Week': ['Tue', 2],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 14],
  'Western calendar': 'Julian',
  'JDN': 1883639,
  'Chinese ymd': [445, 1, 22],
  'cyear': 445,
  'cdate': '1-22',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ren Zi', 49],
  'Week': ['Wed', 3],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 15],
  'Western calendar': 'Julian',
  'JDN': 1883640,
  'Chinese ymd': [445, 1, 23],
  'cyear': 445,
  'cdate': '1-23',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Gui Chou', 50],
  'Week': ['Thu', 4],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 16],
  'Western calendar': 'Julian',
  'JDN': 1883641,
  'Chinese ymd': [445, 1, 24],
  'cyear': 445,
  'cdate': '1-24',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Jia Yin', 51],
  'Week': ['Fri', 5],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 17],
  'Western calendar': 'Julian',
  'JDN': 1883642,
  'Chinese ymd': [445, 1, 25],
  'cyear': 445,
  'cdate': '1-25',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Yi Mao', 52],
  'Week': ['Sat', 6],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 18],
  'Western calendar': 'Julian',
  'JDN': 1883643,
  'Chinese ymd': [445, 1, 26],
  'cyear': 445,
  'cdate': '1-26',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Bing Chen', 53],
  'Week': ['Sun', 0],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 19],
  'Western calendar': 'Julian',
  'JDN': 1883644,
  'Chinese ymd': [445, 1, 27],
  'cyear': 445,
  'cdate': '1-27',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ding Si', 54],
  'Week': ['Mon', 1],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 20],
  'Western calendar': 'Julian',
  'JDN': 1883645,
  'Chinese ymd': [445, 1, 28],
  'cyear': 445,
  'cdate': '1-28',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Wu Wu', 55],
  'Week': ['Tue', 2],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 21],
  'Western calendar': 'Julian',
  'JDN': 1883646,
  'Chinese ymd': [445, 1, 29],
  'cyear': 445,
  'cdate': '1-29',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji Wei', 56],
  'Week': ['Wed', 3],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 22],
  'Western calendar': 'Julian',
  'JDN': 1883647,
  'Chinese ymd': [445, 1, 30],
  'cyear': 445,
  'cdate': '1-30',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Shen', 57],
  'Week': ['Thu', 4],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 23],
  'Western calendar': 'Julian',
  'JDN': 1883648,
  'Chinese ymd': [445, -1, 1],
  'cyear': 445,
  'cdate': 'leap 1-01',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['Xin You', 58],
  'Week': ['Fri', 5],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 24],
  'Western calendar': 'Julian',
  'JDN': 1883649,
  'Chinese ymd': [445, -1, 2],
  'cyear': 445,
  'cdate': 'leap 1-02',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['Ren Xu', 59],
  'Week': ['Sat', 6],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 25],
  'Western calendar': 'Julian',
  'JDN': 1883650,
  'Chinese ymd': [445, -1, 3],
  'cyear': 445,
  'cdate': 'leap 1-03',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['Gui Hai', 60],
  'Week': ['Sun', 0],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 26],
  'Western calendar': 'Julian',
  'JDN': 1883651,
  'Chinese ymd': [445, -1, 4],
  'cyear': 445,
  'cdate': 'leap 1-04',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['Jia Zi', 1],
  'Week': ['Mon', 1],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 27],
  'Western calendar': 'Julian',
  'JDN': 1883652,
  'Chinese ymd': [445, -1, 5],
  'cyear': 445,
  'cdate': 'leap 1-05',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['Yi Chou', 2],
  'Week': ['Tue', 2],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 28],
  'Western calendar': 'Julian',
  'JDN': 1883653,
  'Chinese ymd': [445, -1, 6],
  'cyear': 445,
  'cdate': 'leap 1-06',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['Bing Yin', 3],
  'Week': ['Wed', 3],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'}]

The list above may be useful for further calendar calculations but is not convenient to view. The method `.western_to_chinese_year_html()` returns an html text, which can be displayed nicely in a Jupyter notebook using the `IPython.display.HTML()` function. The result is similar to the calendar table on [my Chinese calendar webpage](https://ytliu0.github.io/ChineseCalendar).

In [7]:
# Calendar table for February, 445 in the Northern Wei calendar
HTML(cal.western_to_chinese_year_html(445, 2, calendar='WeiZhouSui'))

In [8]:
# Showing the JDN (Julian date at noon) in the calendar table February, 445 
# in the Northern Wei calendar
HTML(cal.western_to_chinese_year_html(445, 2, calendar='WeiZhouSui', showJDN=True))

As in [my Chinese calendar page](https://ytliu0.github.io/ChineseCalendar), moon phases and solar terms refer to the modern calculation using JPL's DE441 ephemeris, whereas calendrical solar terms refer to the solar terms calculated using the method at that time. Starting from 2014 and as of 2025, the official moon phases and solar terms promulgated by the Purple Mountain Observatory (the calendrical moon phases and solar terms of modern times) are computed using JPL's DE421/LE421, which are very close to our results based on DE441. All times calculated by DE431/DE441 are in UT+8 (UT1+8 for years before 1972, UTC+8 for years between 1972 and present year, and projected UTC+8 for future years).

In [9]:
# Show the calenar table for 2500 computed by GB/T 33661-2017.
HTML(cal.western_to_chinese_year_html(2500, calendar='GBT'))

## Chinese calendar to Western calendar conversion

Four methods are provided to do the conversion:

`.chinese_to_western_date(y, m, d, calendar='default', ephemeris='None')`: Given a Chinese date (year = y, month = m, date = d), convert to the date in the Western calendar. For a leap month, enter a negative number for `m`.

`.chinese_year_info(y, calendar='default', ephemeris='None')`: Given a Chinese year whose New Year day is closest to Jan 1, y in the Western calendar, this function returns a list containing the first days in Chinese months, calendrical solar terms and solar terms computed by a DE ephemeris in the Chinese year.

`.chinese_year_html(y, calendar='default', ephemeris='None')`: Same as the previous function but returns an HTML text.

`.chinese_to_western_year(y, m=None, calendar='default', ephemeris='None')`: Given a Chinese year y, return a list containing the Western dates corresponding to all days in the year if m is None or Western dates corresponding to all days in month m in the Western calendar.

`chinese_to_western_year_html(y, m=None, calendar='default', showJDN=False, ephemeris='None', show_chinese_year_info=True, show_chinese_calendar_info=True)`: Same as the previous function but returns an HTML text.

There are no equivalent pages in [my Chinese calendar website](https://ytliu0.github.io/ChineseCalendar) providing the same information as these functions. The closest one is the [conversion table page](https://ytliu0.github.io/ChineseCalendar/table.html), which provides information similar to the function `.chinese_year_html()`. 

The usage of these functions are similar to the functions for the conversion from Western to Chinese calendar. Below I show a few examples.

In [10]:
# Convert the 15th day in the 8th month in Chinese year 1661 in the Southern Ming dynasty 
# to Western date
cal.chinese_to_western_date(1661, 8, 15, calendar='SouthernMing')

{'Chinese ymd': [1661, 8, 15],
 'Western ymd': [1661, 9, 8],
 'Western calendar': 'Gregorian',
 'JDN': 2327979,
 'cyear': 1661,
 'cdate': '8-15',
 'sexagenary year': ['Xin Chou', 'Ox', 38],
 'jian': ['Ding You', 34],
 'Nday_cmonth': 29,
 'sexagenary date': ['Ren Chen', 29],
 'Week': ['Thu', 4],
 'period': 'Qing (1645 - 1911)',
 'reign/era': '[Southern Ming] Yǒnglì  15',
 'Chinese calendar': 'Canming Datong'}

This shows that the Western date was September 8, 1661. Note that this was not the date in the calendar used by the Qing dynasty, which was October 7, 1661 as shown by the command `cal.chinese_to_western_date(1661, 8, 15)`.

Ocassionally there are multiple days corresponding to the same Chinese date in the past. This is caused by a Chinese calendar reform. As an example, let's look at the 12th day in the 5th month in the Chinese year 762.

In [11]:
cal.chinese_to_western_date(762, 5, 12)

[{'Chinese ymd': [762, 5, 12],
  'Western ymd': [762, 4, 10],
  'Western calendar': 'Julian',
  'JDN': 1999478,
  'cyear': 762,
  'cdate': '5-12',
  'sexagenary year': ['Ren Yin', 'Tiger', 39],
  'jian': ['Jia Chen', 41],
  'Nday_cmonth': 30,
  'sexagenary date': ['Xin Mao', 28],
  'Week': ['Sat', 6],
  'period': 'Tang (618 - 907)',
  'reign/era': '[Tang] Sùzōng Shàngyuán 3/Bǎoyìng 1',
  'Chinese calendar': 'Wuji'},
 {'Chinese ymd': [762, 5, 12],
  'Western ymd': [762, 6, 8],
  'Western calendar': 'Julian',
  'JDN': 1999537,
  'cyear': 762,
  'cdate': '5-12',
  'sexagenary year': ['Ren Yin', 'Tiger', 39],
  'jian': ['Bing Wu', 43],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Yin', 27],
  'Week': ['Tue', 2],
  'period': 'Tang (618 - 907)',
  'reign/era': '[Tang] Sùzōng Shàngyuán 3/Bǎoyìng 1',
  'Chinese calendar': 'Wuji'}]

The following command returns the information of the Chinese year -250 (251 BCE) in the Zhuanxu calendar.

In [12]:
cal.chinese_year_info(-250, calendar='Zhuanxu')

{'cm': [{'cm': 10, 'JDN': 1629685, 'jian': 'NA', 'n': 29},
  {'cm': 11, 'JDN': 1629714, 'jian': 'NA', 'n': 30},
  {'cm': 12, 'JDN': 1629744, 'jian': 'NA', 'n': 29},
  {'cm': 1, 'JDN': 1629773, 'jian': 'NA', 'n': 30},
  {'cm': 2, 'JDN': 1629803, 'jian': 'NA', 'n': 29},
  {'cm': 3, 'JDN': 1629832, 'jian': 'NA', 'n': 30},
  {'cm': 4, 'JDN': 1629862, 'jian': 'NZ', 'n': 29},
  {'cm': 5, 'JDN': 1629891, 'jian': 'NA', 'n': 30},
  {'cm': 6, 'JDN': 1629921, 'jian': 'NA', 'n': 30},
  {'cm': 7, 'JDN': 1629951, 'jian': 'NA', 'n': 29},
  {'cm': 8, 'JDN': 1629980, 'jian': 'NA', 'n': 30},
  {'cm': 9, 'JDN': 1630010, 'jian': 'NA', 'n': 29},
  {'cm': -9, 'JDN': 1630039, 'jian': 'NA', 'n': 30}],
 'calendar': 'Zhuanxu',
 'reign/era': '[Qin] Zhāoxiāngwáng 56',
 'calst': [('J10', 1629693),
  ('Z10', 1629708),
  ('J11', 1629723),
  ('Z11', 1629739),
  ('J12', 1629754),
  ('Z12', 1629769),
  ('J1', 1629784),
  ('Z1', 1629799),
  ('J2', 1629815),
  ('Z2', 1629830),
  ('J3', 1629845),
  ('Z3', 1629860),
  ('J4', 1629876),
  ('Z4', 1629891),
  ('J5', 1629906),
  ('Z5', 1629921),
  ('J6', 1629936),
  ('Z6', 1629952),
  ('J7', 1629967),
  ('Z7', 1629982),
  ('J8', 1629997),
  ('Z8', 1630013),
  ('J9', 1630028),
  ('Z9', 1630043),
  ('J10', 1630058)],
 'datongST': [],
 'sterm': [['J10',
   {'event': 'J10',
    'year': -251,
    'month': 11,
    'date': 11,
    'hour': 0,
    'minute': 5,
    'dateString': 'Nov 11',
    'timeString': '00:05',
    'jd0_ut': 1629379.5,
    'jd1_ut': 314.6704472091856}],
  ['Z10',
   {'event': 'Z10',
    'year': -251,
    'month': 11,
    'date': 25,
    'hour': 17,
    'minute': 2,
    'dateString': 'Nov 25',
    'timeString': '17:02',
    'jd0_ut': 1629379.5,
    'jd1_ut': 329.3761596532432}],
  ['J11',
   {'event': 'J11',
    'year': -251,
    'month': 12,
    'date': 10,
    'hour': 9,
    'minute': 34,
    'dateString': 'Dec 10',
    'timeString': '09:34',
    'jd0_ut': 1629379.5,
    'jd1_ut': 344.0652342350903}],
  ['Z11',
   {'event': 'Z11 (Dec. solstice)',
    'year': -251,
    'month': 12,
    'date': 25,
    'hour': 2,
    'minute': 50,
    'dateString': 'Dec 25',
    'timeString': '02:50',
    'jd0_ut': 1629379.5,
    'jd1_ut': 358.78462715774}],
  ['J12',
   {'event': 'J12',
    'year': -250,
    'month': 1,
    'date': 8,
    'hour': 21,
    'minute': 19,
    'dateString': 'Jan 8',
    'timeString': '21:19',
    'jd0_ut': 1629744.5,
    'jd1_ut': 8.55491430365799}],
  ['Z12',
   {'event': 'Z12',
    'year': -250,
    'month': 1,
    'date': 23,
    'hour': 18,
    'minute': 3,
    'dateString': 'Jan 23',
    'timeString': '18:03',
    'jd0_ut': 1629744.5,
    'jd1_ut': 23.418670915664787}],
  ['J1',
   {'event': 'J1',
    'year': -250,
    'month': 2,
    'date': 7,
    'hour': 17,
    'minute': 18,
    'dateString': 'Feb 7',
    'timeString': '17:18',
    'jd0_ut': 1629744.5,
    'jd1_ut': 38.387677983639044}],
  ['Z1',
   {'event': 'Z1',
    'year': -250,
    'month': 2,
    'date': 22,
    'hour': 19,
    'minute': 49,
    'dateString': 'Feb 22',
    'timeString': '19:49',
    'jd0_ut': 1629744.5,
    'jd1_ut': 53.49231758221474}],
  ['J2',
   {'event': 'J2',
    'year': -250,
    'month': 3,
    'date': 10,
    'hour': 1,
    'minute': 30,
    'dateString': 'Mar 10',
    'timeString': '01:30',
    'jd0_ut': 1629744.5,
    'jd1_ut': 68.7294830296245}],
  ['Z2',
   {'event': 'Z2 (March equinox)',
    'year': -250,
    'month': 3,
    'date': 25,
    'hour': 10,
    'minute': 39,
    'dateString': 'Mar 25',
    'timeString': '10:39',
    'jd0_ut': 1629744.5,
    'jd1_ut': 84.11076204636416}],
  ['J3',
   {'event': 'J3',
    'year': -250,
    'month': 4,
    'date': 9,
    'hour': 22,
    'minute': 47,
    'dateString': 'Apr 9',
    'timeString': '22:47',
    'jd0_ut': 1629744.5,
    'jd1_ut': 99.61585250099941}],
  ['Z3',
   {'event': 'Z3',
    'year': -250,
    'month': 4,
    'date': 25,
    'hour': 13,
    'minute': 37,
    'dateString': 'Apr 25',
    'timeString': '13:37',
    'jd0_ut': 1629744.5,
    'jd1_ut': 115.23425344113146}],
  ['J4',
   {'event': 'J4',
    'year': -250,
    'month': 5,
    'date': 11,
    'hour': 6,
    'minute': 22,
    'dateString': 'May 11',
    'timeString': '06:22',
    'jd0_ut': 1629744.5,
    'jd1_ut': 130.93199232680843}],
  ['Z4',
   {'event': 'Z4',
    'year': -250,
    'month': 5,
    'date': 27,
    'hour': 0,
    'minute': 18,
    'dateString': 'May 27',
    'timeString': '00:18',
    'jd0_ut': 1629744.5,
    'jd1_ut': 146.6792014152924}],
  ['J5',
   {'event': 'J5',
    'year': -250,
    'month': 6,
    'date': 11,
    'hour': 18,
    'minute': 30,
    'dateString': 'Jun 11',
    'timeString': '18:30',
    'jd0_ut': 1629744.5,
    'jd1_ut': 162.43783074815417}],
  ['Z5',
   {'event': 'Z5 (June solstice)',
    'year': -250,
    'month': 6,
    'date': 27,
    'hour': 12,
    'minute': 1,
    'dateString': 'Jun 27',
    'timeString': '12:01',
    'jd0_ut': 1629744.5,
    'jd1_ut': 178.16723182187786}],
  ['J6',
   {'event': 'J6',
    'year': -250,
    'month': 7,
    'date': 13,
    'hour': 4,
    'minute': 5,
    'dateString': 'Jul 13',
    'timeString': '04:05',
    'jd0_ut': 1629744.5,
    'jd1_ut': 193.83693906002978}],
  ['Z6',
   {'event': 'Z6',
    'year': -250,
    'month': 7,
    'date': 28,
    'hour': 17,
    'minute': 47,
    'dateString': 'Jul 28',
    'timeString': '17:47',
    'jd0_ut': 1629744.5,
    'jd1_ut': 209.40776681216443}],
  ['J7',
   {'event': 'J7',
    'year': -250,
    'month': 8,
    'date': 13,
    'hour': 4,
    'minute': 47,
    'dateString': 'Aug 13',
    'timeString': '04:47',
    'jd0_ut': 1629744.5,
    'jd1_ut': 224.86590666054565}],
  ['Z7',
   {'event': 'Z7',
    'year': -250,
    'month': 8,
    'date': 28,
    'hour': 12,
    'minute': 26,
    'dateString': 'Aug 28',
    'timeString': '12:26',
    'jd0_ut': 1629744.5,
    'jd1_ut': 240.1844070460951}],
  ['J8',
   {'event': 'J8',
    'year': -250,
    'month': 9,
    'date': 12,
    'hour': 16,
    'minute': 53,
    'dateString': 'Sep 12',
    'timeString': '16:53',
    'jd0_ut': 1629744.5,
    'jd1_ut': 255.37026374160808}],
  ['Z8',
   {'event': 'Z8 (Sep. equinox)',
    'year': -250,
    'month': 9,
    'date': 27,
    'hour': 17,
    'minute': 56,
    'dateString': 'Sep 27',
    'timeString': '17:56',
    'jd0_ut': 1629744.5,
    'jd1_ut': 270.41405366707596}],
  ['J9',
   {'event': 'J9',
    'year': -250,
    'month': 10,
    'date': 12,
    'hour': 16,
    'minute': 13,
    'dateString': 'Oct 12',
    'timeString': '16:13',
    'jd0_ut': 1629744.5,
    'jd1_ut': 285.3420372582834}],
  ['Z9',
   {'event': 'Z9',
    'year': -250,
    'month': 10,
    'date': 27,
    'hour': 11,
    'minute': 52,
    'dateString': 'Oct 27',
    'timeString': '11:52',
    'jd0_ut': 1629744.5,
    'jd1_ut': 300.1611619608815}],
  ['J10',
   {'event': 'J10',
    'year': -250,
    'month': 11,
    'date': 11,
    'hour': 5,
    'minute': 53,
    'dateString': 'Nov 11',
    'timeString': '05:53',
    'jd0_ut': 1629744.5,
    'jd1_ut': 314.91179084995105}]],
 'mphase': [['Q0',
   {'event': 'New Moon',
    'year': -251,
    'month': 11,
    'date': 1,
    'hour': 8,
    'minute': 6,
    'dateString': 'Nov 1',
    'timeString': '08:06',
    'jd0_ut': 1629379.5,
    'jd1_ut': 305.0041343972275}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -251,
    'month': 11,
    'date': 8,
    'hour': 10,
    'minute': 56,
    'dateString': 'Nov 8',
    'timeString': '10:56',
    'jd0_ut': 1629379.5,
    'jd1_ut': 312.1222598391197}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -251,
    'month': 11,
    'date': 15,
    'hour': 8,
    'minute': 17,
    'dateString': 'Nov 15',
    'timeString': '08:17',
    'jd0_ut': 1629379.5,
    'jd1_ut': 319.0115389188933}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -251,
    'month': 11,
    'date': 23,
    'hour': 5,
    'minute': 21,
    'dateString': 'Nov 23',
    'timeString': '05:21',
    'jd0_ut': 1629379.5,
    'jd1_ut': 326.88970718156435}],
  ['Q0',
   {'event': 'New Moon',
    'year': -251,
    'month': 11,
    'date': 30,
    'hour': 22,
    'minute': 54,
    'dateString': 'Nov 30',
    'timeString': '22:54',
    'jd0_ut': 1629379.5,
    'jd1_ut': 334.6209143938907}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -251,
    'month': 12,
    'date': 7,
    'hour': 18,
    'minute': 57,
    'dateString': 'Dec 7',
    'timeString': '18:57',
    'jd0_ut': 1629379.5,
    'jd1_ut': 341.45595795450066}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -251,
    'month': 12,
    'date': 15,
    'hour': 0,
    'minute': 1,
    'dateString': 'Dec 15',
    'timeString': '00:01',
    'jd0_ut': 1629379.5,
    'jd1_ut': 348.66701798969905,
    'eclipse': 'Total lunar eclipse',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=-299&ind=111&DE=441&shrule=revised_Danjon&ref=python'}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -251,
    'month': 12,
    'date': 23,
    'hour': 2,
    'minute': 56,
    'dateString': 'Dec 23',
    'timeString': '02:56',
    'jd0_ut': 1629379.5,
    'jd1_ut': 356.78880866201763}],
  ['Q0',
   {'event': 'New Moon',
    'year': -251,
    'month': 12,
    'date': 30,
    'hour': 11,
    'minute': 58,
    'dateString': 'Dec 30',
    'timeString': '11:58',
    'jd0_ut': 1629379.5,
    'jd1_ut': 364.16504390002854,
    'eclipse': 'Partial solar eclipse',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=-299&ind=109&DE=441&ref=python'}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 1,
    'date': 6,
    'hour': 3,
    'minute': 39,
    'dateString': 'Jan 6',
    'timeString': '03:39',
    'jd0_ut': 1629744.5,
    'jd1_ut': 5.819029870415639}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 1,
    'date': 13,
    'hour': 17,
    'minute': 36,
    'dateString': 'Jan 13',
    'timeString': '17:36',
    'jd0_ut': 1629744.5,
    'jd1_ut': 13.39999685301384}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 1,
    'date': 21,
    'hour': 22,
    'minute': 11,
    'dateString': 'Jan 21',
    'timeString': '22:11',
    'jd0_ut': 1629744.5,
    'jd1_ut': 21.590943639094064}],
  ['Q0',
   {'event': 'New Moon',
    'year': -250,
    'month': 1,
    'date': 28,
    'hour': 23,
    'minute': 0,
    'dateString': 'Jan 28',
    'timeString': '23:00',
    'jd0_ut': 1629744.5,
    'jd1_ut': 28.62511018926719}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 2,
    'date': 4,
    'hour': 13,
    'minute': 57,
    'dateString': 'Feb 4',
    'timeString': '13:57',
    'jd0_ut': 1629744.5,
    'jd1_ut': 35.248244974440716}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 2,
    'date': 12,
    'hour': 11,
    'minute': 42,
    'dateString': 'Feb 12',
    'timeString': '11:42',
    'jd0_ut': 1629744.5,
    'jd1_ut': 43.1539226501219}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 2,
    'date': 20,
    'hour': 13,
    'minute': 50,
    'dateString': 'Feb 20',
    'timeString': '13:50',
    'jd0_ut': 1629744.5,
    'jd1_ut': 51.243159231803915}],
  ['Q0',
   {'event': 'New Moon',
    'year': -250,
    'month': 2,
    'date': 27,
    'hour': 8,
    'minute': 12,
    'dateString': 'Feb 27',
    'timeString': '08:12',
    'jd0_ut': 1629744.5,
    'jd1_ut': 58.00831229267649}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 3,
    'date': 6,
    'hour': 2,
    'minute': 19,
    'dateString': 'Mar 6',
    'timeString': '02:19',
    'jd0_ut': 1629744.5,
    'jd1_ut': 64.76310972482588}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 3,
    'date': 14,
    'hour': 4,
    'minute': 57,
    'dateString': 'Mar 14',
    'timeString': '04:57',
    'jd0_ut': 1629744.5,
    'jd1_ut': 72.87275274832018}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 3,
    'date': 22,
    'hour': 1,
    'minute': 27,
    'dateString': 'Mar 22',
    'timeString': '01:27',
    'jd0_ut': 1629744.5,
    'jd1_ut': 80.72697818556273}],
  ['Q0',
   {'event': 'New Moon',
    'year': -250,
    'month': 3,
    'date': 28,
    'hour': 16,
    'minute': 14,
    'dateString': 'Mar 28',
    'timeString': '16:14',
    'jd0_ut': 1629744.5,
    'jd1_ut': 87.34296210246426}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 4,
    'date': 4,
    'hour': 16,
    'minute': 39,
    'dateString': 'Apr 4',
    'timeString': '16:39',
    'jd0_ut': 1629744.5,
    'jd1_ut': 94.36054342231938}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 4,
    'date': 12,
    'hour': 20,
    'minute': 30,
    'dateString': 'Apr 12',
    'timeString': '20:30',
    'jd0_ut': 1629744.5,
    'jd1_ut': 102.52078782260928}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 4,
    'date': 20,
    'hour': 9,
    'minute': 23,
    'dateString': 'Apr 20',
    'timeString': '09:23',
    'jd0_ut': 1629744.5,
    'jd1_ut': 110.05782797604088}],
  ['Q0',
   {'event': 'New Moon',
    'year': -250,
    'month': 4,
    'date': 27,
    'hour': 0,
    'minute': 6,
    'dateString': 'Apr 27',
    'timeString': '00:06',
    'jd0_ut': 1629744.5,
    'jd1_ut': 116.67084100248293}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 5,
    'date': 4,
    'hour': 8,
    'minute': 30,
    'dateString': 'May 4',
    'timeString': '08:30',
    'jd0_ut': 1629744.5,
    'jd1_ut': 124.02091017236958}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 5,
    'date': 12,
    'hour': 10,
    'minute': 1,
    'dateString': 'May 12',
    'timeString': '10:01',
    'jd0_ut': 1629744.5,
    'jd1_ut': 132.0840138612833}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 5,
    'date': 19,
    'hour': 14,
    'minute': 42,
    'dateString': 'May 19',
    'timeString': '14:42',
    'jd0_ut': 1629744.5,
    'jd1_ut': 139.2792481594195}],
  ['Q0',
   {'event': 'New Moon',
    'year': -250,
    'month': 5,
    'date': 26,
    'hour': 8,
    'minute': 51,
    'dateString': 'May 26',
    'timeString': '08:51',
    'jd0_ut': 1629744.5,
    'jd1_ut': 146.03554483990834,
    'eclipse': 'Partial solar eclipse',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=-299&ind=110&DE=441&ref=python'}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 6,
    'date': 3,
    'hour': 1,
    'minute': 16,
    'dateString': 'Jun 3',
    'timeString': '01:16',
    'jd0_ut': 1629744.5,
    'jd1_ut': 153.7196359917709}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 6,
    'date': 10,
    'hour': 21,
    'minute': 32,
    'dateString': 'Jun 10',
    'timeString': '21:32',
    'jd0_ut': 1629744.5,
    'jd1_ut': 161.5636686405566,
    'eclipse': 'Total lunar eclipse',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=-299&ind=112&DE=441&shrule=revised_Danjon&ref=python'}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 6,
    'date': 17,
    'hour': 18,
    'minute': 52,
    'dateString': 'Jun 17',
    'timeString': '18:52',
    'jd0_ut': 1629744.5,
    'jd1_ut': 168.4529687332379}],
  ['Q0',
   {'event': 'New Moon',
    'year': -250,
    'month': 6,
    'date': 24,
    'hour': 19,
    'minute': 20,
    'dateString': 'Jun 24',
    'timeString': '19:20',
    'jd0_ut': 1629744.5,
    'jd1_ut': 175.47245728683188,
    'eclipse': 'Partial solar eclipse',
    'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=-299&ind=111&DE=441&ref=python'}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 7,
    'date': 2,
    'hour': 18,
    'minute': 25,
    'dateString': 'Jul 2',
    'timeString': '18:25',
    'jd0_ut': 1629744.5,
    'jd1_ut': 183.4338085121368}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 7,
    'date': 10,
    'hour': 7,
    'minute': 21,
    'dateString': 'Jul 10',
    'timeString': '07:21',
    'jd0_ut': 1629744.5,
    'jd1_ut': 190.97304356756078}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 7,
    'date': 16,
    'hour': 23,
    'minute': 34,
    'dateString': 'Jul 16',
    'timeString': '23:34',
    'jd0_ut': 1629744.5,
    'jd1_ut': 197.6484026479367}],
  ['Q0',
   {'event': 'New Moon',
    'year': -250,
    'month': 7,
    'date': 24,
    'hour': 8,
    'minute': 4,
    'dateString': 'Jul 24',
    'timeString': '08:04',
    'jd0_ut': 1629744.5,
    'jd1_ut': 205.00300252383713}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 8,
    'date': 1,
    'hour': 11,
    'minute': 21,
    'dateString': 'Aug 1',
    'timeString': '11:21',
    'jd0_ut': 1629744.5,
    'jd1_ut': 213.13952120713364}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 8,
    'date': 8,
    'hour': 16,
    'minute': 6,
    'dateString': 'Aug 8',
    'timeString': '16:06',
    'jd0_ut': 1629744.5,
    'jd1_ut': 220.3375076847566}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 8,
    'date': 15,
    'hour': 6,
    'minute': 23,
    'dateString': 'Aug 15',
    'timeString': '06:23',
    'jd0_ut': 1629744.5,
    'jd1_ut': 226.93256639302703}],
  ['Q0',
   {'event': 'New Moon',
    'year': -250,
    'month': 8,
    'date': 22,
    'hour': 23,
    'minute': 11,
    'dateString': 'Aug 22',
    'timeString': '23:11',
    'jd0_ut': 1629744.5,
    'jd1_ut': 234.63295465260558}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 8,
    'date': 31,
    'hour': 3,
    'minute': 22,
    'dateString': 'Aug 31',
    'timeString': '03:22',
    'jd0_ut': 1629744.5,
    'jd1_ut': 242.80667541271595}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 9,
    'date': 7,
    'hour': 0,
    'minute': 37,
    'dateString': 'Sep 7',
    'timeString': '00:37',
    'jd0_ut': 1629744.5,
    'jd1_ut': 249.69247580764429}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 9,
    'date': 13,
    'hour': 16,
    'minute': 36,
    'dateString': 'Sep 13',
    'timeString': '16:36',
    'jd0_ut': 1629744.5,
    'jd1_ut': 256.35852956699784}],
  ['Q0',
   {'event': 'New Moon',
    'year': -250,
    'month': 9,
    'date': 21,
    'hour': 16,
    'minute': 26,
    'dateString': 'Sep 21',
    'timeString': '16:26',
    'jd0_ut': 1629744.5,
    'jd1_ut': 264.351088169005}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 9,
    'date': 29,
    'hour': 17,
    'minute': 39,
    'dateString': 'Sep 29',
    'timeString': '17:39',
    'jd0_ut': 1629744.5,
    'jd1_ut': 272.40199571417907}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 10,
    'date': 6,
    'hour': 9,
    'minute': 50,
    'dateString': 'Oct 6',
    'timeString': '09:50',
    'jd0_ut': 1629744.5,
    'jd1_ut': 279.0761177946032}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 10,
    'date': 13,
    'hour': 6,
    'minute': 52,
    'dateString': 'Oct 13',
    'timeString': '06:52',
    'jd0_ut': 1629744.5,
    'jd1_ut': 285.9525301161068}],
  ['Q0',
   {'event': 'New Moon',
    'year': -250,
    'month': 10,
    'date': 21,
    'hour': 11,
    'minute': 0,
    'dateString': 'Oct 21',
    'timeString': '11:00',
    'jd0_ut': 1629744.5,
    'jd1_ut': 294.1246872114843}],
  ['Q1',
   {'event': 'First Quarter',
    'year': -250,
    'month': 10,
    'date': 29,
    'hour': 5,
    'minute': 40,
    'dateString': 'Oct 29',
    'timeString': '05:40',
    'jd0_ut': 1629744.5,
    'jd1_ut': 301.9028073524435}],
  ['Q2',
   {'event': 'Full Moon',
    'year': -250,
    'month': 11,
    'date': 4,
    'hour': 20,
    'minute': 26,
    'dateString': 'Nov 4',
    'timeString': '20:26',
    'jd0_ut': 1629744.5,
    'jd1_ut': 308.5181694842007}],
  ['Q3',
   {'event': 'Last Quarter',
    'year': -250,
    'month': 11,
    'date': 12,
    'hour': 0,
    'minute': 55,
    'dateString': 'Nov 12',

The function returns a python list with the following keys:

`'cm'`: a list containing the information of all Chinese months in the form of \[{'cm':m1, 'JDN':JDN1, 'jian':'jian1', 'n':n1}, {'cm':m2, 'JDN':JDN2, 'jian':'jian2', 'n':n2}, ...\] with 'cm' indicating the Chinese month number (negative for a leap month), 'JDN' indicating the Julian date at noon of the first day of the Chinese month, 'jian' indicating the sexagenary month cycle associated with jian ('jian'='1' for jia zi, '2' for yi chou, ... '60' for gui hai, 'NA' for months without jian (leap months or months before -103 when no Zhongqi rule was not imposed), 'NZ' for a month not containing a major solar term (only for the ancient six calendars)), and 'n' indicating the number of days in the Chinese month. The list is sorted in ascending order in the values in 'JDN'.

`'calendar'`: version of the Chinese calendar (e.g. 'Santong', 'Shixian').

`'reign/era'` (optional): reign and/or era name of the Chinese year (only for years before 1912).

`'calst'`: list of tuples \[(lab1, jdn1), (lab2, jdn2), ...\] where lab1, lab2, ... are the lables of the calendrical solar terms (e.g. 'J1', 'Z4') and jdn1, jdn2, ... are the Julian dates at noon of the solar terms.

`'datongST'` (optional): list of tuples \[(lab1, jdn1), (lab2, jdn2), ...\] of all the Datong solar terms in the Chinese year. This is only present for 1667 <= y <= 1669.

`'sterm'`: a list \[\[lab1, info1\], \[lab2, info2\], ...\] containing all solar terms based on DE431/DE441 in Chinese year y, where lab1, lab2, ... are the labels of the solar terms (e.g. 'J8', 'Z3') and info1, info2, ... are dictionaries containing the Western date and time information of the solar terms.

`'mphase'`: a list \[\[lab1, info1\], \[lab2, info2\], ...\] containing all moon phases based on DE431/DE441 in year y, where lab1, lab2, ... are the labels of the moon phases (e.g. 'Q0', 'Q3') and info1, info2, ... are dictionaries containing the Western date and time information of the moon phases.

The returned python list is not convenient for viewing. The `.chinese_year_info_html()` method geneartes an HTML text for a table, which can be viewed in the Jupyter notebook using `IPython.display.HTML()` function.

In [13]:
# Chinese year -250 in the Zhuanxu calendar
HTML(cal.chinese_year_html(-250, calendar='Zhuanxu'))

In [14]:
# Chinese year 2714 based on GB/T 33661-2017
HTML(cal.chinese_year_html(2714, calendar='GBT'))

In [15]:
# Extract all days in Chinese month 8 in the Chinese year 955 in the calendar used by the Liao dynasty
cal.chinese_to_western_year(955, 8, calendar='LiaoJinYuan')

[{'Chinese ymd': [955, 8, 1],
  'Western ymd': [955, 8, 20],
  'Western calendar': 'Julian',
  'JDN': 2070103,
  'cyear': 955,
  'cdate': '8-01',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Bing Shen', 33],
  'Week': ['Mon', 1],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 2],
  'Western ymd': [955, 8, 21],
  'Western calendar': 'Julian',
  'JDN': 2070104,
  'cyear': 955,
  'cdate': '8-02',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ding You', 34],
  'Week': ['Tue', 2],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 3],
  'Western ymd': [955, 8, 22],
  'Western calendar': 'Julian',
  'JDN': 2070105,
  'cyear': 955,
  'cdate': '8-03',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Wu Xu', 35],
  'Week': ['Wed', 3],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 4],
  'Western ymd': [955, 8, 23],
  'Western calendar': 'Julian',
  'JDN': 2070106,
  'cyear': 955,
  'cdate': '8-04',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji Hai', 36],
  'Week': ['Thu', 4],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 5],
  'Western ymd': [955, 8, 24],
  'Western calendar': 'Julian',
  'JDN': 2070107,
  'cyear': 955,
  'cdate': '8-05',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Zi', 37],
  'Week': ['Fri', 5],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 6],
  'Western ymd': [955, 8, 25],
  'Western calendar': 'Julian',
  'JDN': 2070108,
  'cyear': 955,
  'cdate': '8-06',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Xin Chou', 38],
  'Week': ['Sat', 6],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 7],
  'Western ymd': [955, 8, 26],
  'Western calendar': 'Julian',
  'JDN': 2070109,
  'cyear': 955,
  'cdate': '8-07',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ren Yin', 39],
  'Week': ['Sun', 0],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 8],
  'Western ymd': [955, 8, 27],
  'Western calendar': 'Julian',
  'JDN': 2070110,
  'cyear': 955,
  'cdate': '8-08',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Gui Mao', 40],
  'Week': ['Mon', 1],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 9],
  'Western ymd': [955, 8, 28],
  'Western calendar': 'Julian',
  'JDN': 2070111,
  'cyear': 955,
  'cdate': '8-09',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Jia Chen', 41],
  'Week': ['Tue', 2],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 10],
  'Western ymd': [955, 8, 29],
  'Western calendar': 'Julian',
  'JDN': 2070112,
  'cyear': 955,
  'cdate': '8-10',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Yi Si', 42],
  'Week': ['Wed', 3],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 11],
  'Western ymd': [955, 8, 30],
  'Western calendar': 'Julian',
  'JDN': 2070113,
  'cyear': 955,
  'cdate': '8-11',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Bing Wu', 43],
  'Week': ['Thu', 4],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 12],
  'Western ymd': [955, 8, 31],
  'Western calendar': 'Julian',
  'JDN': 2070114,
  'cyear': 955,
  'cdate': '8-12',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ding Wei', 44],
  'Week': ['Fri', 5],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 13],
  'Western ymd': [955, 9, 1],
  'Western calendar': 'Julian',
  'JDN': 2070115,
  'cyear': 955,
  'cdate': '8-13',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Wu Shen', 45],
  'Week': ['Sat', 6],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 14],
  'Western ymd': [955, 9, 2],
  'Western calendar': 'Julian',
  'JDN': 2070116,
  'cyear': 955,
  'cdate': '8-14',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji You', 46],
  'Week': ['Sun', 0],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 15],
  'Western ymd': [955, 9, 3],
  'Western calendar': 'Julian',
  'JDN': 2070117,
  'cyear': 955,
  'cdate': '8-15',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Xu', 47],
  'Week': ['Mon', 1],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 16],
  'Western ymd': [955, 9, 4],
  'Western calendar': 'Julian',
  'JDN': 2070118,
  'cyear': 955,
  'cdate': '8-16',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Xin Hai', 48],
  'Week': ['Tue', 2],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 17],
  'Western ymd': [955, 9, 5],
  'Western calendar': 'Julian',
  'JDN': 2070119,
  'cyear': 955,
  'cdate': '8-17',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ren Zi', 49],
  'Week': ['Wed', 3],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 18],
  'Western ymd': [955, 9, 6],
  'Western calendar': 'Julian',
  'JDN': 2070120,
  'cyear': 955,
  'cdate': '8-18',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Gui Chou', 50],
  'Week': ['Thu', 4],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 19],
  'Western ymd': [955, 9, 7],
  'Western calendar': 'Julian',
  'JDN': 2070121,
  'cyear': 955,
  'cdate': '8-19',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Jia Yin', 51],
  'Week': ['Fri', 5],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 20],
  'Western ymd': [955, 9, 8],
  'Western calendar': 'Julian',
  'JDN': 2070122,
  'cyear': 955,
  'cdate': '8-20',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Yi Mao', 52],
  'Week': ['Sat', 6],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 21],
  'Western ymd': [955, 9, 9],
  'Western calendar': 'Julian',
  'JDN': 2070123,
  'cyear': 955,
  'cdate': '8-21',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Bing Chen', 53],
  'Week': ['Sun', 0],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 22],
  'Western ymd': [955, 9, 10],
  'Western calendar': 'Julian',
  'JDN': 2070124,
  'cyear': 955,
  'cdate': '8-22',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ding Si', 54],
  'Week': ['Mon', 1],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 23],
  'Western ymd': [955, 9, 11],
  'Western calendar': 'Julian',
  'JDN': 2070125,
  'cyear': 955,
  'cdate': '8-23',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Wu Wu', 55],
  'Week': ['Tue', 2],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 24],
  'Western ymd': [955, 9, 12],
  'Western calendar': 'Julian',
  'JDN': 2070126,
  'cyear': 955,
  'cdate': '8-24',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji Wei', 56],
  'Week': ['Wed', 3],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 25],
  'Western ymd': [955, 9, 13],
  'Western calendar': 'Julian',
  'JDN': 2070127,
  'cyear': 955,
  'cdate': '8-25',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Shen', 57],
  'Week': ['Thu', 4],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 26],
  'Western ymd': [955, 9, 14],
  'Western calendar': 'Julian',
  'JDN': 2070128,
  'cyear': 955,
  'cdate': '8-26',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Xin You', 58],
  'Week': ['Fri', 5],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 27],
  'Western ymd': [955, 9, 15],
  'Western calendar': 'Julian',
  'JDN': 2070129,
  'cyear': 955,
  'cdate': '8-27',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ren Xu', 59],
  'Week': ['Sat', 6],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 28],
  'Western ymd': [955, 9, 16],
  'Western calendar': 'Julian',
  'JDN': 2070130,
  'cyear': 955,
  'cdate': '8-28',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Gui Hai', 60],
  'Week': ['Sun', 0],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 29],
  'Western ymd': [955, 9, 17],
  'Western calendar': 'Julian',
  'JDN': 2070131,
  'cyear': 955,
  'cdate': '8-29',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Jia Zi', 1],
  'Week': ['Mon', 1],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 30],
  'Western ymd': [955, 9, 18],
  'Western calendar': 'Julian',
  'JDN': 2070132,
  'cyear': 955,
  'cdate': '8-30',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Yi Chou', 2],
  'Week': ['Tue', 2],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'}]

In [16]:
# Create an HTML table for the Chinese month 8 in the Chinese year 955 
# in the calendar used by the Liao dynasty.
HTML(cal.chinese_to_western_year_html(955, 8, calendar='LiaoJinYuan'))

In [17]:
# Create an HTML table for the Chinese year 254
# in the calendar used by the Shu state.
HTML(cal.chinese_to_western_year_html(254, calendar='Shu'))

Unlike `.western_to_chinese_year_html()`, the dates of moon phases and solar terms under each month refer to the dates in the Chinese calendar.

## Moon phases and solar terms

Dates and times of moon phases and solar terms calculated by a modern ephemeris can be obtained from the `ChineseCalendar_py.sunMoon.sunMoon` class. The following commands create an instance of the `sunMoon` object.

In [18]:
sm = ccal.sunMoon.sunMoon('Eng')

The first parameter 'Eng' sets the display language as English. Two other possible parameters are 'ChiT' for traditional Chinese and 'ChiS' for simplified Chinese.

There is an optional second parameter (either 'DE431' or 'DE441') that allows the user to choose an ephemeris. When the second parameter is absent, it takes on the default value 'DE441' for JPL's DE441 ephemeris. for moon phases and solar terms to be JPL's DE441 ephemeris. DE441 and DE431 give practically identical moon phase and solar term times in years within a few hundred years from 2000. As mentioned above, the official moon phases and solar terms promulgated by the Purple Mountain Observatory in 2014-present (as of 2025) are calculated by JPL's DE421/LE421, which also gives practially identical moon phase and solar term times from 2014-present. The moon phases and solar terms promulgated by the government in 1929-2013 were calculated by older ephemerides and could deviate from those of DE431/DE441 by half minutes. Before 1929, moon phases and solar terms not only were calculated by old ephemerides but times were not given in UT+8. 

The TDB times of moon phases and solar terms in -3502-3503 are pre-computed by DE431 and DE441. They are stored in the files 'sunMoon_DE431.csv' and 'sunMoon_DE441.csv' in the folder `src/ChineseCalendar_py/`. Times in UT+8 are converted from the TDB times in the function `get_dTT_UT()` in `src/ChineseCalendar_py/` folder. This function will be updated on a yearly basis to incorporate the most up-to-date leap second data. As leap seconds will be abolished before 2035, the updates will be much less frequent after 2035.

In [19]:
# Extract solar terms and moon phases in 3500 
st, mp = sm.st_mp(3500)
print('solar terms:\n', st)
print('moon phases:\n', mp)

solar terms:
 [['J12', {'event': 'J12', 'year': 3500, 'month': 1, 'date': 6, 'hour': 7, 'minute': 2, 'dateString': 'Jan 6', 'timeString': '07:02', 'jd0_ut': 2999407.5, 'jd1_ut': 5.959842061353328}], ['Z12', {'event': 'Z12', 'year': 3500, 'month': 1, 'date': 21, 'hour': 1, 'minute': 14, 'dateString': 'Jan 21', 'timeString': '01:14', 'jd0_ut': 2999407.5, 'jd1_ut': 20.718280931005655}], ['J1', {'event': 'J1', 'year': 3500, 'month': 2, 'date': 4, 'hour': 18, 'minute': 54, 'dateString': 'Feb 4', 'timeString': '18:54', 'jd0_ut': 2999407.5, 'jd1_ut': 35.454193554548816}], ['Z1', {'event': 'Z1', 'year': 3500, 'month': 2, 'date': 19, 'hour': 12, 'minute': 59, 'dateString': 'Feb 19', 'timeString': '12:59', 'jd0_ut': 2999407.5, 'jd1_ut': 50.20746779877934}], ['J2', {'event': 'J2', 'year': 3500, 'month': 3, 'date': 6, 'hour': 8, 'minute': 1, 'dateString': 'Mar 6', 'timeString': '08:01', 'jd0_ut': 2999407.5, 'jd1_ut': 65.00048394186084}], ['Z2', {'event': 'Z2 (March equinox)', 'year': 3500, 'month': 3, 'date': 21, 'hour': 4, 'minute': 53, 'dateString': 'Mar 21', 'timeString': '04:53', 'jd0_ut': 2999407.5, 'jd1_ut': 79.86981892632781}], ['J3', {'event': 'J3', 'year': 3500, 'month': 4, 'date': 5, 'hour': 3, 'minute': 57, 'dateString': 'Apr 5', 'timeString': '03:57', 'jd0_ut': 2999407.5, 'jd1_ut': 94.83096817200175}], ['Z3', {'event': 'Z3', 'year': 3500, 'month': 4, 'date': 20, 'hour': 5, 'minute': 50, 'dateString': 'Apr 20', 'timeString': '05:50', 'jd0_ut': 2999407.5, 'jd1_ut': 109.90977010507072}], ['J4', {'event': 'J4', 'year': 3500, 'month': 5, 'date': 5, 'hour': 10, 'minute': 38, 'dateString': 'May 5', 'timeString': '10:38', 'jd0_ut': 2999407.5, 'jd1_ut': 125.10947091740418}], ['Z4', {'event': 'Z4', 'year': 3500, 'month': 5, 'date': 20, 'hour': 18, 'minute': 32, 'dateString': 'May 20', 'timeString': '18:32', 'jd0_ut': 2999407.5, 'jd1_ut': 140.4387534252777}], ['J5', {'event': 'J5', 'year': 3500, 'month': 6, 'date': 5, 'hour': 5, 'minute': 16, 'dateString': 'Jun 5', 'timeString': '05:16', 'jd0_ut': 2999407.5, 'jd1_ut': 155.88641968348998}], ['Z5', {'event': 'Z5 (June solstice)', 'year': 3500, 'month': 6, 'date': 20, 'hour': 18, 'minute': 34, 'dateString': 'Jun 20', 'timeString': '18:34', 'jd0_ut': 2999407.5, 'jd1_ut': 171.44049890975725}], ['J6', {'event': 'J6', 'year': 3500, 'month': 7, 'date': 6, 'hour': 9, 'minute': 52, 'dateString': 'Jul 6', 'timeString': '09:52', 'jd0_ut': 2999407.5, 'jd1_ut': 187.0776442874307}], ['Z6', {'event': 'Z6', 'year': 3500, 'month': 7, 'date': 22, 'hour': 2, 'minute': 25, 'dateString': 'Jul 22', 'timeString': '02:25', 'jd0_ut': 2999407.5, 'jd1_ut': 202.7670252144291}], ['J7', {'event': 'J7', 'year': 3500, 'month': 8, 'date': 6, 'hour': 19, 'minute': 31, 'dateString': 'Aug 6', 'timeString': '19:31', 'jd0_ut': 2999407.5, 'jd1_ut': 218.4800733389651}], ['Z7', {'event': 'Z7', 'year': 3500, 'month': 8, 'date': 22, 'hour': 12, 'minute': 11, 'dateString': 'Aug 22', 'timeString': '12:11', 'jd0_ut': 2999407.5, 'jd1_ut': 234.17463316911727}], ['J8', {'event': 'J8', 'year': 3500, 'month': 9, 'date': 7, 'hour': 3, 'minute': 50, 'dateString': 'Sep 7', 'timeString': '03:50', 'jd0_ut': 2999407.5, 'jd1_ut': 249.82667054395995}], ['Z8', {'event': 'Z8 (Sep. equinox)', 'year': 3500, 'month': 9, 'date': 22, 'hour': 17, 'minute': 28, 'dateString': 'Sep 22', 'timeString': '17:28', 'jd0_ut': 2999407.5, 'jd1_ut': 265.39453092715394}], ['J9', {'event': 'J9', 'year': 3500, 'month': 10, 'date': 8, 'hour': 4, 'minute': 49, 'dateString': 'Oct 8', 'timeString': '04:49', 'jd0_ut': 2999407.5, 'jd1_ut': 280.867087507004}], ['Z9', {'event': 'Z9', 'year': 3500, 'month': 10, 'date': 23, 'hour': 13, 'minute': 8, 'dateString': 'Oct 23', 'timeString': '13:08', 'jd0_ut': 2999407.5, 'jd1_ut': 296.21395772260337}], ['J10', {'event': 'J10', 'year': 3500, 'month': 11, 'date': 7, 'hour': 18, 'minute': 36, 'dateString': 'Nov 7', 'timeString': '18:36', 'jd0_ut': 2999407.5, 'jd1_ut': 311.44143044582245}], ['Z10', {'event': 'Z10', 'year': 3500, 'month': 11, 'date': 22, 'hour': 20, 'minute': 51, 'dateString': 'Nov 22', 'timeString': '20:51', 'jd0_ut': 2999407.5, 'jd1_ut': 326.5356782296335}], ['J11', {'event': 'J11', 'year': 3500, 'month': 12, 'date': 7, 'hour': 20, 'minute': 29, 'dateString': 'Dec 7', 'timeString': '20:29', 'jd0_ut': 2999407.5, 'jd1_ut': 341.52039177669093}], ['Z11', {'event': 'Z11 (Dec. solstice)', 'year': 3500, 'month': 12, 'date': 22, 'hour': 17, 'minute': 33, 'dateString': 'Dec 22', 'timeString': '17:33', 'jd0_ut': 2999407.5, 'jd1_ut': 356.3979728763978}]]
moon phases:
 [['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 1, 'date': 1, 'hour': 0, 'minute': 36, 'dateString': 'Jan 1', 'timeString': '00:36', 'jd0_ut': 2999407.5, 'jd1_ut': 0.6920066560282614}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 1, 'date': 9, 'hour': 3, 'minute': 40, 'dateString': 'Jan 9', 'timeString': '03:40', 'jd0_ut': 2999407.5, 'jd1_ut': 8.81968228343947, 'eclipse': 'Penumbral lunar eclipse', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=3401&ind=251&DE=441&shrule=revised_Danjon&ref=python'}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 1, 'date': 17, 'hour': 1, 'minute': 5, 'dateString': 'Jan 17', 'timeString': '01:05', 'jd0_ut': 2999407.5, 'jd1_ut': 16.71162403213348}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 1, 'date': 23, 'hour': 17, 'minute': 3, 'dateString': 'Jan 23', 'timeString': '17:03', 'jd0_ut': 2999407.5, 'jd1_ut': 23.377318247244986}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 1, 'date': 30, 'hour': 17, 'minute': 13, 'dateString': 'Jan 30', 'timeString': '17:13', 'jd0_ut': 2999407.5, 'jd1_ut': 30.384028430678082}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 2, 'date': 7, 'hour': 22, 'minute': 50, 'dateString': 'Feb 7', 'timeString': '22:50', 'jd0_ut': 2999407.5, 'jd1_ut': 38.617791239176576}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 2, 'date': 15, 'hour': 12, 'minute': 2, 'dateString': 'Feb 15', 'timeString': '12:02', 'jd0_ut': 2999407.5, 'jd1_ut': 46.16826826038512}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 2, 'date': 22, 'hour': 4, 'minute': 24, 'dateString': 'Feb 22', 'timeString': '04:24', 'jd0_ut': 2999407.5, 'jd1_ut': 52.8498902367278}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 3, 'date': 1, 'hour': 12, 'minute': 54, 'dateString': 'Mar 1', 'timeString': '12:54', 'jd0_ut': 2999407.5, 'jd1_ut': 60.20438817871954}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 3, 'date': 9, 'hour': 15, 'minute': 55, 'dateString': 'Mar 9', 'timeString': '15:55', 'jd0_ut': 2999407.5, 'jd1_ut': 68.3296250639521}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 3, 'date': 16, 'hour': 20, 'minute': 48, 'dateString': 'Mar 16', 'timeString': '20:48', 'jd0_ut': 2999407.5, 'jd1_ut': 75.53299498870601}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 3, 'date': 23, 'hour': 16, 'minute': 24, 'dateString': 'Mar 23', 'timeString': '16:24', 'jd0_ut': 2999407.5, 'jd1_ut': 82.35016297188179}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 3, 'date': 31, 'hour': 9, 'minute': 59, 'dateString': 'Mar 31', 'timeString': '09:59', 'jd0_ut': 2999407.5, 'jd1_ut': 90.08262437871339}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 4, 'date': 8, 'hour': 6, 'minute': 10, 'dateString': 'Apr 8', 'timeString': '06:10', 'jd0_ut': 2999407.5, 'jd1_ut': 97.92373732105295}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 4, 'date': 15, 'hour': 4, 'minute': 1, 'dateString': 'Apr 15', 'timeString': '04:01', 'jd0_ut': 2999407.5, 'jd1_ut': 104.83400699109681}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 4, 'date': 22, 'hour': 5, 'minute': 25, 'dateString': 'Apr 22', 'timeString': '05:25', 'jd0_ut': 2999407.5, 'jd1_ut': 111.89264053567214}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 4, 'date': 30, 'hour': 6, 'minute': 15, 'dateString': 'Apr 30', 'timeString': '06:15', 'jd0_ut': 2999407.5, 'jd1_ut': 119.92681408283815}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 5, 'date': 7, 'hour': 17, 'minute': 43, 'dateString': 'May 7', 'timeString': '17:43', 'jd0_ut': 2999407.5, 'jd1_ut': 127.40501613505016}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 5, 'date': 14, 'hour': 10, 'minute': 39, 'dateString': 'May 14', 'timeString': '10:39', 'jd0_ut': 2999407.5, 'jd1_ut': 134.11028834234236}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 5, 'date': 21, 'hour': 19, 'minute': 42, 'dateString': 'May 21', 'timeString': '19:42', 'jd0_ut': 2999407.5, 'jd1_ut': 141.48755136138817}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 5, 'date': 29, 'hour': 23, 'minute': 57, 'dateString': 'May 29', 'timeString': '23:57', 'jd0_ut': 2999407.5, 'jd1_ut': 149.66429954837122}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 6, 'date': 6, 'hour': 3, 'minute': 4, 'dateString': 'Jun 6', 'timeString': '03:04', 'jd0_ut': 2999407.5, 'jd1_ut': 156.79471775042782, 'eclipse': 'Partial lunar eclipse', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=3401&ind=252&DE=441&shrule=revised_Danjon&ref=python'}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 6, 'date': 12, 'hour': 17, 'minute': 47, 'dateString': 'Jun 12', 'timeString': '17:47', 'jd0_ut': 2999407.5, 'jd1_ut': 163.40769793681432}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 6, 'date': 20, 'hour': 11, 'minute': 1, 'dateString': 'Jun 20', 'timeString': '11:01', 'jd0_ut': 2999407.5, 'jd1_ut': 171.12551544418866, 'eclipse': 'Annular solar eclipse', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=3401&ind=250&DE=441&ref=python'}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 6, 'date': 28, 'hour': 14, 'minute': 21, 'dateString': 'Jun 28', 'timeString': '14:21', 'jd0_ut': 2999407.5, 'jd1_ut': 179.26460200118035}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 7, 'date': 5, 'hour': 10, 'minute': 52, 'dateString': 'Jul 5', 'timeString': '10:52', 'jd0_ut': 2999407.5, 'jd1_ut': 186.1191003268794}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 7, 'date': 12, 'hour': 2, 'minute': 33, 'dateString': 'Jul 12', 'timeString': '02:33', 'jd0_ut': 2999407.5, 'jd1_ut': 192.773169338639}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 7, 'date': 20, 'hour': 2, 'minute': 39, 'dateString': 'Jul 20', 'timeString': '02:39', 'jd0_ut': 2999407.5, 'jd1_ut': 200.77711769296496}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 7, 'date': 28, 'hour': 1, 'minute': 35, 'dateString': 'Jul 28', 'timeString': '01:35', 'jd0_ut': 2999407.5, 'jd1_ut': 208.73282494316825}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 8, 'date': 3, 'hour': 17, 'minute': 50, 'dateString': 'Aug 3', 'timeString': '17:50', 'jd0_ut': 2999407.5, 'jd1_ut': 215.4094330445667}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 8, 'date': 10, 'hour': 13, 'minute': 55, 'dateString': 'Aug 10', 'timeString': '13:55', 'jd0_ut': 2999407.5, 'jd1_ut': 222.24632955284363}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 8, 'date': 18, 'hour': 17, 'minute': 49, 'dateString': 'Aug 18', 'timeString': '17:49', 'jd0_ut': 2999407.5, 'jd1_ut': 230.40917836191667}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 8, 'date': 26, 'hour': 10, 'minute': 14, 'dateString': 'Aug 26', 'timeString': '10:14', 'jd0_ut': 2999407.5, 'jd1_ut': 238.09301618530733}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 9, 'date': 2, 'hour': 0, 'minute': 56, 'dateString': 'Sep 2', 'timeString': '00:56', 'jd0_ut': 2999407.5, 'jd1_ut': 244.705384971758}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 9, 'date': 9, 'hour': 4, 'minute': 21, 'dateString': 'Sep 9', 'timeString': '04:21', 'jd0_ut': 2999407.5, 'jd1_ut': 251.8482209148659}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 9, 'date': 17, 'hour': 8, 'minute': 3, 'dateString': 'Sep 17', 'timeString': '08:03', 'jd0_ut': 2999407.5, 'jd1_ut': 260.00230746307665}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 9, 'date': 24, 'hour': 17, 'minute': 4, 'dateString': 'Sep 24', 'timeString': '17:04', 'jd0_ut': 2999407.5, 'jd1_ut': 267.3780523834939}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 10, 'date': 1, 'hour': 9, 'minute': 19, 'dateString': 'Oct 1', 'timeString': '09:19', 'jd0_ut': 2999407.5, 'jd1_ut': 274.0546344019013}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 10, 'date': 8, 'hour': 21, 'minute': 42, 'dateString': 'Oct 8', 'timeString': '21:42', 'jd0_ut': 2999407.5, 'jd1_ut': 281.570885521494}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 10, 'date': 16, 'hour': 21, 'minute': 19, 'dateString': 'Oct 16', 'timeString': '21:19', 'jd0_ut': 2999407.5, 'jd1_ut': 289.55510690637067}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 10, 'date': 23, 'hour': 23, 'minute': 4, 'dateString': 'Oct 23', 'timeString': '23:04', 'jd0_ut': 2999407.5, 'jd1_ut': 296.62796921100306}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 10, 'date': 30, 'hour': 20, 'minute': 7, 'dateString': 'Oct 30', 'timeString': '20:07', 'jd0_ut': 2999407.5, 'jd1_ut': 303.50500727377096}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 11, 'date': 7, 'hour': 17, 'minute': 2, 'dateString': 'Nov 7', 'timeString': '17:02', 'jd0_ut': 2999407.5, 'jd1_ut': 311.3761620230932}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 11, 'date': 15, 'hour': 9, 'minute': 49, 'dateString': 'Nov 15', 'timeString': '09:49', 'jd0_ut': 2999407.5, 'jd1_ut': 319.07537457462996}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 11, 'date': 22, 'hour': 5, 'minute': 23, 'dateString': 'Nov 22', 'timeString': '05:23', 'jd0_ut': 2999407.5, 'jd1_ut': 325.89108874115215}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 11, 'date': 29, 'hour': 10, 'minute': 7, 'dateString': 'Nov 29', 'timeString': '10:07', 'jd0_ut': 2999407.5, 'jd1_ut': 333.08812331508364, 'eclipse': 'Partial lunar eclipse', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_lunar_eclipse_general.html?ybeg=3401&ind=253&DE=441&shrule=revised_Danjon&ref=python'}], ['Q3', {'event': 'Last Quarter', 'year': 3500, 'month': 12, 'date': 7, 'hour': 12, 'minute': 58, 'dateString': 'Dec 7', 'timeString': '12:58', 'jd0_ut': 2999407.5, 'jd1_ut': 341.2068875424675}], ['Q0', {'event': 'New Moon', 'year': 3500, 'month': 12, 'date': 14, 'hour': 21, 'minute': 39, 'dateString': 'Dec 14', 'timeString': '21:39', 'jd0_ut': 2999407.5, 'jd1_ut': 348.5689319389534, 'eclipse': 'Total solar eclipse', 'eclipse url': 'http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=3401&ind=251&DE=441&ref=python'}], ['Q1', {'event': 'First Quarter', 'year': 3500, 'month': 12, 'date': 21, 'hour': 13, 'minute': 19, 'dateString': 'Dec 21', 'timeString': '13:19', 'jd0_ut': 2999407.5, 'jd1_ut': 355.2211868041038}], ['Q2', {'event': 'Full Moon', 'year': 3500, 'month': 12, 'date': 29, 'hour': 3, 'minute': 12, 'dateString': 'Dec 29', 'timeString': '03:12', 'jd0_ut': 2999407.5, 'jd1_ut': 362.7999416139854}]]

In [20]:
# Extract solar terms and moon phases in 3500 and put them into pandas df's
st, mp = sm.st_mp_df(3500)
display(st)
display(mp)

             solar term    time (UT+8)
0                   J12   Jan 6, 07:02
1                   Z12  Jan 21, 01:14
2                    J1   Feb 4, 18:54
3                    Z1  Feb 19, 12:59
4                    J2   Mar 6, 08:01
5    Z2 (March equinox)  Mar 21, 04:53
6                    J3   Apr 5, 03:57
7                    Z3  Apr 20, 05:50
8                    J4   May 5, 10:38
9                    Z4  May 20, 18:32
10                   J5   Jun 5, 05:16
11   Z5 (June solstice)  Jun 20, 18:34
12                   J6   Jul 6, 09:52
13                   Z6  Jul 22, 02:25
14                   J7   Aug 6, 19:31
15                   Z7  Aug 22, 12:11
16                   J8   Sep 7, 03:50
17    Z8 (Sep. equinox)  Sep 22, 17:28
18                   J9   Oct 8, 04:49
19                   Z9  Oct 23, 13:08
20                  J10   Nov 7, 18:36
21                  Z10  Nov 22, 20:51
22                  J11   Dec 7, 20:29
23  Z11 (Dec. solstice)  Dec 22, 17:33

,New Moon,First Quarter,Full Moon,Last Quarter
0,,"Jan 1, 00:36","Jan 9, 03:40<br /><a href=""http://ytliu.epizy....","Jan 17, 01:05"
1,"Jan 23, 17:03","Jan 30, 17:13","Feb 7, 22:50","Feb 15, 12:02"
2,"Feb 22, 04:24","Mar 1, 12:54","Mar 9, 15:55","Mar 16, 20:48"
3,"Mar 23, 16:24","Mar 31, 09:59","Apr 8, 06:10","Apr 15, 04:01"
4,"Apr 22, 05:25","Apr 30, 06:15","May 7, 17:43","May 14, 10:39"
5,"May 21, 19:42","May 29, 23:57","Jun 6, 03:04<br /><a href=""http://ytliu.epizy....","Jun 12, 17:47"
6,"Jun 20, 11:01<br /><a href=""http://ytliu.epizy...","Jun 28, 14:21","Jul 5, 10:52","Jul 12, 02:33"
7,"Jul 20, 02:39","Jul 28, 01:35","Aug 3, 17:50","Aug 10, 13:55"
8,"Aug 18, 17:49","Aug 26, 10:14","Sep 2, 00:56","Sep 9, 04:21"
9,"Sep 17, 08:03","Sep 24, 17:04","Oct 1, 09:19","Oct 8, 21:42"
10,"Oct 16, 21:19","Oct 23, 23:04","Oct 30, 20:07","Nov 7, 17:02"
11,"Nov 15, 09:49","Nov 22, 05:23","Nov 29, 10:07<br /><a href=""http://ytliu.epizy...","Dec 7, 12:58"
12,"Dec 14, 21:39<br /><a href=""http://ytliu.epizy...","Dec 21, 13:19","Dec 29, 03:12",

Note that links to information on eclipses are provided in the moon phase data. To properly display the links, we can convert the pandas df to html and then use HTML to display the result. The resulting table is similar to my [moon phase and solar term page](https://ytliu0.github.io/ChineseCalendar/sunMoon.html).

In [21]:
HTML(mp.to_html(
    render_links=True,
    escape=False,
))

## Calendrical solar terms

Solar terms in the past were not calculated using modern ephemerides, but were calculated using the astronomical systems developed in the past. I call them the calendrical solar terms. The method `.calendrical_solar_terms(y, calendar="default", ephemeris='None')` returns the calendrical solar terms in Western year y. The argument 'ephemeris' is only relevant for the GBT calendar.

In [22]:
# calendrical solar term in 250 in the Wu state
cal.calendrical_solar_terms(250, calendar='Wu')

[{'solar term': 'J12', 'date': 'Jan 8'},
 {'solar term': 'Z12', 'date': 'Jan 23'},
 {'solar term': 'J1', 'date': 'Feb 7'},
 {'solar term': 'Z1', 'date': 'Feb 22'},
 {'solar term': 'J2', 'date': 'Mar 9'},
 {'solar term': 'Z2 (March equinox)', 'date': 'Mar 25'},
 {'solar term': 'J3', 'date': 'Apr 9'},
 {'solar term': 'Z3', 'date': 'Apr 24'},
 {'solar term': 'J4', 'date': 'May 9'},
 {'solar term': 'Z4', 'date': 'May 25'},
 {'solar term': 'J5', 'date': 'Jun 9'},
 {'solar term': 'Z5 (June solstice)', 'date': 'Jun 24'},
 {'solar term': 'J6', 'date': 'Jul 9'},
 {'solar term': 'Z6', 'date': 'Jul 24'},
 {'solar term': 'J7', 'date': 'Aug 9'},
 {'solar term': 'Z7', 'date': 'Aug 24'},
 {'solar term': 'J8', 'date': 'Sep 8'},
 {'solar term': 'Z8 (Sep. equinox)', 'date': 'Sep 23'},
 {'solar term': 'J9', 'date': 'Oct 9'},
 {'solar term': 'Z9', 'date': 'Oct 24'},
 {'solar term': 'J10', 'date': 'Nov 8'},
 {'solar term': 'Z10', 'date': 'Nov 23'},
 {'solar term': 'J11', 'date': 'Dec 8'},
 {'solar term': 'Z11 (Dec. solstice)', 'date': 'Dec 24'}]

In [23]:
# calendrical solar term in 250 in the Wu state displayed as a pandas df
display(pd.DataFrame(cal.calendrical_solar_terms(250, calendar='Wu')))

             solar term    date
0                   J12   Jan 8
1                   Z12  Jan 23
2                    J1   Feb 7
3                    Z1  Feb 22
4                    J2   Mar 9
5    Z2 (March equinox)  Mar 25
6                    J3   Apr 9
7                    Z3  Apr 24
8                    J4   May 9
9                    Z4  May 25
10                   J5   Jun 9
11   Z5 (June solstice)  Jun 24
12                   J6   Jul 9
13                   Z6  Jul 24
14                   J7   Aug 9
15                   Z7  Aug 24
16                   J8   Sep 8
17    Z8 (Sep. equinox)  Sep 23
18                   J9   Oct 9
19                   Z9  Oct 24
20                  J10   Nov 8
21                  Z10  Nov 23
22                  J11   Dec 8
23  Z11 (Dec. solstice)  Dec 24

Calendrical solar terms in a Chinese year can be obtained using the method `.chinese_year_info()` or `.chinese_year_html()` shown above.

## Calendar Exercises

The above summarizes the main functions provided by this package. You can see examples of using this package to perform advanced calendar calculations in the `calendar_exercises.ipynb` notebook in this folder.